### ISSUE TITLE
Refactor config to import base.config first, outside of profile scope

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#101]
_From @ewels on August 2, 2018 14:19_

See example of where I started doing this on the rnaseq pipeline here: https://github.com/ewels/nf-core-rnaseq/compare/config_refactor#diff-c79fe4336e72c04860afccd21f4ae1c5R17

_Copied from original issue: nf-core/cookiecutter#50_

**Comment by apeltzer** [comment]
I can work on this now, but we'd need some testing maybe first. I guess I'll add this to e.g. a separate branch of RNAseq and we could test on some infrastructures of our choice (uppmax, binac, cfc maybe?) to make sure these changes don't cause something troublesome. Any opinions on that?

**Comment by drpatelh** [comment]
Fixed with: https://github.com/nf-core/tools/pull/212
Can this be closed now?

**Comment by apeltzer** [comment]
Yes!
