### ISSUE TITLE
New lint test: schema param description

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#1017]
I can't think of a time when it's ok for a parameter in a schema to _not_ have a description. So we should probably lint for that and throw a warning.

Also warn if there are any ungrouped parameters.

**Comment by KevinMenden** [comment]
Looking into this, I realized that the lint tests are not self-contained. Meaning one only runs when the other has been run before. 
That's pretty dangerous, and in fact you can easily break it when running only `nf-core lint <pipeline> -k schema_params` 

So we should probably make that more robust/ the tests self-contained.

**Comment by ewels** [comment]
Yes, good point with the `-k`. You mean stuff like getting the pipeline config?

**Comment by KevinMenden** [comment]
Yeah creating the schema object, the error was easy to catch because we basically have a comment saying that:

```python
    # First, get the top-level config options for the pipeline
    # Schema object already created in the `schema_lint` test
    self.schema_obj.get_schema_path(self.wf_path)
    self.schema_obj.get_wf_params()
    self.schema_obj.no_prompts = True
```

**Comment by KevinMenden** [comment]
Remnants of the old code structure I guess
