### ISSUE TITLE
Sort out better release tagging for singularity

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#102]
_From @ewels on August 3, 2018 16:6_

Docker hub works nicely with automated builds based on GitHub releases which are tagged with the same name.

Singularity hub doesn't support the same method and instead has nasty filename based tagging support. However, there is a [very nice CLI](https://singularityhub.github.io/sregistry-cli/) that interacts with the API.

We should be able to use this CLI to automatically build and tag singularity hub containers when GitHub releases are prepared, using Travis CI.

_Copied from original issue: nf-core/cookiecutter#53_

**Comment by ewels** [comment]
_From @apeltzer on August 7, 2018 12:49_

We should discuss this too - maybe tomorrow?

**Comment by sven1103** [comment]
According to the documentation of the `sregistry` tool, there is no such a command as `add` for Singularity Hub from remote. The client can search and pull images from SHUB, but you cannot add images. 

What you can do is setting up a local registry and push the image to the local registry.

**Comment by ewels** [comment]
Can be closed as we no longer intend to use singularity hub.
