### ISSUE TITLE
Add minimum NF version to quick start section of main README

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1032]
The website currently trims off the badges off the top of the main README when rendered there. Given that this is currently the only place that the NF version is present in the README it would be good to add it somewhere else where it is quite visible.

e.g. as done here [here](https://github.com/nf-core/rnaseq/blob/38d5bbf60f698c62dc315bfee5437db5e58ebb7e/README.md#quick-start)

Will need to put this under bump versions control with nf-core/tools when updating the version of NF in the pipeline.

**Comment by KevinMenden** [comment]
So if I understand that correctly, we just add the Nextflow version to the Quick Start section of the `README.md` in the template, and then modify bump-versions to take this into account, right?

**Comment by drpatelh** [comment]
Yup. Exactly 👍🏽

**Comment by drpatelh** [comment]
I have put something like this [here](https://github.com/nf-core/rnaseq/tree/dev#quick-start) so the NF version needs to be recognised there and bumped if required.

**Comment by KevinMenden** [comment]
Alright, let's do that then, thanks! :+1:

**Comment by ewels** [comment]
Done in https://github.com/nf-core/tools/pull/1064
