### ISSUE TITLE
`params_used` lint check complains about all igenomes options

### ISSUE THREAD

**Issue by KevinMenden** [nf-core/tools#1055]
The new lint check whether params in `nextflow.config` are mentioned in `main.nf` leads to warnings for every genome in `igenomes.config`.

I feel like we should suppress warnings from `params.genoms.*`  by default?

![image](https://user-images.githubusercontent.com/15126788/117103015-d1f3dc80-ad79-11eb-8542-9f971e90e4c9.png)

**Comment by ewels** [comment]
Yup, or just anything that's an map / array..

**Comment by KevinMenden** [comment]
close by #1062

**Comment by ewels** [comment]
This did fix it, but I still get a couple of warnings from this test that we should also clear up:

```
params_used: Config variable not found in main.nf: params.igenomes_base                                                                                                                        
params_used: Config variable not found in main.nf: params.igenomes_ignore
```

I guess we need to add these to a special case list again or something? 🤔
