### ISSUE TITLE
Update comment style for modules function.nf

### ISSUE THREAD

**Issue by JoseEspinosa** [nf-core/tools#1076]
The style of the comments has been updated on the `rnaseq` and the `viralrecon` DSL2 pipelines  after adding the `EditorConfig` `Actions` see [here](https://github.com/nf-core/rnaseq/pull/629) and [here](https://github.com/nf-core/viralrecon/pull/188), respectively. On this way all the `.{nf,groovy,conf}` files have the comment style shown below:

```bash
//
// My awesome comment here
//
```

To make all the comments consistent, the template used to create the modules should be also updated to use the commenting style above on the `functions.nf` file.

**Comment by KevinMenden** [comment]
closing as has been fixed
