### ISSUE TITLE
Update/remove `params_used` lint check for DSL2 template

### ISSUE THREAD

**Issue by KevinMenden** [nf-core/tools#1105]
Adding this here so we don't forget.

The `params_used` lint check is currently not compatible with DSL2 as it checks for parameters in the `main.nf` file, which doesn't really contain params anymore now.

So we either need to adapt it to DSL2 or remove it.

Parameters should practically not be used within the modules code, but in the workflows in `workflows/` and maybe also in subworkflows? Checking all `.nf` in `workflows/` + `main.nf` would be a good start I guess.

**Comment by ewels** [comment]
This was removed in the v2.0 release I think, here: https://github.com/nf-core/tools/pull/1153
