### ISSUE TITLE
Lint check that documentation mentions all command line flags

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#111]
It would be great if we could check that all options (`params`) are described in the markdown documentation. We'll need the ability to have a list of exceptions, but it would ensure that the docs are kept up to date.

**Comment by drpatelh** [comment]
@ewels this will somehow be sorted with the now JSON schema right? Wondering if this is a duplicate is now redundant.

**Comment by ewels** [comment]
Yes, it will be redundant with https://github.com/nf-core/nf-co.re/issues/393

Once that's implemented we'll need to do a bit of cleaning up too, basically deleting a load of existing documentation from pipelines & the template.

**Comment by drpatelh** [comment]
So keep this open until we have removed everything from the template too?

**Comment by ewels** [comment]
Hmm, maybe a bit confusing. I'll make a new issue and close this one.

**Comment by ewels** [comment]
👉  https://github.com/nf-core/tools/issues/647
