### ISSUE TITLE
Lint Python code in pipeline template with Black

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1119]
We currently are using Black to lint the main tools repo but it would be nice to also lint any code added to the pipeline template itself. This would mean extending the Github Actions in the pipeline template. I have already added [ECLint CI tests](https://github.com/nf-core/tools/blob/afbed88e343512d72ecabb4d8c2c6a19eaf34d24/nf_core/pipeline-template/.github/workflows/linting.yml#L49-L62) to the pipeline template.

**Comment by ErikDanielsson** [comment]
Closing due to merge of #1119
