### ISSUE TITLE
Source repository of `external` modules is not stored in a pipeline

### ISSUE THREAD

**Issue by marc-jones** [nf-core/tools#1157]
## Is your feature request related to a problem? Please describe

The source repositories of modules installed from repositories other than `nf-core/modules` are not stored anywhere. Having them stored somewhere would allow the linter to check whether `external` modules are out of date and update them.

## Describe the solution you'd like

When a module is installed and the `-r` and `-b` command line arguments are set, those should be stored so the module code can be checked against the remote module code during linting.

## Describe alternatives you've considered

The commit SHA could also be saved, although I'm not sure if there's a way of creating GitHub links which are robust to repositories being renamed.

## Additional context

These are the locations (that I can think of) where code would need to be changed:

- Installing and removing modules in [`modules/pipeline_modules.py`](https://github.com/nf-core/tools/blob/7721f3742fc30a9e6e46d879404bd1366345092d/nf_core/modules/pipeline_modules.py#L198) would need to store the repo and branch details somewhere.
- Modules in the `external` folder would need to be returned by [`modules/lint.py.get_installed_modules()`](https://github.com/nf-core/tools/blob/7721f3742fc30a9e6e46d879404bd1366345092d/nf_core/modules/lint.py#L214)
- [`modules/lint.py.check_module_changes()`](https://github.com/nf-core/tools/blob/7721f3742fc30a9e6e46d879404bd1366345092d/nf_core/modules/lint.py#L373) would need to compare to the stored repo and branch, not the branch and repo given on the command line.

**Comment by drpatelh** [comment]
I believe this has been fixed in the latest release @marc-jones ? Be great if you can give it a go and close if so :)

**Comment by ErikDanielsson** [comment]
Closing as we have support for this since the v2.0 release.
