### ISSUE TITLE
Homebrew version of nextflow is out of date.

### ISSUE THREAD

**Issue by winni2k** [nf-core/tools#119]
Need to update version on homebrew-bio

**Comment by MaxUlysse** [comment]
I was wondering how can your commit appeared in the PR from someone else, but you made a PR on his repo, so no he's making a PR on the homebrew official repo...
That seems complicated

**Comment by winni2k** [comment]
Huh, that is weird.  I used to work for Chris.  I hope this isn't a security issue of some kind!

**Comment by winni2k** [comment]
Well, the PR has been merged.
