### ISSUE TITLE
Check if a module is installed before running nf-core modules install

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1199]
Manually removing a module with `rm -rf` and then trying to re-install won't do anything because the module info is still in `modules.json` so an `INFO` message is printed to screen suggesting that the module is up-to-date even though it has been deleted.

Maybe a better solution is to check whether the module is installed first and re-install at the commit in `modules.json` if it isn't. It may be a good idea to tidy up `modules.json` "before" installing any modules just to make sure that we have the same modules listed in the JSON and installed locally.

```bash
$ nf-core modules install

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.0.2.dev0



? Tool name: fastqc
INFO     'nf-core/modules/fastqc' is already up to date                                                                                                     install.py:108
```

**Comment by chasemc** [comment]
I was going to make an issue but I think it might be related to this. 

`nf-core modules lint` says out of date, ` nf-core modules install -a` says everything is fine

![image](https://user-images.githubusercontent.com/18691127/125515161-59c33ec4-b0e7-4fcc-abc6-c5b09e22083b.png)

**Comment by chasemc** [comment]
Yes, it is exactly what you described

**Comment by chasemc** [comment]
After downloading, running the linter results in warnings to update conda versions within module(s). 
However, updating the versions results in a `Local copy of module outdated` warning from the linter

**Comment by ErikDanielsson** [comment]
Closing due to the merge of #1200
