### ISSUE TITLE
Add alias `nf-core module` for `nf-core modules`

### ISSUE THREAD

**Issue by jfy133** [nf-core/tools#1216]
## Is your feature request related to a problem? Please describe

I keep thinking, oh I need a new **module**, lets get a template from nf-core tools.

Except then I write: `nf-core module <...>` rather than `nf-core <modules>`, which currently results in `Error: No such command 'module'.`

## Describe the solution you'd like

Set up an alias so if you run `nf-core module` it'll automatically run `nf-core modules` for you.

## Describe alternatives you've considered

I learn to memorise the command :grimacing:

**Comment by jfy133** [comment]
@ErikDanielsson @maxulysse fairly argued against due to parser cluttering

**Comment by maxulysse** [comment]
I argued mainly because you could just type properly ;-)
