### ISSUE TITLE
Install modules from custom repository ignores `-b` parameter

### ISSUE THREAD

**Issue by jfy133** [nf-core/tools#1218]
## Description of the bug

I would like to install an in development module from my fork into my pipeline.

`nf-core modules install` correctly picks up `-r jfy133/modules`, installing a version corresponding to `modules/jfy133/modules/damageprofiler/`. 

However, this installs whatever is on `master`, and not the branch, even though the branch is specified with `-b`.

```console
🧬 10:16:10 with 7GiB/15GiB in archaeodiet on  dsl2 via 🅒 nf-core ❯ nf-core modules -r jfy133/modules -b damageprofiler-update install damageprofiler

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.0.1



? Select 'damageprofiler' version: Rename software/ directory to modules/ to re-organise module structure (#567) e937c7950af70930d1f34bb961403d9d2aa81c7d
INFO     Installing damageprofiler                                                                                                                                                                            install.py:168
INFO     Downloaded 3 files to ./modules/jfy133/modules/damageprofiler           
```

Hash here is `e937c7950af70930d1f34bb961403d9d2aa81c7d`, whereas the latest hash of that module on the branch is 

![image](https://user-images.githubusercontent.com/17950287/126756844-edbb5982-332d-49f0-8886-2602695004c4.png)

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: `nf-core modules -r jfy133/modules -b damageprofiler-update install damageprofiler`

## Expected behaviour

Also correctly picks up branch.

## System

- Hardware: Laptop
- OS: Ubuntu 20.04
- Version of nf-core/tools: 2.0.1
- Python version: `3.6.12`

**Comment by jfy133** [comment]
> Is -r a bit confusing for this? That means release / branch / tag in other commands (eg. launch).
>
> (Same as Nextflow )

From :point_up: also fair point from @ewels (https://nfcore.slack.com/archives/CE5LG7WMB/p1627116833309500?thread_ts=1627028868.304100&cid=CE5LG7WMB)

**Comment by ErikDanielsson** [comment]
Closing due to the merge of #1219.
