### ISSUE TITLE
Running 'nf-core launch' results in "sticked on revision"

### ISSUE THREAD

**Issue by chasemc** [nf-core/tools#1246]
## Description of the bug

Using the -r flag with `nf-core launch` doesn't pass the flag on to the `nextflow run` command

## Steps to reproduce

Steps to reproduce the behaviour:

1. `nf-core launch nf-core/rnaseq -r dev`
2. See error: `Project 'nf-core/rnaseq' currently is sticked on revision: dev -- you need to specify explicitly a revision with the option '-r' to use it`
## Nextflow Installation

- Version: 
N E X T F L O W  ~  version 21.04.0
nf-core, version 2.1

**Comment by ErikDanielsson** [comment]
Closing with the merge of #1258.
