### ISSUE TITLE
Updating modules break EClint

### ISSUE THREAD

**Issue by maxulysse** [nf-core/tools#1248]
When updating modules with the `nf-core modules update` command, it modifies the `modules.json` file and remove the final newline, which raise an error with the EClint.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: 
2. See error: 

## System

- Hardware: 
- Executor: 
- OS: 
- Version of nf-core/tools: 
- Python version: 

## Nextflow Installation

- Version:

**Comment by drpatelh** [comment]
If you sync in the latest template updates this should be fixed by this https://github.com/nf-core/rnaseq/blob/8094c42add6dcdf69ce54dfdec957789c37ae903/.editorconfig#L15

**Comment by maxulysse** [comment]
I'll try that and close the issue then if it's not there anymore
