### ISSUE TITLE
`-c` argument to `nf-core modules create` "eats" too much/ignores `-c`

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/tools#1255]
## Description of the bug

When I specify `-c r-openxlsx` to `nf-core modules create` the tool thinks my module name is a Conda package.

## Steps to reproduce

Steps to reproduce the behaviour:

1. `nf-core modules create -c r-openxslx -l low sbdiexport` or `nf-core modules create sbdiexport -c r-openxslx -l low` (i.e. position of `sbdiexport` doesn't matter)
2. See error: `WARNING  Could not find Conda dependency using the Anaconda API: 'sbdiexport'`

## Expected behaviour

`sbdiexport` should be the name of the new module and it should use the `r-openxlsx` Conda/Docker/Singularity package.

## System

- OS: Ubuntu
- Version of nf-core/tools: 2.1
- Python version: 3.6.13

**Comment by erikrikarddaniel** [comment]
The title is a bit misleading. I think the `-c r-openxlsx` argument is just ignored.

**Comment by ErikDanielsson** [comment]
Closing due to the merge of #1256.
