### ISSUE TITLE
Non-updated lint tip message

### ISSUE THREAD

**Issue by jfy133** [nf-core/tools#1259]
## Description of the bug

Linting with files applicable for auto-fixing gives the following message:

```
Tip: Some of these linting errors can automatically be resolved with the following command:

    nf-core lint . --fix files_unchanged
```

However the `.` declaration has been removed in the latest version of nf-core tools, and so the command errors

```
Error: Got unexpected extra argument (.)
```

## Steps to reproduce

Modify a template file (e.g. `.github/CONTRIBUTING.md`, and run lint command

## Expected behaviour

Update message to remove `.`

## System

- nf-core tools version: 2.1

**Comment by ErikDanielsson** [comment]
Closing due to the merge of #1263.
