### ISSUE TITLE
Linting does not recognize README Nextflow minimum version mention in Quick Start

### ISSUE THREAD

**Issue by chris-cheshire** [nf-core/tools#1260]
When running `nf-core lint` with a readme file that has the following in it:

```
## Quick Start

1. Install [`Nextflow`](https://www.nextflow.io/docs/latest/getstarted.html#installation) (`>=21.04.0`)
```

A warning is triggered:

```
readme: README did not have a Nextflow minimum version mentioned in Quick Start section.
```

This warning should not be triggering as the minimum nextflow version is in the readme file.

Link to code location

https://github.com/nf-core/tools/blob/01291016652284bfba23a900399fa0155906a7c5/nf_core/lint/readme.py#L65-L66

**Comment by ErikDanielsson** [comment]
Closing due to the merge of #1261.
