### ISSUE TITLE
 nf-core/tools in slurm

### ISSUE THREAD

**Issue by marwa38** [nf-core/tools#1264]
Hello 
Anyway to download nf-core/tools in slurm (HPC)?
Thanks

**Comment by jfy133** [comment]
Hello,

Installation is based on your operating system, so it doesn't matter what scheduling system your hpc using.

Please see the nf-core tools documentation for installation instructions: https://github.com/nf-core/tools

You will most likely need either pip and/or conda installed on your HPC
