### ISSUE TITLE
Changing ext.args does not trigger a re-run on -resume 

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1285]
It would be nice if the pipeline was resumed from the appropriate process if any of the tool-specific arguments passed to it are amended. However, it appears like the pipelne is cached based on the string representation of the `script` section BEFORE any variable replacement.

This would ultimately mean users won't have to start the pipeline from scratch if they wanted to change an argument passed to one or more tools.

See: https://github.com/nf-core/rnaseq/pull/701#discussion_r725950463 and https://github.com/nextflow-io/nextflow/issues/2382

**Comment by mahesh-panchal** [comment]
Fixed in `21.10.0-SNAPSHOT build 5639`.
