### ISSUE TITLE
test_wf_use_local_configs is not working as expected

### ISSUE THREAD

**Issue by bunop** [nf-core/tools#1296]
## Description of the bug

Dear developers,

while testing `nf-core tools` for another feature, I found that the `DownloadTest.test_wf_use_local_configs` fails after the first successful attempt. The reason is that after the first execution, the example local configuration file is cached while the test is expecting to download a new copy of the test pipeline. Currently I noticed this behaviour in bot *master* and *dev* branch. Maybe in CI tests we can't see this behaviour since environment is cleaned up after tests

## Steps to reproduce

Steps to reproduce the behaviour:
```bash
$ pytest --color=yes tests/test_download.py::DownloadTest::test_wf_use_local_configs # execute without errors
$ pytest --color=yes tests/test_download.py::DownloadTest::test_wf_use_local_configs # fails
...
FAILED tests/test_download.py::DownloadTest::test_wf_use_local_configs - AssertionError: assert "'/tmp/tmp6ui.../../configs/'" == "'/tmp/tmp9uv.../../configs/'"
```

## Expected behaviour

Test needs to pass with success after first attempt without wiping out the `$HOME/.nextflow/nf-core` directory. 

## System

- Hardware: desktop
- Executor: local
- OS: Debian buster
- Version of nf-core/tools: dev
- Python version: 3.9.7

## Nextflow Installation

- Version: 21.04.3 build 5560

## Additional context

I fixed code by disabling cache during test. I will do a PR

**Comment by ewels** [comment]
Ah I didn't realise that the temporary directories are not removed. I thought that the system OS would clean them up on reboot etc? Either way, using your proposed method to clean up after ourselves sounds better - would be great if you fancy updating the tests to do this 👍

**Comment by bunop** [comment]
Yes, all contents in `/tmp` folder is removed in startup phase. However, those file remains for a longer period in machines that *rarely* restart. I remember, when I stated write python packages, that is a recommended practice to create all temporary files in `/tmp` folder and remove them after them are finished, however I can't find this reference now. Maybe I can work on them later and propose *tests with context managers* in another PR

**Comment by ewels** [comment]
Sounds good 👍🏻 Let's split this out into a new dedicated issue.

**Comment by ewels** [comment]
Made a new issue and assigned you. I closed this issue as the original topic is now resolved. Thanks!
