### ISSUE TITLE
Warn for the MD5 sum of empty files in the `test.yml` files.

### ISSUE THREAD

**Issue by charles-plessy** [nf-core/tools#1302]
I would like to suggest to warn for the MD5 sum `d41d8cd98f00b204e9800998ecf8427e` in the `test.yml` files, because it is an empty file, which may be a sign that the module is not functioning as expected.

See how often it occurs: https://github.com/nf-core/modules/search?q=d41d8cd98f00b204e9800998ecf8427e

Although empty files may be generated sometimes because test data is light, the best solution in these case would be to improve the tests to that they produce a real output.

**Comment by charles-plessy** [comment]
I found another funny MD5 sum, `7029066c27ac6f5ef18d660d5741979a`, for compressed empty files.  You can produce it with the following command: `printf '' | gzip -n | md5sum`.

It is more rare than the previous one, but still occurs in a couple of packages: https://github.com/nf-core/modules/search?q=7029066c27ac6f5ef18d660d5741979a

**Comment by ewels** [comment]
Done: Linting now checks for these two specific md5sum hashes and warns about them.

The test-yml builder also checks for empty files (or gzipped empty files). If it finds them, it does not add an md5sum to the test.yml and it throws an error at the end of execution. So this can be ignored in exceptions but should hopefully be pretty obvious.

See also https://github.com/nf-core/modules/pull/1167 where I wrote a small helper script to find suspicious md5sums in the YAML files. These two are the only super obvious ones though 👍🏻
