### ISSUE TITLE
JSON schema validation error with 21.10.0-SNAPSHOT 

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1304]
Copied across description from https://github.com/nextflow-io/nextflow/issues/2418

In the latest snapshot release, the parameter JSON schema validation we have in nf-core pipelines seems to be failing before the pipeline execution as a result of a mismatch between the observed and expected objects:

```
$ NXF_VER=21.10.0-SNAPSHOT nextflow run nf-core/rnaseq -profile test,singularity

ERROR: Validation of pipeline parameters failed!

* --hostnames: expected type: String, found: JSONObject ({"cfc":[".hpc.uni-tuebingen.de"],"utd_sysbio":["sysbio.utdallas.edu"],"utd_ganymede":["ganymede.utdallas.edu"],"genouest":[".genouest.org"],"cbe":[".cbe.vbc.ac.at"],"genotoul":[".genologin1.toulouse.inra.fr",".genologin2.toulouse.inra.fr"],"crick":[".thecrick.org"],"uppmax":[".uppmax.uu.se"],"icr_davros":[".davros.compute.estate"],"imperial":[".hpc.ic.ac.uk"],"binac":[".binac.uni-tuebingen.de"],"imperial_mb":[".hpc.ic.ac.uk"]})

```

Changing [this line](https://github.com/nf-core/rnaseq/blob/964425e3fd8bfc3dc7bce43279a98d17a874d3f7/nextflow_schema.json#L515 ) to "type": "object" in the parameter schema fixes it. However, this means that the latest version of NF will not be compatible with older versions of nf-core pipelines. This is very likely due to poor patch fixing on the nf-core side to get things working but it would be good to find a workaround.

The error is being raised from [NfcoreSchema.groovy](https://github.com/nf-core/rnaseq/blob/964425e3fd8bfc3dc7bce43279a98d17a874d3f7/lib/NfcoreSchema.groovy#L156-L158)

**Comment by pditommaso** [comment]
I've dumped the content of params_json [here](https://github.com/nf-core/rnaseq/blob/964425e3fd8bfc3dc7bce43279a98d17a874d3f7/lib/NfcoreSchema.groovy#L149) and made a diff between 21.04.x and 21.10.x versions. There are some interesting changes 

<img width="1793" alt="Screenshot 2021-10-30 at 10 57 32" src="https://user-images.githubusercontent.com/816968/139526786-1112d841-5aab-47af-b97f-8bda1c5f0377.png">

When using NF 21.04 the `genomes` params is reported as a map object that was rendered as a sole string value (which looks wrong). Instead with the latest version, the `genomes` is correctly handled as a nested map. 

Don't know why the stringify version of genomes was working, however, it looks to me the latest version has the correct version of the `genomes` structure.

I've attached the json params for your convenience in this comment


[params-json.zip](https://github.com/nf-core/tools/files/7446128/params-json.zip)

**Comment by drpatelh** [comment]
> map object that was rendered as a sole string value (which looks wrong)

Yep, this definitely looks wrong in the current implementation where those entries are somehow loaded and validated as a string instead of a map.

Assuming that we need to add a workaround in the nf-core validation script to correctly handle a map we only have 1 option as far as I can see. Changing [this line](https://github.com/nf-core/rnaseq/blob/964425e3fd8bfc3dc7bce43279a98d17a874d3f7/nextflow_schema.json#L515 ) to `"type": "object"` (and everywhere else a map is required) in the parameter schema fixes it. However, this means all currently released nf-core pipelines with a JSON schema will not work with the latest release of NF so the pipelines will have to be re-released with this fix.

We could try to update the validation script but I don't think that is the problem. The problem is a mismatch between the defined and expected object types...

**Comment by pditommaso** [comment]
still not sure to understand what the [hostname validation](https://github.com/nf-core/rnaseq/blob/964425e3fd8bfc3dc7bce43279a98d17a874d3f7/nextflow_schema.json#L515) should validate. 

That the user specified a hostname string? in that case it looks correct that's a string, no?

**Comment by drpatelh** [comment]
In this case, `params.hostnames` is actually defined independently from the pipeline code on nf-core/configs [here](https://github.com/nf-core/configs/blob/0600ac12932e8575c4c1380973ffd0e756209c29/nfcore_custom.config#L68-L82) and it is defined as a Groovy Map.

We have basically been using it to warn users if they are not using the correct nf-core config for their institution but it may easier to retire it at this point as I have done [here](https://github.com/nf-core/configs/pull/295) to fix the pressing issue with NF compatibility and either leave it out entirely or add it properly in the future.

**Comment by pditommaso** [comment]
Seems a good plan to me, think `genomes` may be affected with the same problem. I may have seen somewhere a similar validation rule using `string` instead of object

**Comment by drpatelh** [comment]
Luckily, we are ignoring the validation for `genomes` at the moment via a parameter called [`params.schema_ignore_params`](https://github.com/nf-core/rnaseq/blob/964425e3fd8bfc3dc7bce43279a98d17a874d3f7/nextflow.config#L99) which is why the nf-core pipeline validation won't fail for this particular parameter. We can update this quietly without telling anyone in the pipeline template 🤫

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/configs/pull/295

We will need to update the pipeline template accordingly to remove `params.hostnames` too.
