### ISSUE TITLE
auth problems with private modules repositories

### ISSUE THREAD

**Issue by bunop** [nf-core/tools#1306]
## Description of the bug

Dear developers,

I'm not sure if you plan to fully support this feature, but I found that using *nf-core tools* with private repositories (or even with public branches) has some issues when accessing modules outside from `nf-core/modules`.

## Steps to reproduce

Each of the following command lines have issues with other repositories than `nf-core/modules`:

```bash
nf-core modules --github-repository <a repository> --branch <a branch> list remote
nf-core modules --github-repository <a repository> --branch <a branch> --dir . <a module>
nf-core modules list local # after installing private modules
nf-core modules --github-repository <a repository> --branch <a branch> update <a module>
```

## Expected behaviour

*nf-core tool* lets to specify different repositories and branches with ``--github-repository`` and ``--branch`` options, and the ``modules.json`` has keys to model different repositories and *SHA* than the standard ``nf-core/modules``. Some requests methods to the github API already provide authentication with `auth=nf_core.utils.github_api_auto_auth()`, so the required paches are not so complex as we could expect.

## System

- Hardware:  Desktop
- Executor:  Local
- OS:  Debian Buster
- Version of nf-core/tools:  2.2.dev0
- Python version:  3.9.7

## Nextflow Installation

- Version:  21.04.3 build 5560

## Additional context

I can open a PR in which I had fixed such issues, however this context is difficult to test: should I prove that those patches works in your CI system? Should I need to mock up the API requests (and reponses)?

**Comment by ewels** [comment]
Fixed in https://github.com/nf-core/tools/pull/1307
