### ISSUE TITLE
Unexpected parameters warnings although defined in schema.json

### ISSUE THREAD

**Issue by praveenraj2018** [nf-core/tools#1315]
## Description of the bug

I noticed while testing #rnavar that it throws many "unexpected parameters" warnings. However these parameters were already defined in the nextflow_schema.json with default values and descriptions. That sounds quite unusual.

Then realized that the parameters in the warning were not grouped in the schema json. And putting them in a group resolved the warning messages. 

Looks like the code is not looking into the ungrouped parameters and I hope this is a minor bug that can be fixed. 

**Warning messages:**
```
(base) praveen@praveen-VirtualBox:~/coderepo/rnavar$ nextflow run main.nf -profile test,docker
N E X T F L O W  ~  version 21.04.1
Launching `main.nf` [romantic_austin] - revision: 52e76d2929
WARN: Found unexpected parameters:
* --skip_qc: false
* --qd_filter: 2.0
* --fs_filter: 30.0
* --cluster: 3
* --window: 35
* --scatter_count: 6
* --skip_variantfiltration: false
* --skip_intervallisttools: false
```

**Schema JSON file:**
https://github.com/praveenraj2018/rnavar/blob/dev/nextflow_schema.json

**Comment by maxulysse** [comment]
@praveenraj2018 do you still have this issue?

**Comment by praveenraj2018** [comment]
No. it has been resolved
