### ISSUE TITLE
Space missing in tip message for --fix files_unchanged

### ISSUE THREAD

**Issue by maxulysse** [nf-core/tools#1331]
## Description of the bug

a space is missing before `--fix files_unchanged`

```
Tip: Some of these linting errors can automatically be resolved with the 
following command:

    nf-core lint --dir /home/runner/work/rnavar/rnavar--fix files_unchanged
```

## Steps to reproduce

https://github.com/nf-core/rnavar/runs/4317868056?check_suite_focus=true#step:6:100

## System

- Hardware: 
- Executor: 
- OS: 
- Version of nf-core/tools: 
- Python version: 

## Nextflow Installation

- Version:

**Comment by mashehu** [comment]
Sorry, I can't reproduce that:
![Screenshot 2021-11-25 at 10 46 32](https://user-images.githubusercontent.com/6169021/143418270-1fc5475d-1dff-4bfd-a81a-144c9ec55c00.png)

And the space is also in the code, so I am a bit lost there...
https://github.com/nf-core/tools/blob/b48bce26b7da46cb71e4a8f78b68d9ceac579ca6/nf_core/lint_utils.py#L41

**Comment by maxulysse** [comment]
Do you see the same error as I on the GHA?
We're using `dev` now for the linting.

**Comment by mashehu** [comment]
Ah, you are correct, it is broken in `dev`. Sorry for that.

**Comment by maxulysse** [comment]
no worries
