### ISSUE TITLE
Pipeline CLI help could be more helpful for parameters with enumerated types

### ISSUE THREAD

**Issue by cjw85** [nf-core/tools#1346]
## Is your feature request related to a problem? Please describe

I'm always frustrated when running a workflow and forgetting the valid option values for a parameter of enumerated type in the parameter schema

## Describe the solution you'd like

When running `nextflow run .... --help` the help test should display the valid options for enumerated types.

## Describe alternatives you've considered

Manually inspecting the schema is a little dirty for end-users of a pipeline.

## Additional context

None

**Comment by ewels** [comment]
This has already been implemented and will be included in the upcoming release. See https://github.com/nf-core/tools/pull/1266

**Comment by cjw85** [comment]
The linked PR seems to only print validation failures, not include anything in the help message. This is a start but I don't think it really solves the issue of not knowing what the list of valid option values are. 

With the PR a user would have to know that an option can be one of several values (maybe it's not a required option and the default is not valid for them) and then deliberately enter an incorrect value to trigger the error message (without knowing that this is the case). They would also then only see up to five of the possible values, with no way of ascertaining the rest.
