### ISSUE TITLE
Add option to throw error when unexpected parameters are detected

### ISSUE THREAD

**Issue by matrulda** [nf-core/tools#1359]
# nf-core/tools feature request

I'd like a parameter that would change unexpected **warnings** to **errors**. This to avoid that misspelled parameter names are used and leaves silent errors. 

See discussion about the issue here: #1355

**Comment by mirpedrol** [comment]
With the new [nf-validation plugin](https://github.com/nextflow-io/nf-validation) that we now use for parameter validation, you can use `--validationFailUnrecognisedParams`
