### ISSUE TITLE
CI tests in pipeline template and tools repo install NF twice

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1361]
When you run the standard tests with the current code on `dev` in the pipeline template NF seems to be installed twice - once with the version specified above and then it is updated to the latest e.g. [here](https://github.com/drpatelh/nf-core-rnaseq/blob/2e09eb00d2c69dc83c6b6af3f9fa1373f782f045/.github/workflows/ci.yml#L23-L28)

![image](https://user-images.githubusercontent.com/23529759/145969695-6aed38ff-1926-443f-a771-fd2d0ce2fc0a.png)

A similar issue seems to be happening for the CI tests we use for the main #tools repo 
https://github.com/nf-core/tools/runs/4478346140?check_suite_focus=true

**Comment by drpatelh** [comment]
Running the `wget` command locally only installs NF once so looks like there is something else going on in the environment that is instructing it to update itself:

```
$ wget -qO- get.nextflow.io | bash
CAPSULE: Downloading dependency io.nextflow:nextflow:jar:21.10.5
CAPSULE: Downloading dependency io.nextflow:nf-commons:jar:21.10.5
CAPSULE: Downloading dependency io.nextflow:nf-httpfs:jar:21.10.5

      N E X T F L O W
      version 21.10.5 build 5658
      created 08-12-2021 14:39 UTC (14:39 BST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io


Nextflow installation completed. Please note:
- the executable file `nextflow` has been created in the folder: /home/patelh/testing/template
- you may complete the installation by moving it to a directory in your $PATH
```

**Comment by grst** [comment]
I mean, we *are* running `nextflow self-update` in addition to the installation. But that should do nothing if the correct version is already installed. 

Maybe a bug with`self-update` to always update to the latest version regardless of `NXF_VER`?

**Comment by grst** [comment]
Do we even need the `self-update` command at all?

**Comment by ewels** [comment]
Ok I think I figured it out, maybe. My guess is that it's because GitHub Actions matrix variables are automatically propagated as environment variables: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix

So we are setting `NXF_VER` _and_ `NXF_EDGE` even when we comment out the latter.

**Comment by ewels** [comment]
Nope, whilst the matrix vars _do_ propagate (meaning we can clean up some code) that's not causing it. I think maybe you're right @grst - it's the `self-update` command..

**Comment by ewels** [comment]
> Ok I think I figured it out, maybe. My guess is that it's because GitHub Actions matrix variables are automatically propagated as environment variables: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix
> 
> So we are setting `NXF_VER` _and_ `NXF_EDGE` even when we comment out the latter.

I'm talking rubbish. I should not code with a headache.

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/tools/pull/1362
