### ISSUE TITLE
module create-test-yml is keeping /tmp/ directories in the output

### ISSUE THREAD

**Issue by SPPearce** [nf-core/tools#1371]
### Description of the bug

With the most recent v2.2.0 version, the `nf-core modules create-test-yml` function is a bit broken, it generates a test.yml file which includes the /tmp/.... file path where the file is run.

### Command used and terminal output

```console
nf-core modules create-test-yml samtools/sort

Generates a test.yml file, but the file includes the /tmp file path:

files:
    - path: /tmp/tmp8ybsopnd/samtools/test.sorted.bam
      md5sum: 4adc495469724a375d5e1a9f3485e38d
    - path: /tmp/tmp8ybsopnd/samtools/versions.yml
      md5sum: cd21543765087489f54d49a4cf070252
```

### System information

Nextflow version: 21.10.05
Hardware: HPC
Executor: local
Version of nf-core/tools: 2.2
Python version : 3.8.6

**Comment by ewels** [comment]
Fixed in https://github.com/nf-core/tools/pull/1372
