### ISSUE TITLE
Schema - error when calling `printExceptions`

### ISSUE THREAD

**Issue by dstrib** [nf-core/tools#1402]
### Description of feature

If it would be possible to increase the amount of detail provided in this error message: 

```
ERROR: Validation of pipeline parameters failed!
```

That might be helpful. I'm not sure if this is something that other people would run into as well, but it took me embarrassingly long to figure out that this "intermittent" error was because I was trying to use an `--input` file ending in `.csv` rather than `.txt`.

**Comment by jfy133** [comment]
I also had a similar issue on with fetchngs,

```
ERROR: Validation of pipeline parameters failed!
Unknown method invocation `printExceptions` on NfcoreSchema type
 -- Check script '/home/jfellows/.nextflow/assets/nf-core/fetchngs/main.nf' at line: 20 or see '.nextflow.log' file for more details
```

In this case I had an extra new line at the end. This wasn't accepted by fetchNGS as it wasn't a valid accession number; and so  it failed. But rather than telling me that was the issue (so no informative error message), I got the above generic error.

**Comment by ewels** [comment]
I thought that we already do print additional information?

This bit is a bug in the template code functionality:

```
Unknown method invocation `printExceptions` on NfcoreSchema type
 -- Check script '/home/jfellows/.nextflow/assets/nf-core/fetchngs/main.nf' at line: 20 or see '.nextflow.log' file for more details
```

So if that was what followed your message as well @dstrib then that makes sense. In which case this is a bugfix issue and not about adding new functionality.

**Comment by ewels** [comment]
To be clear, it's the `printExceptions` function that does this and which presumably isn't being called here for some reason. This [is present](https://github.com/nf-core/tools/blob/e563811adb292b07ec933a52611e937ce9ef5481/nf_core/pipeline-template/lib/NfcoreSchema.groovy#L333-L367) in the fetchngs pipeline.

**Comment by dstrib** [comment]
Indeed @ewels, that is the message that I am getting.

**Comment by asthara10** [comment]
Hi! I started to work on this, could you tell me how to replicate this error message? 
If I try to introduce an error to nf-params.json I get the error: 
```
ERROR    [✗] Input parameters are invalid: '' does not match '^\\S+\\.csv$'
```
which I think is not triggered by the same function.

**Comment by ewels** [comment]
@asthara10 this discussion is about validation in pipeline runs - that is, when doing `nextflow run ...` and not when running `nf-core ...`

To replicate, you'll want to make a new skeleton pipeline and try running with that:

```bash
nf-core create
cd nf-core-test
nextflow run . --input foo
```

(or something, commands off the top of my head)

**Comment by asthara10** [comment]
It seems that the error is from the pipeline (fixed in `tools/nf_core/pipeline-template/lib/NfcoreSchema.groovy`).
The argument `enums` is missing when the function printExceptions() is called recursively in line 365 
https://github.com/nf-core/fetchngs/blob/c318ae12fcb972ff28f6d38edd3165c88b6d0b3f/lib/NfcoreSchema.groovy#L365

After adding the argument in my local copy of fetchngs the exceptions are printed. To confirm that, I deleted the argument from rnaseq pipeline (which doesn't have the bug) and reproduced the same error.

I can open a PR to `fetchngs`, but should we warn the maintainers of all pipelines that there might be an error here?
