### ISSUE TITLE
wrong yamllint config

### ISSUE THREAD

**Issue by mashehu** [nf-core/tools#1413]
### Description of the bug

It looks like `yamllint.yml` is not recognized by the npm-version of yamllint (https://github.com/nf-core/tools/pull/1412#issuecomment-1041549974), which is the one the github action uses. 

So, we either can use a different yaml-lint config or we switch to a different yamllint in the github action, e.g. this one seems to be based on the yamllint we wrote the `yamllint.yml` for (and have installed in the gitpod image) https://github.com/marketplace/actions/yamllint-github-action

**Comment by JoseEspinosa** [comment]
After some try and error, I think the best will be to switch to the GitHub action you proposed above, I will try to draft a PR as soon as I can

**Comment by ewels** [comment]
I think we've talked about using Prettier before to consolidate markdown and YAML into one tool. Maybe now would be a good time?

**Comment by mashehu** [comment]
I looked a bit into switching into prettier over the weekend. I think we should stick with markdown-lint and yaml-lint for now, because most of our markdown rules (e.g. `ul-indent`,`no-duplicate-header`, etc.) can not be replicated in a prettier config as far as I can see. But if you say these rules are not that important we could switch.

**Comment by JoseEspinosa** [comment]
Tried to fix this issue here https://github.com/nf-core/tools/pull/1422

**Comment by JoseEspinosa** [comment]
In the PR above, I switch to the github action proposed by @mashehu, might have lost some discussion since I could not connect last week.
