### ISSUE TITLE
Make --outdir a mandatory parameter

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1415]
### Description of feature

We need to re-assess what we set `--outdir` by default in the nf-core pipeline template.

It is currently set to `./results` which is fine for shared file systems / HPC environments but with the growing adoption of Cloud this simply doesn't work anymore and can end up costing money and time if an absolute path isn't provided instead of a relative one. e.g. on AWS Batch, by default the results will get written to the head node and are lost with it.

We have tried to add a solution that checks if we are using `-profile awsbatch` and to raise an error if we aren't using an absolute path [here](https://github.com/nf-core/tools/blob/e563811adb292b07ec933a52611e937ce9ef5481/nf_core/pipeline-template/lib/NfcoreTemplate.groovy#L17) but that will only work for those using `-profile awsbatch` and so isn't a generic solution.

The only solution I can see is to make `--outdir` a mandatory parameter. This would avoid silent failures at the very least and can easily be set to the current default value within a config albeit a local or institutional one.

**Comment by drpatelh** [comment]
One problem we have here is that if we set `--outdir = null` in `nextflow.config` then [`tracedir`](https://github.com/nf-core/tools/blob/e563811adb292b07ec933a52611e937ce9ef5481/nf_core/pipeline-template/nextflow.config#L28) gets evaluated to `null/pipeline_info` even if `--outdir ./results` is specified on the CLI.

Wondering what the best solution is here 🤔 Ping @mahesh-panchal

**Comment by pditommaso** [comment]
I think it would make more sense to address this on nextflow. Likely adding a configuration setting that when enable instructs Nextflow to resolve relative paths against the work-dir instead of the launching directory. We had already a chat with @jordeu at this regard. Could be an issue opened in the Nextflow repo?

**Comment by drpatelh** [comment]
Thanks @pditommaso ! Done https://github.com/nextflow-io/nextflow/issues/2661

**Comment by drpatelh** [comment]
Will be fixed in https://github.com/nf-core/tools/pull/1431
