### ISSUE TITLE
pin node version number with setup-node in GHA

### ISSUE THREAD

**Issue by maxulysse** [nf-core/tools#1425]
### Description of feature

Node version installed is the linting tests is not specified, so it's the default one, which might change overtime.
I think it should be good to actually pin a node version (which is possible with the `setup-node` GHA that we are currently using.

**Comment by mashehu** [comment]
We switched away from the node version of yamllint to the conda version, due to issues with the config file. Or are you talking about a different github action?

**Comment by ewels** [comment]
Closing as we deliberately removed this and I'm not super keen to add it back again. I think stuff will break over time either way.. But generally the new Prettier action should also update in line with node, so likely to be more stable to leave both unpinned I think.
