### ISSUE TITLE
nf-core download not working for rnaseq and singularity images

### ISSUE THREAD

**Issue by DrOllyGomez** [nf-core/tools#1459]
getting this critical error on Ubuntu 20.04...
===================
mike.harbour@bioinf3:~$ nf-core download
    nf-core/tools version 2.2

Specify the name of a nf-core pipeline or a GitHub repository name (user/repo).
? Pipeline name: rnaseq
? Select release / branch: 3.6  [release]

In addition to the pipeline code, this tool can download software containers.
? Download software container images: singularity

If transferring the downloaded files to another system, it can be convenient to have everything 
compressed in a single file.
This is not recommended when downloading Singularity images, as it can take a long time and saves very
little space.
? Choose compression type: none
INFO     Saving 'nf-core/rnaseq'                                                       download.py:160
          Pipeline revision: '3.6'                                                                    
          Pull containers: 'singularity'                                                              
          Using $NXF_SINGULARITY_CACHEDIR': /home/mike.harbour/nfcoreSingularity                      
          Output directory: 'nf-core-rnaseq-3.6'                                                      
INFO     Downloading workflow files from GitHub                                        download.py:163
INFO     Downloading centralised configs from GitHub                                   download.py:167
INFO     Found 1 container                                                             download.py:472
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% • 0/1 completed
${ workflow.containerEngine ==  Copying from cache to target directory ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CRITICAL [Errno 2] No such file or directory: '/home/mike.harbour/nfcoreSingularity/${ download.py:182
         workflow.containerEngine == .img'         

===================
Anyone able to help? What else do I need to post here that can help diagnosis?
Best
Mike

**Comment by DrOllyGomez** [comment]
> What else do I need to post here that can help diagnosis?
heres some things..

mike.harbour@bioinf3:~$ nextflow info
  Version: 21.10.6 build 5661
  Created: 21-12-2021 17:01 UTC (17:01 BST)
  System: Linux 5.4.0-99-generic
  Runtime: Groovy 3.0.9 on OpenJDK 64-Bit Server VM 11.0.14+9-Ubuntu-0ubuntu2.20.04
  Encoding: UTF-8 (UTF-8)

**Comment by mashehu** [comment]
We just updated nf-core tools to version 2.3. Could you please try it again with the updated version?

**Comment by DrOllyGomez** [comment]
will do.....

**Comment by DrOllyGomez** [comment]
...thats worked fine. many thanks. closing issue ticket..
