### ISSUE TITLE
Validate input parameter type with that in the schema

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1481]
### Description of feature

A couple of users have tripped up thinking e.g. the `--trim_nextseq` parameter is boolean when in fact it should be an integer. This is quite tricky conceptually because if you don't provide a value after a Nextflow params on the CLI then it is automatically treated as a boolean. We could try to check the value of the variable in the resolved Nextflow configuration matches that which is defined in the schema and fail elegantly. I have a feeling we (I) have tried this already but failed miserably - would be worth another shot me thinks.

**Comment by ewels** [comment]
Is this now solved with nf-validation @mirpedrol ?

**Comment by mirpedrol** [comment]
If the parameter should be an integer but a boolean is provided (with `--trim_nextseq 1.1` or `--trim_nextseq`), the validation will fail with the message saying that this parameter must be an integer. Was this the expected behaviour?

**Comment by ewels** [comment]
I think so, right @drpatelh ?

**Comment by drpatelh** [comment]
Yep, sounds about right 🚀
