### ISSUE TITLE
nf-core bump-version does not adjust PATH in Dockerfile and Singularity

### ISSUE THREAD

**Issue by sven1103** [nf-core/tools#150]
Expected behaviour:

The command `bump-version` (earlier `release`) adjusts the environment PATH for conda with the correct bumped version number.

Actual behaviour:

Both PATHs statements in the **Dockerfile** and **Singularity** file remain unchanged.

**Comment by ewels** [comment]
Crap, you're right... I'm sure this used to work - sorry, I must have broken something.

**Comment by ewels** [comment]
Or maybe it didn't actually. Either way, I'll add it now.

**Comment by sven1103** [comment]
We installed packages into the conda root dir, and this PATH is added my default, when installing conda. So we did not have this line :)

**Comment by ewels** [comment]
Ok, added - #149 not merged yet so was appended onto that PR...
