### ISSUE TITLE
modules.json file is updated for all modules

### ISSUE THREAD

**Issue by maxulysse** [nf-core/tools#1514]
### Description of the bug

Using `nf-core modules update -a` with the interactive possibility to check out diff.
All modules are updated in the `modules.json` file, even the one I did not accept

### System information

Using latest tools@dev

**Comment by fabianegli** [comment]
This might be linked with the redefinition of the `moduel` variable in the update function...

```
$ pylint -f colorized --disable all --enable R1704 update.py
provi.py:141:24: R1704: Redefining argument with the local name 'module' (redefined-argument-from-local)
provi.py:146:24: R1704: Redefining argument with the local name 'module' (redefined-argument-from-local)
provi.py:160:24: R1704: Redefining argument with the local name 'module' (redefined-argument-from-local)
provi.py:226:26: R1704: Redefining argument with the local name 'module' (redefined-argument-from-local)
```
until now, it's just an educated guess. I am lacking a test environment for this.

**Comment by ggabernet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [nf-core modules](https://trello.com/c/TRNv6fzy/7-nf-core-modules)

**Comment by ewels** [comment]
@maxulysse - can you check this again please? Neither @mirpedrol or I can replicate the error.. (maybe it's been fixed somewhere already)

**Comment by ewels** [comment]
Just remembered that @maxulysse is on holiday, so I think we go ahead and close this until we can replicate 👍🏻
