### ISSUE TITLE
Is there support to adopt the "good-first-issue" label in this repo?

### ISSUE THREAD

**Issue by fabianegli** [nf-core/tools#1528]
### Description of feature

Issues labelled as such are collected here on GitHub https://github.com/topics/good-first-issue and on other sites that encourage the public to contribute. I think this is a great way to get contributions and give the repo more exposure.

Is there support to adopt the "good-first-issue" label in this repo?

**Comment by jfy133** [comment]
Other pipelines independently have this, and I see no reason why not to have it ;) I've just made it for you!

**Comment by fabianegli** [comment]
Thank you 😄
