### ISSUE TITLE
README logo not being rendered

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1530]
### Description of the bug

It appears that the path to the logo used in the README isn't being found and hence the image isn't being rendered. If we look at the template PR for rnaseq [here](https://github.com/nf-core/rnaseq/tree/nf-core-template-merge-2.3.2) the path to the image at the top of the README is:

```
# ![nf-core/rnaseq](docs/images/nf-core/rnaseq_logo_light.png#gh-light-mode-only) ![nf-core/rnaseq](docs/images/nf-core/rnaseq_logo_dark.png#gh-dark-mode-only)
```

However it should be:
```
# ![nf-core/rnaseq](docs/images/nf-core-rnaseq_logo_light.png#gh-light-mode-only) ![nf-core/rnaseq](docs/images/nf-core-rnaseq_logo_dark.png#gh-dark-mode-only)
```

Note, it should be `nf-core-rnaseq_logo*` and not `nf-core/rnaseq_logo*`.

In the pipeline template the logo based Jinja variables are `logo_light` and `logo_dark`. These will need to be fixed and checked wherever else they are being used.

**Comment by asthara10** [comment]
It seems that it is already fixed in dev version 2.4, so I am closing the issue
