### ISSUE TITLE
Remove nf-core branding from pipeline template

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1548]
### Description of feature

It would be awesome if we can have an option to remove the nf-core branding when creating pipelines and for this to work with all of the existing tooling we have.

A few members in the community including myself have created a number of pipelines now using the template but they arent likely to be contributed back to nf-core. Having this option saves having to manually replace bits everywhere. 

 We have some docs to do this manually on the website [here](https://nf-co.re/docs/contributing/tutorials/unofficial_pipelines) but the idea is to replace most of this with a single command! 🔥 

@robsyme (just sent you an invite to become a member of the community 🚀 ) has offered to help with the implementation.

I will let him fill in the details but some preliminary discussion was initiated on Slack [here](https://nfcore.slack.com/archives/CE5LG7WMB/p1651777699434469) 

The main complication will be how we get downstream tools like the linting, sync etc to play nicely with non-nf-core branded pipelines. We should add tests for this via Github Actions.

**Comment by Midnighter** [comment]
What was brought up in the discussion as well, is to add a flag when creating the pipeline to avoid the branding. Maybe it is easier to have options in the various jinja templates that avoids creating the files/sections related to branding.

**Comment by drpatelh** [comment]
We should collect a list of any filenames, variables, comments, images that are using "nf-core" / "Nfcore" and ideally replace as much as we can either with `--prefix` or something more generic to save having to use Jinja templating, renaming files etc.

**Comment by Midnighter** [comment]
> or something more generic

Naming them for their purpose irrespective of nf-core gets my vote 👍🏼 

> What kind of stuff do you guys consider branding?

Good question 🙂 

Things I thought of:

1. Printed banner/logo when running the pipeline
2. Project/pipeline being named `nf-core-*`
3. Apple in the logo

I think it would be fair to add a footer in the README that says, "generated with the nf-core tools template" or a similar message on non-branded projects. This is quite common, provides some attribution, but doesn't cause confusion on whether a project is nf-core or not.

**Comment by ErikDanielsson** [comment]
Closing due to merge of #1551.
