### ISSUE TITLE
Docker Cloud Migration

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#155]
We need to get all our repositories set up at Docker Cloud instead of Docker hub. 
Reason is, for repositories that were e.g. renamed (RNAseq -> rnaseq), the automated builds break.

It is impossible to add a new source repository on Docker Hub, but on Docker Cloud you can. Both are interfaces for the same backend - so we don't loose anything but gain something. I only have to set up the tags/branch builds for all repositories again once. 

- [x] rnaseq
- [x] hlatyping
- [x] methylseq
- [x] eager
- [x] chipseq
- [x] exoseq
- [x] mag
- [x] vipr
- [x] smrnaseq

....

**Comment by apeltzer** [comment]
I turned off Docker Hub and we now use Docker Cloud for everything. Benefits are easier handling of tags, easier changing of source directories if that ever becomes again an issue and overall better performance in my opinion! 

Every repository + MAG (which didn't have a dockerhub integration yet) has now properly set up build triggers for `master` , `dev` and `tag`

**Comment by ewels** [comment]
Great stuff, thanks for the super speedy response @apeltzer!
