### ISSUE TITLE
Lint warning when using a template

### ISSUE THREAD

**Issue by Midnighter** [nf-core/tools#1558]
### Description of the bug

When using a template instead of a script block inside of a process, I get the following lint warning:

```
Process name not used for versions.yml
```

which seems like a parsing bug of the linter.

### Command used and terminal output

```console
nf-core modules lint sratools/prefetch  # On currently open PR.
```

### System information

nf-core, version 2.4.dev0

**Comment by Midnighter** [comment]
See https://github.com/nf-core/modules/pull/1631 and the failing lint action.

**Comment by Midnighter** [comment]
Actually no, different lint warning.

**Comment by ewels** [comment]
ok I should stop working and go and eat. Just realised that your comment immediately after opening the issue was exactly that 👍🏻

**Comment by ewels** [comment]
...except [the PR](https://github.com/nf-core/modules/pull/1631) and [failing lint action](https://github.com/nf-core/modules/runs/6368191141?check_suite_focus=true) has the error from the other issue which I thought that you'd duplicated:

```
╭──────────────────────────────────────────────────────────────────────────────╮
│ [!] 1 Test Failed                                                            │
╰──────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────┬─────────────────┬─────────────────╮
│ Module name                              │ File path       │ Test message    │
├──────────────────────────────────────────┼─────────────────┼─────────────────┤
│ sratools/prefetch                        │ modules/sratoo… │ when: condition │
│                                          │                 │ has too many    │
│                                          │                 │ lines           │
╰──────────────────────────────────────────┴─────────────────┴─────────────────╯
```

I guess the force-push in that PR dropped reference to the original CI tests where this was happening.

Could you link to a reproducible example please? 🙏🏻

**Comment by mirpedrol** [comment]
It seems that when using a template the linting checks for the script section (which is empty in that case) are also performed, thus the error. 
Should we only perform the checks when there is a script section?
We could also include a template section to perform the linting, but I guess it will be varying a lot between different templates, won't it?

**Comment by ewels** [comment]
> We could also include a template section to perform the linting, but I guess it will be varying a lot between different templates, won't it?

Yeah I wondered the same but I'm not sure that we can do much with this. I did wonder about checking for the version etc. but it would be fairly complex code and probably quite liable to break. There aren't loads of modules taking this approach so I'm not in a rush to do this for now.
