### ISSUE TITLE
[BUG] Regex behaviour and comment in code do not agree

### ISSUE THREAD

**Issue by fabianegli** [nf-core/tools#1595]
### Description of the bug

See

https://github.com/nf-core/tools/blob/171127bd850040e76febd0945e6980b7afcaad69/nf_core/modules/lint/main_nf.py#L242-L244

The regex as it is in the code extracts `v1.2.0_cv1.img` instead of `v1.2.0_cv1` from `https://containers.biocontainers.pro/s3/SingImgsRepo/biocontainers/v1.2.0_cv1/biocontainers_v1.2.0_cv1.img' :`

See the [original](https://regex101.com/r/Zz1I05/1) and [fixed](https://regex101.com/r/Zz1I05/2) regex.

**Comment by ErikDanielsson** [comment]
Closing due to merge of #1598.
