### ISSUE TITLE
Update conda channel order priorities

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#160]
`conda-forge` should now have highest priority, see https://github.com/bioconda/bioconda-recipes/pull/10924#issuecomment-421463832

**Comment by MaxUlysse** [comment]
If `conda-forge` gets the highest priority, could this means that we can get rid of the `openjdk` requirement for `FastQC`?

**Comment by apeltzer** [comment]
Yes, its a change required by upstream conda-forge/bioconda changes.

**Comment by ewels** [comment]
Yes, exactly 👍 

But better to do it in the template and then sync that out to all pipelines if possible..

**Comment by drpatelh** [comment]
Thanks. Shall I create a pull request? Im not sure if Travis is going to be my friend...so I may need to someone else to do my homework!

**Comment by apeltzer** [comment]
Send a PR for that

**Comment by drpatelh** [comment]
Just saw it! No probs.
