### ISSUE TITLE
make CONTRIBUTING.md file more visible and mention/link to it in the README.md

### ISSUE THREAD

**Issue by fabianegli** [nf-core/tools#1608]
### Description of feature

The developer documentation is currently hidden away in the .github folder. This way it is not immediately clear it exists from looking at the GitHub landing page.

See also: https://github.com/nf-core/tools/pull/1538#issuecomment-1136973933

**Comment by ewels** [comment]
If you fancy just moving it into the root, that'd be fab. Been meaning to do this for ages.
