### ISSUE TITLE
Branch tests failing when creating a PR from dev -> master

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1609]
### Description of the bug

See conversation here: https://nfcore.slack.com/archives/CE5LG7WMB/p1653387517434859

The tests shouldn't be failing when merging to `master` from `dev`. I tried removing and adding quotes as in [this commit](https://github.com/nf-core/rnaseq/pull/832/commits/325fdd619f20a765a9b36fdd106144d7302bbc56) but that didn't help either.

**Comment by mirpedrol** [comment]
If I understood well from the Slack conversation, this was magically fixed :) Can I close the issue?
