### ISSUE TITLE
Include statement for installed module ends on wrong `

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/tools#1640]
### Description of the bug

The include statement ends on the wrong quote type , should be `'` instead

### Command used and terminal output

```console
nf-core modules install mosdepth

 Include statement: include { MOSDEPTH } from '../modules/nf-core/modules/mosdepth/main’
```

### System information

tools version 2.4.1
macos

**Comment by PritamSarbajna** [comment]
can someone assign me this issue ?

**Comment by ewels** [comment]
> can someone assign me this issue ?

Done! You're welcome to assign yourself to issues if you're intending to work on them :)

**Comment by PritamSarbajna** [comment]
> ```
> mosdepth
> ```
can you please give me a little hint that where to find it ?
@FriederikeHanssen

**Comment by PritamSarbajna** [comment]
hey @ewels 
I think this issue is actually on [nf-core/modules](https://github.com/nf-core/modules)

**Comment by ewels** [comment]
No, it's here: https://github.com/nf-core/tools/blob/f8de281e6dd039f8a00cfa69f52ba2ff19099e49/nf_core/modules/install.py#L135

The final character `’` should be a `'`

**Comment by ewels** [comment]
Normally yes, but as this is such a small edit I don't think that there's any need 👍🏻  Please do a fork and then make a pull-request though.

If you like you could also make the statement coloured:

```python
 log.info(f"Include statement: [magenta]include {{ {module_name} }} from '.{os.path.join(*install_folder, module)}/main'")
```

The logging uses the python Rich library, which is where the `[magenta]` thing is used: https://rich.readthedocs.io/en/stable/markup.html
