### ISSUE TITLE
Schema: Lint for mimetype

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#1647]
Check that `params.input` has a `mimetype` set and trigger warning if missing.

[Example](https://github.com/nf-core/tools/blob/171127bd850040e76febd0945e6980b7afcaad69/nf_core/pipeline-template/nextflow_schema.json#L18): `"mimetype": "text/csv",`

Would be nice to link to a list of commonly used mimetypes in the docstring docs for lint tests.

**Comment by ErikDanielsson** [comment]
Closing due to merge of #1676.
