### ISSUE TITLE
Lint for singularity image parsing

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#1654]
When running `nf-core download` you can sometimes get the following error log message:

```
ERROR    Cannot parse container string, skipping: ${            download.py:485
         workflow.containerEngine ==   
```

On the plus side, it doesn't fail. But the error message isn't super useful (would be good to log which file it came from).

More importantly, we should add a lint test to check pipelines that all container strings can be parsed, to avoid this happening in the first place.

**Comment by ErikDanielsson** [comment]
Closing due to merge of #1683
