### ISSUE TITLE
"modules create" mismatching containers 

### ISSUE THREAD

**Issue by rpetit3** [nf-core/tools#1656]
### Description of the bug

When using `modules create` I'm finding the build numbers are different for the Docker and Singularity containers. In the example below, the Singularity container is the most recent one and the one that should be used.

### Command used and terminal output

```console
$ nf-core modules create genotyphi

INFO     Using Bioconda package: 'bioconda::genotyphi=1.9.1'                                                                                                                                                                                   
INFO     Using Docker container: 'quay.io/biocontainers/genotyphi:1.9.1--hdfd78af_0'                                                                                                                                                           
INFO     Using Singularity container: 'https://depot.galaxyproject.org/singularity/genotyphi:1.9.1--hdfd78af_1'
```

### System information

GCP VM with Debian 12 server using the dev branch of nf-core/tools

**Comment by ErikDanielsson** [comment]
`nf-core modules create` uses the Biocontainer API to pull the latest Singularity and Docker tags. I looked in the Biocontainer registry for `genotyphi`, and it seems that the most recent update to `genotyphi` only updated the Singularity image, which explains the mismatch. Hence, it is difficult to correct this on the `nf-core/tools` side of things.

**Comment by mirpedrol** [comment]
One option would be to use the last version available in both systems, even if it's not the latest possible version. I think it's better for consistency. Would you agree with that?
