### ISSUE TITLE
[Custom Template] Collection of open points

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#1677]
### Description of feature

Hi - especially @ErikDanielsson  who worked on this

I've given nf-core@dev another try and found most of the template stuff now nicely configurable. What is currently still created is the Github stuff, which could also be something to ditch (on a configurable basis). 

`.github/ISSUE_TEMPLATE` is only useful if one really hosts on Github

**Comment by apeltzer** [comment]
Another thing, when linting, it complains about some files not being there (which are typically not really required if you're not intending to have them in nf-core):

![image](https://user-images.githubusercontent.com/2359510/179237902-b595124c-9874-4aa5-9693-4b292215f2eb.png)

**Comment by ErikDanielsson** [comment]
Then we should add an option to skip GitHub stuff altogether, which should be rather straightforward to do. 

Regarding linting issue: Fixing this would require us to add all these files to the `file_exists` section of the `.nf-core.yaml`. Do you think it would be best to add this by default, or would it be better to be able to configure it (perhaps with the option for skipping all GitHub stuff)?

**Comment by apeltzer** [comment]
I think the latter would be best
