### ISSUE TITLE
Add some info on the gitHub-authorization required by the nf-core tool

### ISSUE THREAD

**Issue by asp8200** [nf-core/tools#1699]
### Description of feature

When running `nf-core modules update -a` in Sarek, I kept getting the message
```
...
│    88 │   │   raise LookupError(                                                                                                                                                                     │
│ ❱  89 │   │   │   f"Unable to fetch commit SHA for module {module_name}. API responded with                                                                                                          │
│       '{response.status_code}'"                                                                                                                                                                      │
│    90 │   │   )                                                                                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
LookupError: Unable to fetch commit SHA for module gatk4/gatherbqsrreports. API responded with '403'
```

The error message wasn't very clear about what the problem was, so I modified my local copy of `nf-core` to print the `response.text`, and I got the much more informative message:
```
{"message":"API rate limit exceeded for 130.225.14.73. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```
Looking further into the source-code for `nf-core`, I could see that it, amongst other authentication options for GitHub, `nf-core` was looking for `GITHUB_TOKEN`, so I set my `GITHUB_TOKEN` and everything worked.

Suggestions:

1) Add a section in the `README.md` describing how to the user should setup GitHub authentication for `nf-core`,

2) Have `nf-core` supply a more informative error message in case the GitHub authentication fails. (Perhaps just print out `response.text`?)

**Comment by ewels** [comment]
Thanks for reporting this @asp8200! The GitHub API rate limiting has been a hassle the past few months and was unexpected as module usage grew.

We can definitely look into improving the error and docs, but I'm hoping that it mostly won't be needed. We have rewritten all of the module code to now use a local cache of the modules repo so the number of GitHub API requests should now be close to zero. So I'm hoping that we will no longer run into these kinds of problems.

Despite this, I agree that having at least a brief mention in the docs would be good (the easiest method is to use the GitHub CLI and do `gh auth`, `nf-core` can then use those credentials).

Printing the full response text (in the debug log as a minimum) is also a good idea. However I suspect that most of the places for this have been removed now, but we could check what GitHub API calls remain.

**Comment by ewels** [comment]
We no longer use the API for this, instead a local clone of the modules repo. So should be resolved now.
