### ISSUE TITLE
Write tests for linting of patch files in `nf-core modules lint`

### ISSUE THREAD

**Issue by ErikDanielsson** [nf-core/tools#1731]
### Description of feature

Tthe recently implemented modules lint tests for patch files have very low coverage. I'd suggest we do it in a similar fashion to how the the `patch` and `updates` commands are tested with patch files, i.e. using the [`patch-tester`](https://gitlab.com/nf-core/modules-test/-/tree/patch-tester) branch in the `nf-core/modules-test` repo on GitLab.

**Comment by mirpedrol** [comment]
If I'm not wrong, this was done by @mashehu #1761. I will close the issue.
