### ISSUE TITLE
Should we keep the `--base-path` option?

### ISSUE THREAD

**Issue by ErikDanielsson** [nf-core/tools#1732]
### Description of feature

The `--base-path` option in the `nf-core modules` command was added without considering all the cases it could be used. For example, in the current implementation we don't support different base paths in different branches, which can be a bit confusing (#1726). To support different base paths for different branches we would have do something along the lines of #1728, but I'm not sure if it is worth the effort if we don't know to what extent it would be used. Therefore I would say we remove it altogether before the 2.5 release.

**Comment by ewels** [comment]
x-ref https://github.com/nf-core/tools/pull/1655

**Comment by ewels** [comment]
Let's remove it. It doesn't add much value, we don't know if anyone really needs it and it adds a lot of complexity.

It'll be a little messy to remove as it's mentioned in a lot of places, but some judicious use of project-find plus deleting stuff should hopefully get it done. Just need to try not to break anything else by accident 😬

**Comment by ewels** [comment]
Nice!
