### ISSUE TITLE
The rich codex screen grab updater is interfering with the development workflow

### ISSUE THREAD

**Issue by fabianegli** [nf-core/tools#1775]
### Description of feature

The new cool workflow updating all PRs with the newest screen grabs is nice, but it comes with some side effects. Every time a commit is pushed to a PR there is a new PR by the bot. This then means that new push might fail and the whole PR has to be rebased or merged. Tis pollutes the commit history and complicates the development workflow. It would be nice to have this workflow as something that can be done "on demand" or just before merging, not with every commit pushed to the PR branch.

**Comment by mashehu** [comment]
This problem will hopefully go away, when we fine tune the tolerance for changes before it pushes them. Working on it.

**Comment by fabianegli** [comment]
I would prefer a different solution that has the following properties:

- Deterministic screen grabs. This is important to have screen grabs consistent with the code base.
- Screen grabs are generated upon demand and PR merge. This way the changes can be introduced immediately, or 

We have a bunch of pre-commit hooks and this might be one to add. But this will be most useful only if the screen grabs are always up to date with the code - no tolerance.

**Comment by ewels** [comment]
Suggestions:

- Limit to commits with a specific text in them such as `[screenshots]`
- An @nf-core-bot render screenshots comment, like we have for fixing formatting
- A manual launch button in actions using [`workflow_dispatch`](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)
- Run on merge to `dev` and disable branch protection for the GitHub Actions bot

Not mutually exclusive, so could do any / all of these..

**Comment by ewels** [comment]
Ok discussing this now. To start with:

- Remove run on push
- Add run on PR approval (#1778)
- Remove minimum % changes, so that we pick up version number changes
- [Later] Add a regular expression to ignore changes within tables for `nf-core list` and more, to reduce re-runs (see [docs](https://ewels.github.io/rich-codex/config/ignoring_changes/#regular-expression-matches))

**Comment by ewels** [comment]
> Add run on PR approval

Ok this was more difficult than expected. When running on push, the action runs on the fork and is simply running on the checked out branch. By moving to the PR approval, the action then runs on the head fork on the pseudo-merged PR code. It runs fine but it can't push those changes to the fork's branch.

It should be possible to do this still by being a bit clever with what exactly is being checked out, but it probably needs some thought / testing. For now will cut out all the automated stuff and just do it on `workflow_dispatch`, then come back to this after the release.

**Comment by ewels** [comment]
I think that we can close this now. Having it only run on `workflow_dispatch` is good I think, then we manually do it before release. It's added to the [release checklist](https://github.com/nf-core/tools/blob/master/.github/RELEASE_CHECKLIST.md). I don't think that we can improve on this for now.
