### ISSUE TITLE
Better explanation for interactive pipeline creation

### ISSUE THREAD

**Issue by Midnighter** [nf-core/tools#1808]
When calling `nf-core create`, there is an option to customize what parts of the template to use. The first few times I was confused about what toggle would mean something is included or excluded.

`●` means skipped
`○` means included

This could be part of the description.

**Comment by lukbut** [comment]
@Midnighter I tried to isolate where this happens in the code with little success - any pointers, please?

**Comment by mirpedrol** [comment]
Closing this as it will be outdated by https://github.com/nf-core/tools/pull/2404
