### ISSUE TITLE
Increase the code coverage

### ISSUE THREAD

**Issue by sven1103** [nf-core/tools#181]
* [x] Raise the code coverage up to more than 90% again. #186 
* [ ] Check for misleading error messages and make them more human-readable (i.e. #180 )

**Comment by ewels** [comment]
Are there any specific misleading error messages @sven1103? I think that I fixed the one you linked to in #224, were there any others?

**Comment by sven1103** [comment]
Not that I am aware of. I think we are good to close it for now, and open more descriptive issues in case another misleading error message occurs.
