### ISSUE TITLE
"since" has no effect

### ISSUE THREAD

**Issue by fabianegli** [nf-core/tools#1817]
Can the argument and its documentation be removed? Or does the code need to be adapted to fulfill the docs?

https://github.com/nf-core/tools/blob/bc56cdd35077e408a0a7c90ec07fcdff7c2d1f3b/nf_core/modules/modules_repo.py#L348-L368

**Comment by fabianegli** [comment]
@ErikDanielsson Do you have preferences how to solve this issue?

**Comment by fabianegli** [comment]
I went ahead and cleaned the function signature and docstring according to the function body.

**Comment by mashehu** [comment]
I think it is fine to remove it. If we see a need for this functionality we can add it. I didn't find any more mention of this functionality except for `modules_repo.py`. Thanks for finding this!
