### ISSUE TITLE
Spring clean nf-core

### ISSUE THREAD

**Issue by christopher-hakkaart** [nf-core/tools#1832]
### Description of feature

**Spring clean of nf-core**

Repos are full and issues pile up and often become outdated. It would be good to establish a yearly clean where everyone, not just core members, remove/archive stale pipelines, issues, branches, and pull requests.

We will aim for March each year (prior to hackathon) so issues can be transferred to tickets for the hackathon if they are appropriate. 

- [ ] Set up reminders on Slack
- [ ] Contact listed lead developers
- [ ] Contact other ways?

**Comment by mirpedrol** [comment]
I think that's done! 🥳 
Can I close it as part of the 1st spring cleaning? Or you still want to revisit this TODO list here?
