### ISSUE TITLE
Make `nf-core lint` and `nf-core schema lint` usage consistent

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#1838]
### Description of feature

One requires a positional argument (schema), the other doesn't. This is confusing to people, so I'll make a fix to make this consistent.

**Comment by sersorrel** [comment]
There are now three (I think?) lint commands: `lint`, `schema lint`, and `modules lint`.

- `lint`: no positional arguments
- `schema lint`: one required positional argument
- `modules lint`: one optional positional argument

As I understand it, the argument to `schema lint` will very often be `nextflow_schema.json`, so using that as a default (and thus making the argument optional) would seem sensible to me. Then all three lint commands can be invoked with no arguments.

@apeltzer, assuming you're not actively working on this, is it ok if I submit a PR for the above as part of the ongoing hackathon?
