### ISSUE TITLE
`nf-core schema build` changes default value from `null` to `"None"`

### ISSUE THREAD

**Issue by Midnighter** [nf-core/tools#1841]
### Description of the bug

Title mostly says it. I have a defined schema with a parameter that has `"default": null`. When I run `nf-core schema build` this default gets replaced with `"None"` which looks like it comes from Python.

My `nextflow.config` has the following entry which probably confuses the logic in the nf-core tool leading to the above result.

```nextflow
params {
    notify_slack = true
    slack_hook_info = params.notify_slack ? "$SLACK_HOOK_INFO" : null
}
```

The environment variable `SLACK_HOOK_INFO` is not defined when I run this.

### Command used and terminal output

```console
nf-core schema build
```

### System information

* Linux 5.17.5-76051705-generic
* nf-core, version 2.5.1
* Python 3.9.5

**Comment by KarNair** [comment]
@Midnighter Do you still face this issue on nf-core v2.7? I tried putting your configuration snippet in my config and I am unable to reproduce this issue.

**Comment by mirpedrol** [comment]
Hello, default values evaluating to false (such as null or empty strings) should not be added to the JSON schema. 
The command `nf-core schema build` [will now remove](https://github.com/nf-core/website/pull/1919) this default values automatically. This does not affect the validation of parameters, you can see the latest docs of the [nf-validation plugin](https://nextflow-io.github.io/nf-validation/nextflow_schema/nextflow_schema_specification/#default).
In case you already have default values of `null` which were converted to `None` you can remove them by hand.
