### ISSUE TITLE
Bump Version issues

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#185]
I tried bumping the nf-core/eager release 2.0.0 and got this message:

```
alex@aragorn ~/I/n/eager> nf-core bump-version . 2.0.0                                                                            (nf-core) 

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'
    

INFO: Running nf-core lint tests
Running pipeline tests  [####################################]  100%  None                              

INFO: ===========
 LINTING RESULTS
=================
 100 tests passed   0 tests had warnings   0 tests failed

ERROR: Could not find config variable workflow.manifest.version
alex@aragorn ~/I/n/eager>                                                                                                         (nf-core) 
```

its the current `dev` branch, so should be fine I suppose?

**Comment by drpatelh** [comment]
Stupid question but are you using NF >= 32.0?

**Comment by apeltzer** [comment]
There are no stupid questions - yes, I am!

**Comment by apeltzer** [comment]
Its a bit weird though, since linting passes 100 tests and everything else behaves perfectly fine but once I want to bump the version string to something for a release, it complains about that missing `version` thing.

**Comment by drpatelh** [comment]
So could it be something localised to the bump_version.py script? Anything related to this recent PR? https://github.com/nf-core/tools/pull/172

**Comment by ewels** [comment]
Already fixed 11 days ago 😉 

https://github.com/nf-core/tools/pull/172

**Comment by apeltzer** [comment]
Ok, I see that Ive been using the bioconda package instead of native installation. Should actually use the newer version ;-)
