### ISSUE TITLE
Add functionality to remove patches

### ISSUE THREAD

**Issue by jfy133** [nf-core/tools#1920]
### Description of feature

Currently `tools` cleverly detects changes to module code within a pipeline, and generates a `diff` file for you.

However in some cases you may wish to remove a patch (if you move the change to pipeline code instead).

It would be nice to be able to have a flag to remove a patch e.g. `nf-core module patch --remove <module>`, so a user does not need  manually delete the `.diff`, and more importantly not have to modify `modules.json` :grimacing: .

**Comment by awgymer** [comment]
There are two methods we could use to do this:
    
    - Delete the diff and reinstall/update the module
    - Apply the diff in reverse and then remove the diff

I am not sure if there is a preference for one or the other? I *think* that an `update` is safer and cleaner but I am not sure.

**Comment by jfy133** [comment]
The risk with the update method is that that could install a later version of teh module that may have even more drastic changes and break things...

**Comment by awgymer** [comment]
I agree with @ewels *but* there is already some code that seemingly [applies a patch in reverse ](https://github.com/nf-core/tools/blob/f3b5d1e2c7d1a5d4959535947c73954070d4ba18/nf_core/modules/modules_json.py#L772) which exists for the purpose of determining the correct `sha`. 

Ironically we seem to see the `modules.json` as the source of truth but never actually trust it in the code 😅

**Comment by awgymer** [comment]
Ok I have created a draft PR using the method of reversing the patch based on exisiting code. Should be a reasonable starting point for either method though.

**Comment by jfy133** [comment]
Completely forgot to come back to this close this and say thanks @awgymer, so I do it now!
