### ISSUE TITLE
Main instead of master for branch name when generating a new pipeline?

### ISSUE THREAD

**Issue by lucacozzuto** [nf-core/tools#1931]
### Is your feature request related to a problem? Please describe

I'm setting up a new local pipeline and I got three branches. I think the master one should be replaced by main...

**Comment by Emiller88** [comment]
I believe @ewels and others were opposed as it would break a lot of things. 
See https://nfcore.slack.com/archives/C0448VBG30R/p1664972715894999

**Comment by maxulysse** [comment]
I'd love to see that, but for the moment, `master` is still hardcoded in a lot of places.
It's on our TODO list, definitively, and I'm quite adamant on having that pushed.

**Comment by ewels** [comment]
We will merge in support for using `main` for tools v3 and mention it in the release. But not take any action immediately (the code will support both main and master).

Once the dust has settled we will have a dedicated blog post about the switch, and then start going through all nf-core org repos making the change.

**Comment by mirpedrol** [comment]
Moving this issue to the next milestone until https://github.com/nextflow-io/nextflow/issues/3593 is fixed by Nextflow

**Comment by ewels** [comment]
The above is now resolved and in stable, so shouldn't be a blocker any more.

**Comment by ewels** [comment]
Let's still set `manifest.defaultBranch` to `main` as well. Should make it work in older versions of Nextflow and is the most paranoid approach.

https://www.nextflow.io/docs/latest/reference/config.html#manifest

It's verbose is the only downside, but we're templating. Can remove in a year or once everyone is running > 24.10.0 if we like.
