### ISSUE TITLE
Test GHA self-hosted runners for events

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#1940]
### Description of feature

We should have some way of setting up custom runners for events such as hackathons to speed up CI on such days. 

This is fairly easy, just requires machines with linux + the setup scripts by Github to be started - then we have to figure out whether we have to fix labels in the github actions scripts or have to change that in our labels.

**Comment by apeltzer** [comment]
Basic configuration description (only visible with permissions): 

https://github.com/organizations/nf-core/settings/actions/runners

Then can configure that runner following the instructions there, add a label `ubuntu-20.04` to it to get jobs scheduled on it too. Also need to install `docker` on the machine running the runner as we are using docker to run jobs.

**Comment by apeltzer** [comment]
Ok, documenting all learning on this one:

a.) Need to enable that the jobs can run on public repositories as we all have public in nf-core
b.) Labels of the runner should be set to `ubuntu-latest` to be able to run other jobs without changing labels in GHA yaml files

The EC2 needs some preinstallation to make things work:

a.) Docker installed + usable for the default user, could also run the runner as root to circumvent that (probably not the best idea)
b.) nodejs installed & directories writeable for everyone -- for prettier etc pp
c.) Java JDK > 13 installed for running Nextflow tests

Python installation works out of the box for a Ubuntu AMI, so should not need any configuration.

**Comment by aktech** [comment]
By the way, if you want a no-maintenance method to achieve that, you can use [cirun.io](https://cirun.io) for the same.

**Comment by apeltzer** [comment]
Once we start the runner, need to assign it the same label as we use everywhere `ubuntu-latest`, that way we will have it available

**Comment by Emiller88** [comment]
https://github.com/philips-labs/terraform-aws-github-runner

**Comment by apeltzer** [comment]
Hm, I'm happy to give it a try to some extent - how much effort would this be?

**Comment by apeltzer** [comment]
We'll take a look at cirun fairly soon - hosting for now manually on EC2, as we'd need a special config file.

**Comment by ewels** [comment]
I took a look at cirun a couple of days ago. I don't think it'll work for us:

* Requires each repo to be switched on manually
    * We want the runners to be available to all repos on the org all the time, we add new repos very frequently and don't want to have to go and click buttons each time
* Requires a [config file](https://docs.cirun.io/reference/yaml) in the repo
    * Need to update all repos, plus more dotfile bloat in the repo root
* Not 100% sure on this, but I think it'll mean we can _only_ use EC2 and won't make use of the free GitHub runners we have

In our case, we don't really care where the jobs are running or what hardware they're using - we just want more capacity. I think that having one or two manual EC2 instances running which drain the default Actions job queues is much easier than setting up cirun and actually works better in our use case.

Happy to be corrected on any and all points 😀 (especially as we have the author on the thread! 😅 )

**Comment by apeltzer** [comment]
Closing this in favour of ttps://github.com/nf-core/actions-runners
