### ISSUE TITLE
Update "nf-core list" after using "nf-core download"

### ISSUE THREAD

**Issue by lconde-ucl** [nf-core/tools#1946]
### Description of feature

Question from slack:

Is there a way to use `nf-core download` and have the output of `nf-core list` updated with the pipelines that were downloaded? It seems that `nf-core list` only picks the pipelines downloaded via `nextflow pull`. Is that right?

PS: just moving the "workflow" folder to ~/.nextflow/assets/ does not work as a quick solution, it gives the error "_This git repository looks broken. It's probably a good idea to delete this local copy and pull again_"

Thanks

**Comment by ewels** [comment]
Came across this in the hackathon, it's an old issue so apologies for the delay in responding.

Unfortunately, I don't think that it's possible to do this for a couple of reasons:

* We don't have a single location where pipelines are downloaded to, where we can check
* `nf-core download` gets a flat copy of the pipeline, so it's not easy to get the git checksum of what was downloaded
* `nf-core download` is designed for moving pipeline code off the host system, so it doesn't really make sense to tie it into `nf-core list`, which runs on the host system.
