### ISSUE TITLE
Tooling now only works for modules/subwf under `nf-core` 

### ISSUE THREAD

**Issue by awgymer** [nf-core/tools#1947]
### Description of the bug

Previously tooling supported modules installed from remote repos other than the `nf-core/modules` Github. 
Other remote repos still work but only if `nf-core` is kept as part of the module/subwf path structure.

This effectively means the only current use of alternative repo functionality is to have a private mirror of nf-core.

The cause is the hard-coding of `nf-core` as part of the modules/subwf paths. 

Possible solutions:
 - Anyone using an alternative remote (for whatever reason) needs to put their own modules under the `nf-core` path
 - Introduce an `org` option which defaults to `nf-core` and is used to control the folder structure in the tooling.  

### System information

Tools version 2.7

**Comment by awgymer** [comment]
I wonder if we can infer the "org" as it were from the path? 
It should always be `/modules/<org>/<<tool>/<subtool>>/main.nf`?

**Comment by mashehu** [comment]
fixed in #2056 🎉
