### ISSUE TITLE
Container Base Url support when creating new modules

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#1948]
### Description of feature

https://github.com/nf-core/modules/pull/2291 outlines how we will restructure to use `params.container_registry` for docker containers in the future, e.g. to allow using container mirrors from ECR or potentially other sources. 

This means however, that we will have to adjust tools code to query the biocontainers API and split the URL 
 to use the `params.container_registry` placeholder. Otherwise users might create new modules using nf-core tooling and have full URLs to quay.io in their newly created module code, which is a bit inconvient. Potentially could also _lint_ for this.

x-ref: https://github.com/nf-core/modules/pull/2291#issuecomment-1277434691

**Comment by ewels** [comment]
Now using docker registry setting, so this can be closed.
