### ISSUE TITLE
default value is out of synch between the `nextflow.config` and `nextflow_schema.json`

### ISSUE THREAD

**Issue by jenmuell** [nf-core/tools#1954]
### Description of the bug

During the hackathon I was working on an issue for the parameter schema and was checking which parameters I can change in the graphical interface. Thereby I changed the default value of a parameter and recognized that the corresponding parameter in the `nextflow.config` was not updated. 
Connected to [Issue](https://github.com/nf-core/nf-co.re/issues/1045) and [PR](https://github.com/nf-core/tools/pull/1926)

A possible solution would be to highlight this behaviour with a tooltip, to inform the user that he has to update the `nextflow.config` file or to disable a change of the default value.

**Comment by ewels** [comment]
Would be good to lint for this, but allow for the `.nf-core.yml` file to ignore specific parameters where this may be desired (eg. complex deferred param defaults in the config and a simple string in JSON).

**Comment by mirpedrol** [comment]
Added the linting test with #2684
