### ISSUE TITLE
nf-core modules create-test-yml does not check existence of versions.yml

### ISSUE THREAD

**Issue by LaurenceKuhl** [nf-core/tools#1958]
### Description of the bug

Hi there,

when creating a new module `nf-core modules create-test-yml -t` creates a `test.yml` file checking the existence of the input/output files and their checksums. The existence/checksum of the version.yml file of the output channels is missing.

### Command used and terminal output

```console
nf-core modules create-test-yml -t mageck/count 
less tests/modules/nf-core/mageck/count/test.yml
```

### System information

N E X T F L O W  version 22.07.1-edge build 5726
nf-core/tools version 2.6

**Comment by mashehu** [comment]
Fixed in #1963
