### ISSUE TITLE
Travis fails build w/ Nextflow v18.11.0-edge

### ISSUE THREAD

**Issue by PhilPalmer** [nf-core/tools#196]
**EDIT: Not sure how necessary this is as the `18.11.0-edge` is not a stable release and older versions of Nextflow are fine for the pipeline I was working on**

Problems are because up until now Nextflow versions have always consisted of numbers and full stops. 

## Issue 1: nf-core bump-version regex
When using `nf-core bump-version . 18.11.0-edge --nextflow` a regex is used to select the version and so the `-edge` is dropped. This can be seen in the [Travis test](https://travis-ci.com/nf-core/deepvariant/jobs/158240899) which fails because Nextflow cannot be installed:
![image](https://user-images.githubusercontent.com/32334279/48434877-e8a1b580-e772-11e8-85ac-28a2b07638c9.png)

## Issue 2: 'manifest.nextflowVersion' must start with '>='
After correcting the nextflow version `nf-core lint` fails. As shown by this [travis test](https://travis-ci.com/nf-core/deepvariant/jobs/158268212):
![image](https://user-images.githubusercontent.com/32334279/48435198-cfe5cf80-e773-11e8-8354-94efe955eeb8.png)
This is despite the Nextflow versions being the same in the pipeline manifest and the `.travis.yml`. I think this is caused by this line in `nextflow.config` `nextflowVersion = '>=18.11.0-edge'` however if I remove the `>` I then get this error:
```
ERROR: Test Failures:
  http://nf-co.re/errors#4: Config variable 'manifest.nextflowVersion' did not start with '>=' : ''=18.11.0-edge
```

**Comment by apeltzer** [comment]
@aunderwo fixed this at some point, so closing this 👍
