### ISSUE TITLE
nf-core launch --params-in error

### ISSUE THREAD

**Issue by mattheatley** [nf-core/tools#1969]
### Description of the bug

nf-core launch with --params-in /path/to/nf-params.json results in "Parameter output file already exists! nf-params.json". is this an error? my understanding is that it should use this file and not try to create a new one

### Command used and terminal output

nf-core launch slamseq --params-in /Users/mbzmch/Desktop/x.NEXTFLOW/WRK/nf-params.json 

WARNING  Parameter output file already exists! nf-params.json                                                                         launch.py:123
Do you want to overwrite this file? [y/n]: n
INFO     Exiting. Use --params-out to specify a custom filename.

**Comment by mashehu** [comment]
Should be fixed now with #1986. Thanks for reporting this bug!
