### ISSUE TITLE
Module linting broken for non-nf-core modules repository after 2.6 upgrade

### ISSUE THREAD

**Issue by kcibul** [nf-core/tools#2011]
### Description of the bug

We have a functioning custom modules repository and we are able to list/install/update modules from it into our pipelines.

However when trying to lint these modules (from within a git clone of the modules repository) with

``

I get this error

`CRITICAL No modules in 'modules' directory                                                                                                 __main__.py:726`

### Command used and terminal output

```console
nf-core modules lint --all
```

### System information

nf-core 2.6

**Comment by ewels** [comment]
This is probably fixed already in #2056 - could you please try with `v2.7dev`?

**Comment by ewels** [comment]
Closing for now, can reopen if it turns out to still be a problem.
