### ISSUE TITLE
schema build replace null value by None

### ISSUE THREAD

**Issue by maxulysse** [nf-core/tools#2030]
`null` value are replaced by `None`, which is trouble on tower.
cf https://github.com/nf-core/sarek/pull/851

**Comment by maxulysse** [comment]
cc @drpatelh @asp8200

**Comment by ewels** [comment]
Sounds like a problem with `null` and `None` in python / JS conversion.. 😰

**Comment by ewels** [comment]
Need to figure out exactly _when_ this happens - at which step in the JSON schema builder the `None` is introduced.
