### ISSUE TITLE
Restore remote options to <modules/subworkflows> remove command

### ISSUE THREAD

**Issue by awgymer** [nf-core/tools#2041]
### Description of the bug

Recent updates to <modules/subworkflows> remove got rid of the remote options for the command. 
This has caused it to be impossible to remove non-nf-core components via the command. 

### Command used and terminal output

```console
nf-core modules --git-remote <my-git-url> remove

Pulling from 'nf-core/modules' (https://github.com/nf-core/modules.git)
CRITICAL Nothing installed from nf-core/modules in pipeline
```

**Comment by mashehu** [comment]
fixed in #2042
