### ISSUE TITLE
`ubuntu-latest` will soon point to the next major Ubuntu version

### ISSUE THREAD

**Issue by fabianegli** [nf-core/tools#2044]
### Description of feature

`ubuntu-latest` is currently pointing to Ubuntu 20.04 but will very soon point to 22.04. See: https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/

If it is deemed necessary to support Ubuntu-20.04 we might want to parametrize the runs-on in the near future:
`runs-on: [ubuntu-20.04, ubuntu-latest]` or `runs-on: [ubuntu-20.04, ubuntu-22.04]`

Found the blog post while looking into #2043.

**Comment by Aratz** [comment]
Good point!

I think it is really important that we test both versions, although I'm also thinking testing the whole matrix Python versions X Ubuntu versions might be a bit too heavy.

If that's possible maybe it would be preferable to only test `[python-3.7, python-3.11] X [ubuntu-20.04, ubuntu-22.04]` on dev and pull requests, and only test the full matrix when making a new release? Not sure if it is possible to implement this behavior in a nice way in GitHub workflows :thinking:

**Comment by maxulysse** [comment]
I think the only way to do so is to have a separate yml for release than the one for the regular tests

**Comment by fabianegli** [comment]
I mean, one could use `if`s in the workflow yamls to skip undesired tests, but it might be more desirable to have a separate yaml for release and dev. See https://docs.github.com/en/actions/learn-github-actions/expressionsa, https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution and https://docs.github.com/en/actions/learn-github-actions/contexts#matrix-context.

**Comment by fabianegli** [comment]
Or even specify a matrix in json format and load that: https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson
