### ISSUE TITLE
Prettier fails linting for default modules.json

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#2047]
### Description of the bug

The `modules.json` was created using `nf-core modules` and `nf-core subworkflows` commands using the latest code on `dev`. However, linting fails with Prettier which wants to put the `installed_by` section on a single line. We should either ignore this file or fix the default output from tools.

```diff
                    "ataqv/ataqv": {
                         "branch": "master",
                         "git_sha": "56421e1a812bc2f9e77dbe9f297e9d9c580cb8a5",
-                        "installed_by": [
-                            "modules"
-                        ]
+                        "installed_by": ["modules"]
                     },
```

**Comment by fabianegli** [comment]
I think we are moving to run Prettier automatically after any command modifying Prettier formatted files. Once we get this we can also remove some hacks from the code to comply with formatting that are applied to some file dumping functions.

**Comment by fabianegli** [comment]
In this respect it would be nice to get the actual invocations that mess up the files to start figuring out all the places we need to invoke Prettier.

**Comment by ewels** [comment]
Prettier PR now merged, so just a case of using that function on this file after modification.
