### ISSUE TITLE
Linting fails if a module `bin/` contains R code

### ISSUE THREAD

**Issue by fabianegli** [nf-core/tools#2051]
R code does not necessarily comply with the defaults set in the `[*]` section of the `.editorconfig` and this leads the linting tests to fail for more "natively" formatted R scripts. e.g. https://github.com/nf-core/spatialtranscriptomics/pull/17

We could either

- use an R specific linter (`lintr`, `formatR`, `styler`)
- don't lint R files at all (use the `--ignore` flag in the `.github/workflows/linting.yml` for invocations of `markdownlint`)
- configure `.editorconfig` to handle R iles (I am not sure this is a reasonable or achievable option)

I think the combination of the first two options would be the most reasonable and they could be implemented sequentially - first, ignore `.R` and related files in `.editorconfig` or at least when running markdownlint in the tests and second use `pre-commit` for formatting these files with any of the hooks available here: https://github.com/lorenzwalthert/precommit

**Comment by awgymer** [comment]
Is it actually `R` code that is the issue there? The `.editorconfig` linting seems to be failing for `.nf` files too (all with 4 space padding issues)?

If it's just a case of padding issues I am not sure why we couldn't set the `.editorconfig` to have something like:
```
[*.R]
indent_size = 2
```

**Comment by fabianegli** [comment]
R has a bunch of idiomatic synthax that is not easily formatted with other tools than dedicated formatters. One issue is hanging indents. e.g. they depend on where the opening parenthesis is and they can be on even or odd positions and this then defines even or odd indents. So just setting indent_size to 2 will not work. And setting it to 1 defies the purpose and we can just completely skip the linting.

**Comment by fasterius** [comment]
Is the indentation case also not something for Nextflow in general, e.g. using whitespace to make the code look nice while regarding indentations (whether the general rule is multiples of 2 or 4), not just R? A simple workaround is of course to just follow multiples of 4 at all times (which is what I did for the PR mentioned above).

**Comment by fabianegli** [comment]
@fasterius code != code and even more so R code != Python code. I do sympathize with the desire to apply a uniform codestyle everywhere, but using an accepted code style for Python for R code is not going to go well for a couple of reasons: 1. R has its own community with its own skewed perception of what nice R code is as we have our perception how nice pyhonic code looks like and 2. RStudio, the most used editor for R code formats code differently by default. I am quite sure there will be a favored R code style at some point, but it's not clear to me which one that will be. Until then I think it would make sense to just pick one styler or ignore R - I personally think the styler and a corresponding pre-commit-hook package would serve the purpose well.

**Comment by awgymer** [comment]
The linting in that PR doesn't look to be the issue now? Did you ignore the files or take some other route?

I would prefer to just ignore style for scripts in `bin` because largely I think it's preferable to encourage meaningful code to be split out into it's own library/package/whatever that can be separately distributed and installed in a container and I think bloating the dependencies of `nf-core/tools` to include multiple linters/formatters for various languages will lead to pain.

**Comment by fasterius** [comment]
I totally agree that allowing different styles for different languages is desirable, I just followed the codestyle for now so that it'd go through the linter - I can revert later if the linter changes. There are some R default coding styles like you said, but the community does not (as far as I can tell) totally agree on which one to follow.

**Comment by ewels** [comment]
I thought that we ignored the `bin` directory? That would generally be my preference..

**Comment by awgymer** [comment]
> I thought that we ignored the `bin` directory? That would generally be my preference..

Current pipeline template `.prettierignore` from `tools:dev`
```
email_template.html
adaptivecard.json
slackreport.json
.nextflow*
work/
data/
results/
.DS_Store
testing/
testing*
*.pyc
```

Current `nf-core/modules` `.prettierignore`:
```
includes/Maven_Pro/

# gitignore
.nextflow*
work/
results/
test_output/
output/
.DS_Store
*.code-workspace
tests/data/
.screenrc
.*.sw?
__pycache__
*.pyo
*.pyc
`

So looks like we don't ignore the `bin` at the moment
