### ISSUE TITLE
nf-core modules lint --all in a pipeline only works for a single remote

### ISSUE THREAD

**Issue by awgymer** [nf-core/tools#2052]
https://github.com/nf-core/tools/blob/1a68dfb42cd1257658d9b2965b742b8a4a697fec/nf_core/modules/lint/__init__.py#L95-L98

This code means that if you have modules installed from non-standard repos (e.g. a mirror in bitbucket/gitlab) that you need to supply the `--git-remote` option. 

Worse, if you have modules installed from multiple sources `--all` only does them all for a single remote. 

This could be solved by not relying on the `--git-remote` option here. We have the `modules.json` as the source of truth for which modules are installed in a pipeline and where they come from, we could easily build a list from that, with the right remote for each module set.

**Comment by awgymer** [comment]
Similar issue arises with linting the version. 

https://github.com/nf-core/tools/blob/1a68dfb42cd1257658d9b2965b742b8a4a697fec/nf_core/modules/lint/module_version.py#L27-L29

Unless the specific remote is supplied you get an error (these are installed from the GitLab mirror):
```
╭─ [✗] 3 Module Tests Failed ──────────────────────────────────────────────────╮
│                                           ╷              ╷                   │
│ Module name                               │ File path    │ Test message      │
│╶──────────────────────────────────────────┼──────────────┼──────────────────╴│
│ custom/dumpsoftwareversions               │ modules.json │ No git_sha entry  │
│                                           │              │ in modules.json   │
│ fastqc                                    │ modules.json │ No git_sha entry  │
│                                           │              │ in modules.json   │
│ multiqc                                   │ modules.json │ No git_sha entry  │
│                                           │              │ in modules.json   │
│                                           ╵              ╵                   │
╰──────────────────────────────────────────────────────────────────────────────╯
```

**Comment by mashehu** [comment]
The problem goes even deeper. For example 

https://github.com/nf-core/tools/blob/dev/nf_core/modules/lint/module_changes.py#L43-L45 

only checks against one `modules_repo`.

**Comment by apeltzer** [comment]
@awgymer on issues that I'm running into myself these days - one step ahead, nice! 🥇
