### ISSUE TITLE
Pin `pip install nf-core` for `.travis.yml`

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#206]
We should probably also fix the version used for running tests in the travis.yml of each pipeline. Maybe have these versions fixed as discused with @sven1103 already...

**Comment by ewels** [comment]
Yes, good idea.

**Comment by ewels** [comment]
Coming back to this - I’m not sure that we want to do this really.. Tests run on PRs, don’t we want new PRs to always run against the most recent lint tests?

**Comment by apeltzer** [comment]
Actually we want that yes - so maybe we shouldn't pin this at all (and simply pip install the latest version!).
