### ISSUE TITLE
Linting issues / regex problem?

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#207]
https://travis-ci.com/nf-core/rrna-ampliseq/jobs/160266618

https://github.com/nf-core/rrna-ampliseq/issues/43

Apparently it doesn't find the conda packages available?

**Comment by apeltzer** [comment]
We're still seeing these, unfortunately... and I don't really know why!

**Comment by namanbiyani** [comment]
Hi i would like to solve this bug . Can you please give some guidelines

**Comment by ewels** [comment]
Hi @namanbiyani,

Sorry that no-one replied. I think it's because it was difficult to give guidelines as no-one knew what was causing the problem 😓 

However, good news! I think I just tracked it down. PR #295 should hopefully solve this problem I think.

Phil
