### ISSUE TITLE
Linting: Check nextflow is installed first

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#208]
I think that currently if you don't have nextflow installed on your system then you get a nasty stack trace error when it gets to that part of the lint tests. Instead, we should do a 'fail-early-and-fast'  check at the start in the same way that we do when we check that the critical files are there. Then we can raise a friendlier error message.

**Comment by likelet** [comment]
👏

**Comment by ewels** [comment]
Fixed and merged.
