### ISSUE TITLE
[create] Remove `--no-git` flag

### ISSUE THREAD

**Issue by fabianegli** [nf-core/tools#2081]
### Description of feature

As discussed in Slack ([this and following posts](https://nfcore.slack.com/archives/CE5LG7WMB/p1669801089332049)) the option to create workflows without using git will be removed if no compelling use cases come to our attention.

Quote from @ewels about how the git-less creation came to be: 

> I think it was requested for people who had already initialised a git repo themselves previously
> But it's generally A Bad Thing, as the fresh repo is needed for automated template synchronisation

Context: https://github.com/nf-core/tools/pull/2074#issuecomment-1331263329

**Comment by awgymer** [comment]
I was just reading through the docs for `nf-core sync` and under the section on [syncing retrospectively](https://nf-co.re/docs/contributing/sync#setting-up-a-pipeline-for-syncing-retrospectively) I noticed the following:

> If your pipeline already has versioned releases (eg. you are not currently on 1.0dev), then specify the version number that you are currently on: 
nf-core create --no-git --version 1.3dev

So I am wondering whether there may be a legitimate edge-case where we need to run `create` without actually initialising any git repo.

**Comment by ewels** [comment]
Yup, but syncing retrospectively is an utterly horrible experience that should be avoided at all costs 😆 It was more uncommon in the early days of nf-core when were first setting up the template sync mechanism, but in recent years I think that almost no-one has needed to do it.

Removing the `--no-git` option is one way of discouraging this. And doing the equivalent manually (eg. copying the files out and over) is not particularly difficult.
