### ISSUE TITLE
Schema, optional inputs that have `null` as default return an error if they contain a pattern

### ISSUE THREAD

**Issue by nvnieuwk** [nf-core/tools#2089]
### Description of the bug

When running `nf-core schema build` I get the error shown below. My `nextflow_schema.json` has a group that looks like this:
```
        "new_group_2": {
            "title": "New Group 2",
            "type": "object",
            "description": "",
            "default": "",
            "properties": {
                "fasta_fai": {
                    "type": "string",
                    "default": null,
                    "pattern": "^.*\\.fai$"
                },
                "dict": {
                    "type": "string",
                    "default": null,
                    "pattern": "^.*\\.dict$"
                }
            }
        }
```

It would be useful if tools wouldn't check the pattern on the default if it is `null` since this is an entirely optional input value. It gets created by the pipeline if the input is `null`. So I can't really change the default

### Command used and terminal output

```console
$ nf-core schema build

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.7.dev0 - https://nf-co.re


ERROR    [✗] Pipeline schema does not follow nf-core specs:                                                                                                 
          Default parameters are invalid: 'None' does not match '^.*\\.fai$'
```

### System information

    Nextflow version 22.10.1
    Hardware Laptop
    Executor local
    OS Ubuntu
    Version of nf-core/tools 2.7.dev0
    Python version 3.10

**Comment by awgymer** [comment]
Possibly related to #1841

**Comment by mirpedrol** [comment]
`null` defaults shouldn't be added to the schema to avoid errors such as this one or #1841, they will now be automatically deleted with `nextflow schema build` https://github.com/nf-core/website/pull/1919 
If you already have default values of `null` which were converted to `None` you can remove them by hand.

**Comment by nvnieuwk** [comment]
Awesome, thanks @mirpedrol
