### ISSUE TITLE
schema doesn't run prettier after build

### ISSUE THREAD

**Issue by maxulysse** [nf-core/tools#2115]
### Description of the bug

schema doesn't run prettier after build
I believe we had this issue with the `modules.json` file as well.

**Comment by awgymer** [comment]
I'm not clear if you are saying there is also still an issue with `modules.json` or whether you are meaning that we should add prettier here as we did (in 2.7) for `modules.json`?

**Comment by mashehu** [comment]
Is the schema builder using a different json.dump function? We should use the same as for modules.json

**Comment by maxulysse** [comment]
was saying we need to run prettier to schema, as we now do on `modules.json`
