### ISSUE TITLE
Extension hooks for adding in extra processes

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#213]
It can be useful to add in extra custom code to pipelines, without just forking (which makes it difficult to stay up to date with new releases).

My thought is that we could include special comment lines in the pipeline code, for example:

```nextflow
def foo = bar

// nf-core hook: pipeline_start

process myprocess {}
```

We could then have a tools command called `nf-core extend <pipeline-name>` which pulls a pipeline and finds all of these `// nf-core hook:` lines (or perhaps we hardcode a standardised list of them?).

A file could then be made with empty jinja templating blocks for each of these:

```nextflow
{% block pipeline_start %}
{% endblock %}

{% block pipeline_finish %}
{% endblock %}
```

This could then be extended by the user:

```nextflow
{% block pipeline_start %}

params.mycustom_flag = null
process my_extra_process { //NB:  may need to think about escaping stuff?
  input: params.mycustom_flag
  output: file '*.fastq' into reads
  script: // etc.
}

{% endblock %}

{% block pipeline_finish %}
{% endblock %}
```

Finally, a new child template would be created by combining these two:

```
nf-core extend -t myextension.nf nf-core/rnaseq
```

And this child pipeline could be run normally with nextflow. This `extend` command could be re-run for multiple different pipelines and repeated when new releases come out.

Thoughts?

Phil

**Comment by apeltzer** [comment]
I like the general idea! Some of my thoughts on it:

- Having channels connected with these defined blocks might get tricky
- We should probably document this feature quite in detail, as there is a lot of potential for errors by people who don't really understand what we're doing here.

I however like that we can provide people with possibilities to e.g. stage data from iRods or other systems, add custom code to do e.g. file merging before running the "default" pipeline!

**Comment by mashehu** [comment]
closing this, because I think components fulfill this requirement now.

**Comment by ewels** [comment]
Oh nice, this is an old one!
