### ISSUE TITLE
Lint test `multiqc_config` has `nf-core` hardcoded

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#2130]
This fails when running on pipelines which are not part of the @nf-core organisation:

https://github.com/nf-core/tools/blob/eecf1c7079ef89e918a7493fb2228ac2fc63e5e0/nf_core/lint/multiqc_config.py#L77-L78

In fairness, maybe that's fine - the next bit of the string is pointing to the nf-core website for docs. But if that's the case, we should (a) mention this in the docs for that lint test and (b) ideally make it possible to ignore just this _part_ of the `multiqc_config` lint test.

**Comment by ewels** [comment]
It would also be super nice if the error message could do some kind of diff, showing what was wrong..

**Comment by awgymer** [comment]
Is this test meant to run by default? Because I just ran `nf-core lint` (using tools `2.7.1`) on my custom pipeline and I did not see an error relating to the multiqc config 🤔

**Comment by awgymer** [comment]
So yeah I have the following in `.nf-core.yml`

```yml
multiqc_config:
    - report_comment
```

This is automatically added by the `PipelineCreate.fix_linting()` method that runs if you call `nf-core create` and opt to make an unbranded template. So I'm a bit surprised anyone with a non-nf-core pipeline has run into this

**Comment by ctuni** [comment]
Like @awgymer said, I also have those line in the `.nf-core.yml` file on a custom non-nf-core pipeline, and this test does not fail. Which should be the strategy to a PR that closes this issue?

**Comment by mirpedrol** [comment]
Hello! This issue was a bit old and we now use the custom organisation (see `name`) and also skip the second line of the message for non-nf-core pipelines (see` if branded`).
https://github.com/nf-core/tools/blob/9eac5e9b33a4b86a5228e950a8c8fd16765f4a85/nf_core/pipeline-template/assets/multiqc_config.yml#L3-L5
So I think this can be closed as resolved. Thank you!
