### ISSUE TITLE
Remove aws_tower profile from AWS megatests Github Actions in pipeline template

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#2138]
### Description of feature

Just realised we are using `-profile test_full,aws_tower` for the automated AWS megatests:
https://github.com/nf-core/tools/blob/99961bedab1518f592668727a4d692c4ddf3c336/nf_core/pipeline-template/.github/workflows/awsfulltest.yml#L30

https://github.com/nf-core/tools/blob/99961bedab1518f592668727a4d692c4ddf3c336/nf_core/pipeline-template/.github/workflows/awstest.yml#L25

Do we still need this if the CE has already been defined in Tower? 🤔  See it was added mostly to overwrite the trace files but they should be unique now anyway in most pipelines because they are named by timestamp? Removing `aws_tower` from those profiles should be ok no?

Originally added by Gisela and reviewed by Phil here:
https://github.com/nf-core/configs/pull/256

**Comment by drpatelh** [comment]
Gisela suggested on Slack that it should be fine to remove it but would be good to test it first. Could maybe use the test-pipeline for that.

**Comment by ewels** [comment]
Could presumably also delete the profile from configs 👍🏻

**Comment by mirpedrol** [comment]
Done in https://github.com/nf-core/tools/pull/2287
