### ISSUE TITLE
devcontainer.json: requirements-dev.txt not found

### ISSUE THREAD

**Issue by nick-youngblut** [nf-core/tools#2158]
### Description of the bug

I'm using the https://github.com/nf-core/tools/tree/master/.devcontainer directory in a codespace, and the codespace build fails to run the `postCreateCommand` because `requirements-dev.txt` is not found. If I change the `postCreateCommand`, my `setup.sh` is run, it appears that `../requirements-dev.txt` is the wrong path. If I use `.devcontainer/requirements-dev.txt`, the file is found by `pip`, but the install fails -- likely due to `-e ../`

### Command used and terminal output

My working `devcontainer.json` file:

```console
{
    "name": "nfcore",
    "image": "nfcore/gitpod:2.7.1",
    "postCreateCommand": "bash .devcontainer/setup.sh",
    "remoteUser": "gitpod",
    // Configure tool-specific properties.
    "customizations": {
        // Configure properties specific to VS Code.
        "vscode": {
            // Set *default* container specific settings.json values on container create.
            "settings": {
                "python.defaultInterpreterPath": "/opt/conda/bin/python",
                "python.linting.enabled": true,
                "python.linting.pylintEnabled": true,
                "python.formatting.autopep8Path": "/opt/conda/bin/autopep8",
                "python.formatting.yapfPath": "/opt/conda/bin/yapf",
                "python.linting.flake8Path": "/opt/conda/bin/flake8",
                "python.linting.pycodestylePath": "/opt/conda/bin/pycodestyle",
                "python.linting.pydocstylePath": "/opt/conda/bin/pydocstyle",
                "python.linting.pylintPath": "/opt/conda/bin/pylint"
            },

            // Add the IDs of extensions you want installed when the container is created.
            "extensions": ["ms-python.python", "ms-python.vscode-pylance", "REditorSupport.r", "EditorConfig.EditorConfig",
                           "codezombiech.gitignore", "Gruntfuggly.todo-tree", "ms-vsliveshare.vsliveshare",
                           "nextflow.nextflow", "redhat.vscode-yaml", "streetsidesoftware.code-spell-checker"]
        }
	},
	"features": {
		"ghcr.io/devcontainers/features/docker-in-docker:2": {
            "version": "latest"
        },
        "ghcr.io/devcontainers/features/aws-cli:1": {
            "version": "latest"
        }
    }
}
```

### System information

GitHub codespaces

**Comment by mirpedrol** [comment]
Hi @nick-youngblut, could you provide some more information? From where are you trying to start your Codespace? 
I tested to create one from my repository, a fork of nf-core/tools, and it worked.

**Comment by nick-youngblut** [comment]
Thanks @mirpedrol  for looking into the issue! 

I was just running the codespace from github via: "start codespace in VS Code". I'm not sure why there would be a difference in PATHs between you and me. Maybe the path can be set via an environmental variable (e.g., `/workspaces/${CODESPACE_NAME}/.devcontainer/`) versus using a relative path?

**Comment by mirpedrol** [comment]
I am not an expert on codespaces, so sorry if this doesn't help much. 
Looks like paths should be [relative to `.devocontainer`](https://containers.dev/implementors/json_reference/#image-specific), thus `requirements-dev.txt` should be outside this folder. 
I don't know why those paths would be different in your case, but if the solution is to modify the `requirements-dev.txt` path, the `-e` argument should be modified accordingly to `-e .`
I also share the [documentation](https://docs.github.com/en/codespaces/developing-in-codespaces/creating-a-codespace-for-a-repository) that I followed to start a codespace in case it's helpful :)

**Comment by mashehu** [comment]
Hi @nick-youngblut 
Just to understand your setup: You want to use the `devcontainer.json` in this repo for you own repo? Is that a repository for a pipeline or a fork of nf-core/tools?

**Comment by nick-youngblut** [comment]
> You want to use the devcontainer.json in this repo for you own repo

I'm using the `devcontainer.json` in my own repo. It is a separate, novel Nextflow pipeline.

I'm guessing that this issue is somehow specific to my setup, if no one else has encountered it, or can reproduce it. I'll do some more experimentation on trying to reproduce the issue.

**Comment by mashehu** [comment]
Ah, okay, for pipelines we have a different devcontainer: `https://github.com/nf-core/tools/blob/master/nf_core/pipeline-template/.devcontainer/devcontainer.json` The one you used is for our nf-core tools repository. Does it work with the one from the linked pipeline template?

**Comment by nick-youngblut** [comment]
Thanks @mashehu for pointing out that dev container! Is that devcontainer noted in the README (or other docs) somewhere? I wasn't able to find such info when looking through the docs, but maybe I just missed it.

I'll try out the container ASAP, but I will need to add `postCreateCommand` in order to run my setup (e.g., setting AWS secrets via `nextflow secrets set AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID`, with `$AWS_ACCESS_KEY_ID` set in my github account).

**Comment by mashehu** [comment]
We mentioned it in the release notes, but don't have any documentation about it (yet). Could you please open an issue about it over on [the website repo](github.com/nf-core/nf-co.re)?

Good luck with the modifications!

**Comment by mirpedrol** [comment]
I will close this issue on behalf of the new one in https://github.com/nf-core/nf-co.re/issues/1614
