### ISSUE TITLE
Add option to ignore selector warnings to pipeline template

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#2161]
Inspired by https://github.com/nextflow-io/nextflow/issues/2700#issuecomment-1383984109

This will mean that process selector warnings are not shown by default when running pipelines. However, if `-profile devel` is used then they are shown to find and fix any configuration issues. Could go for other names too e.g. `dev` (clashes with branch names?), `development` etc. or we can include it as part of the existing `debug` profile.

Will need to update the developer docs on the website and contributing docs / issue and PR templates  in the pipeline template to suggest using this profile when writing pipelines.

**Comment by matthdsm** [comment]
I think it would make the most sense to add this to the `debug` profile. That way we avoid any possible name collision

**Comment by fa2k** [comment]
The default has now been changed to hide the process selector warnings, with a possibility to re-enable them with the debug profile. This will be less confusing for end users. Thanks for the issue drpatelh.
