### ISSUE TITLE
Missing configuration and report files

### ISSUE THREAD

**Issue by sstrong99** [nf-core/tools#2191]
### Description of the bug

When I run the nf-core/atacseq pipeline on NextflowTower with an aws compute environment, the only files in `<outdir>/pipeline_info` are `samplesheet.valid.csv` and `software_versions.yml`. The pipeline config indicates that there should be 4 other files as well: 
```nextflow 
timeline {
    enabled = true
    file    = "${params.tracedir}/execution_timeline_${trace_timestamp}.html"
}
report {
    enabled = true
    file    = "${params.tracedir}/execution_report_${trace_timestamp}.html"
}
trace {
    enabled = true
    file    = "${params.tracedir}/execution_trace_${trace_timestamp}.txt"
}
dag {
    enabled = true
    file    = "${params.tracedir}/pipeline_dag_${trace_timestamp}.html"
}
```

and `tracedir = ${params.outdir}/pipeline_info` by default.

### System information

NextflowTower 
aws TowerForge compute environment
Nextflow version 23.02.0-edge

**Comment by sstrong99** [comment]
FYI @maxulysse

**Comment by maxulysse** [comment]
Can confirm that I reproduce that with tower on both AWS and GCP

Tried @FriederikeHanssen trick and set up tracedir in full, and it worked...
I now have the `pipeline_info` folder

**Comment by mashehu** [comment]
How is that an issue with tools? Sounds more like a tower problem, or am I missing something?

**Comment by ewels** [comment]
It sounds like a config resolution issue within Nextflow to me. So likely something that needs a fix within the template.

**Comment by sstrong99** [comment]
I removed these lines from the `nextflow_schema.json` and that seems to have fixed it: https://github.com/nf-core/atacseq/blob/master/nextflow_schema.json#L591-L597

Maybe some kind of conflict btw the default specified there vs the one specified in `nextflow.config`?

**Comment by sstrong99** [comment]
and actually just deleting the `default` line seems to fix it as well: https://github.com/nf-core/atacseq/blob/master/nextflow_schema.json#L594

**Comment by maxulysse** [comment]
Fixed in https://github.com/nf-core/tools/pull/2317
