### ISSUE TITLE
Remove --tracedir parameter

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#2208]
### Description of feature

See https://github.com/nf-core/rnaseq/pull/966/commits/0b23eb0c8075deeaadee764bf47426079c8318a4

A number of users have reported that trace reports etc aren't being published as expected. Turns out it was an issue with resolving this parameter in the configuration. The easiest fix is to remove the `--tracedir` parameter because it isn't really adding much to the template. Users can still overwrite via a custom config but I suspect this is going to be a rarity.

**Comment by ewels** [comment]
I think that the reason we had this in the first place was that `tracedir` has to be a POSIX filesystem, so breaks if you set it to be an s3 bucket. So we had this set to `params.outdir` by default but customisable for anyone running on cloud where the trace couldn't be written to object storage.

Pretty sure it was @apeltzer who added it, maybe he can comment?

Phil

**Comment by apeltzer** [comment]
Phils summary is accurate - we had to add it in the past to be able to write out tracedir on both HPC and Cloud according to the requirements. If this is not anymore the case I'm happy to see it removed - though I'd be cautious if this brings back issues we saw in the past ...

**Comment by ewels** [comment]
Doing some digging:
* https://github.com/nf-core/tools/issues/79
* https://github.com/nextflow-io/nextflow/issues/813

So I think that this is fixed now and can hopefully be safely removed.

Error mode should be a crash when running with a bucket `--outdir` and resuming.

**Comment by mirpedrol** [comment]
Closed with #2317
