### ISSUE TITLE
Document how to use the GPL3 license when using `nf-core lint`

### ISSUE THREAD

**Issue by richelbilderbeek** [nf-core/tools#2230]
### Description of feature

I enjoy using a linter such as `nf-core lint`. By default this tool assumes an MIT license, however, I use GPL3. In the documentation at [https://github.com/nf-core/tools#linting-config](https://github.com/nf-core/tools#linting-config) there is some help to change the setup of `nf-core lint`, yet does not have an example how to specify that the license is GPL3.

I hope it will be documented how to use a custom (not MIT, yet for example, GPL3) license when using `nf-core lint`.

**Comment by ewels** [comment]
Hi @richelbilderbeek,

I just stumbled across this issue, sorry it took so long.

The easiest way to solve this is to simply disable the lint test with a config, as described in the docs: https://nf-co.re/docs/nf-core-tools/pipelines/lint#linting-config

The same is true for every lint test, I'm not sure that we want to explicitly document each as such, so I'll close this issue. But thanks for flagging and if you have any ideas on how to surface the linting config in a better way then do say. Note that the new pipeline creation tool will make much of this stuff opt-in from the start so I suspect it will be less of an issue going forward.

Phil
