### ISSUE TITLE
Crontab specification error in stale workflow

### ISSUE THREAD

**Issue by fabianegli** [nf-core/tools#2231]
The day specification (the last number in the crontab entry) should be any one from 0-6. 7 is invalid. 0 is Sunday.

https://github.com/nf-core/tools/blob/27318f1e42b5bde7874b104ce327ec8a20d16e78/.github/workflows/stale.yml#L4

For reference, see: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

**Comment by mashehu** [comment]
Fixed in #2241
