### ISSUE TITLE
nf-core tools hangs

### ISSUE THREAD

**Issue by tzvi909** [nf-core/tools#2234]
### Description of the bug

nf-core tools hanging when running on a t2.2xlarge AWS EC2 instance and not loading the html page when running nf-core schema build. issues with both micromamba and mamba installation. We were not having these issues on our old Azure VM. Essentially running much slower on AWS than on Azure

### Command used and terminal output

```console
$ nf-core lint 

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.7.2 - https://nf-co.re
```

### System information

t2.2xlarge AWS EC2
Ubuntu Linux
nf-core/tools 2.7.2
python 3.11.2
pytest 7.2.2

**Comment by nfancy** [comment]
Hi, I have the similar issue after installing the dev version 

```
nfancy@nuruns-lab:~/hpc-home/overclockers_backup/resources/nf-core-scflow$ nf-core lint

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.8.dev0 - https://nf-co.re
```

I installed this version

```
pip install --upgrade --force-reinstall git+https://github.com/nf-core/tools.git@dev
```

**Comment by ewels** [comment]
Please could someone run the command with the verbose `-v` flag? There is very little we can do otherwise as we are not able to replicate this problem.
