### ISSUE TITLE
I'm facing a stubborn issue while running pipelines, and I urgently need your guidance and assistance!

### ISSUE THREAD

**Issue by HardingZhang** [nf-core/tools#2246]
When I run different pipelines, including RNA-seq and ATAC-seq, I always encounter the following error. Although it can sometimes be temporarily resolved by using the `-resume`, it still frequently occurs, causing my workflow to become disjointed. After searching online, it seems that the issue may be related to Docker, but I am not sure how to resolve it. I believe I need your help to solve this problem.

```
Command error:
  docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:319: getting the final child's pid from pipe caused \"EOF\"": unknown.
  time="2023-04-21T22:25:35+08:00" level=error msg="error waiting for container: context canceled"

The exit status of the task that caused the workflow execution to fail was: 125.

The full error message was:

Error executing process > 'NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_MARKDUPLICATES_PICARD:PICARD_MARKDUPLICATES (S6_REP1)'

Caused by:
  Process `NFCORE_ATACSEQ:ATACSEQ:MERGED_LIBRARY_MARKDUPLICATES_PICARD:PICARD_MARKDUPLICATES (S6_REP1)` terminated with an error exit status (125)
```

**Comment by mribeirodantas** [comment]
Seems to be related to this: https://github.com/docker/docs/issues/7962#issuecomment-450889365

**Comment by HardingZhang** [comment]
> Seems to be related to this: [docker/docs#7962 (comment)](https://github.com/docker/docs/issues/7962#issuecomment-450889365)

Thank you for your advice; I will do a test in the next two days using your suggestion.

**Comment by ewels** [comment]
This issue does not appear to be anything to do with the nf-core/tools Python software package, so I'm going to close the issue. Please post on the Nextflow or nf-core Slack organisations if you need support.
