### ISSUE TITLE
nf-core modules create-test-yml should make tags for other modules used in the test 

### ISSUE THREAD

**Issue by SPPearce** [nf-core/tools#2248]
### Description of feature

When `nf-core subworkflows create-test-yml` is invoked, the resulting test.yml file automatically includes a `tag` entry for every tool used in the tests. This means that when any of those tools are updated, the tests for the subworkflows are also ran.

However, this feature is not present in `nf-core modules create-test-yml`, meaning that the tags are only for the module that is being directly tested. So if toolA uses toolB to pre-process some input data (to generate a reference file for instance), then updates to toolB might break toolA. For instance, the recent updates to samtools affect several downstream tools that use samtools as a preprocessing step, for instance the bamcmp module, but the tests for these were not rerun when samtools was updated. The subworkflows on the other hand correctly update, as they have the tags.

**Comment by SPPearce** [comment]
The subworkflow create-test-yml code includes this function that grabs the import statements from the tests main.nf

https://github.com/nf-core/tools/blob/eecf1c7079ef89e918a7493fb2228ac2fc63e5e0/nf_core/subworkflows/test_yml_builder.py#L202-L222

Presumably the same kind of logic could be applied to the tests main.nf for modules.

**Comment by mirpedrol** [comment]
This is now outdated with nf-test, tags are checked with nf-core linting and the missing ones are reported in the error message
