### ISSUE TITLE
Docker Building / tagging on testing

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#225]
Hi!

current situation is as follows:

- `master` on GitHub is `latest` on Docker Cloud
- `dev` on GitHub is `dev` on Docker Cloud

At the moment, we always have the issue when we change something in the environment.yaml or Dockerfile, that the tests will fail because of missing dependencies. This can only be fixed once we push to `master`, which then triggers a new `latest` container. 

Proposition:

- Use `dev` for testing in `dev`, e.g. changing our container path in `nf-core/tools` to use 
- Use `latest`for testing in `master`, and `tag` for stable releases

```
  container = 'nfcore/rnaseq:latest' //old
  container = 'nfcore/rnaseq:dev' //new
```

Any thoughts on this? This would allow us to test the containers more intensively when working on the `dev` and even update the docker container once, by simply doing a simple PR updating the Docker image first and then submitting a second PR containing the nextflow code changes.

The current tagging behaviour in `.travis.yml` doesn't seem to work the way we want it:

```
- docker pull nfcore/rnaseq
- docker tag nfcore/rnaseq nfcore/rnaseq:latest
```

By default, `docker pull nfcore/rnaseq` pulls already the latest container (!), so we should instead either pull `dev` and tag that to be `latest`, or use the proposition on top of this comment here to change the overall behaviour :-) 

Stumbled across this when adding `csvtk` to rnaseq, which is currently not tested ideally because the dependency won't be in before we merge in the updated `environment.yaml`.

**Comment by apeltzer** [comment]
Changing the `travis.yml`:

```
```

Results in lint error
```
- docker pull nfcore/rnaseq:dev
  # Fake the tag locally so that the pipeline runs properly
- docker tag nfcore/rnaseq:dev nfcore/rnaseq:latest
```

ERROR: Test Failures:
  http://nf-co.re/errors#5: CI is not pulling the correct docker image. Should be:
    'docker pull nfcore/rnaseq'
  http://nf-co.re/errors#5: CI is not tagging docker image correctly. Should be:
    'docker tag nfcore/rnaseq nfcore/rnaseq:latest'
```

**Comment by drpatelh** [comment]
@apeltzer I believe I am experiencing similar issues.

https://nfcore.slack.com/archives/CE5EL6326/p1544521153000300

**Comment by apeltzer** [comment]
Yes, this looks exactly the same way! :-)

**Comment by apeltzer** [comment]
I guess linting should maybe just check for consistency, e.g. that the `.travis.yml` ask for the image to be both on `dev` for example. 

Can take a look at this, I guess its something relevant for everyone who keeps updating pipeline dependencies from time to time...
