### ISSUE TITLE
nf-core download error

### ISSUE THREAD

**Issue by SNOL2** [nf-core/tools#2282]
### Description of the bug

Hello, there is an error when I want to download nf-core/rnaseq.Can you kindly tell me how to solve it? Thanks in advance.
Here is Error:GitHub API PR failed - got return code 401 from https://api.github.com/repos/nf-core/rnaseq/branches

### Command used and terminal output

```console
nf-core download rnaseq
```

**Comment by mashehu** [comment]
Could you please run `nf-core --verbose download rnaseq` and post the complete output here?

**Comment by SNOL2** [comment]
> Could you please run `nf-core --verbose download rnaseq` and post the complete output here?

Sure, thanks in advance!
`
DEBUG    Fetching list of nf-core workflows                                                               list.py:102
DEBUG    Starting new HTTPS connection (1): nf-co.re:443                                       connectionpool.py:1007
DEBUG    https://nf-co.re:443 "GET /pipelines.json HTTP/1.1" 200 276038                         connectionpool.py:465
DEBUG    Initialising GitHub API requests session                                                        utils.py:427
DEBUG    Using GitHub auth: gh CLI config: ahy1221                                                       utils.py:471
DEBUG    Starting new HTTPS connection (1): api.github.com:443                                 connectionpool.py:1007
DEBUG    https://api.github.com:443 "GET /repos/nf-core/rnaseq/branches HTTP/1.1" 401 80        connectionpool.py:465
DEBUG    Requested URL: https://api.github.com/repos/nf-core/rnaseq/branches                             utils.py:477
DEBUG    From requests cache: False                                                                      utils.py:478
DEBUG    Request status code: 401                                                                        utils.py:479
DEBUG    Request reason: Unauthorized                                                                    utils.py:480
DEBUG    {                                                                                               utils.py:484
             "Server": "GitHub.com",                                                                                 
             "Date": "Tue, 09 May 2023 00:45:52 GMT",                                                                
             "Content-Type": "application/json; charset=utf-8",                                                      
             "Content-Length": "80",                                                                                 
             "X-GitHub-Media-Type": "github.v3; format=json",                                                        
             "X-RateLimit-Limit": "60",                                                                              
             "X-RateLimit-Remaining": "59",                                                                          
             "X-RateLimit-Reset": "1683596752",                                                                      
             "X-RateLimit-Used": "1",                                                                                
             "X-RateLimit-Resource": "core",                                                                         
             "Access-Control-Expose-Headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP,                      
         X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource,                           
         X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval,                                
         X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",                               
             "Access-Control-Allow-Origin": "*",                                                                     
             "Strict-Transport-Security": "max-age=31536000; includeSubdomains; preload",                            
             "X-Frame-Options": "deny",                                                                              
             "X-Content-Type-Options": "nosniff",                                                                    
             "X-XSS-Protection": "0",                                                                                
             "Referrer-Policy": "origin-when-cross-origin, strict-origin-when-cross-origin",                         
             "Content-Security-Policy": "default-src 'none'",                                                        
             "Vary": "Accept-Encoding, Accept, X-Requested-With",                                                    
             "X-GitHub-Request-Id": "D57A:07FA:11C819A:129677A:645997C0"                                             
         }                                                                                                           
DEBUG    {                                                                                               utils.py:485
             "message": "Bad credentials",                                                                           
             "documentation_url": "https://docs.github.com/rest"                                                     
         }                                                                                                           
DEBUG    {}                                                                                              utils.py:486
CRITICAL GitHub API PR failed - got return code 401 from                                              download.py:127
         https://api.github.com/repos/nf-core/rnaseq/branches
`

**Comment by mashehu** [comment]
what do you get with `gh auth status`?

**Comment by SNOL2** [comment]
Oh, I address this issue on your advice. Thanks!

**Comment by IdoBar** [comment]
Hi @mashehu ,

I'm having exactly the same issue.
This is the output of `gh auth status`:
```
github.com
  ✓ Logged in to github.com as IdoBar (GITHUB_TOKEN)
  ✓ Git operations for github.com configured to use https protocol.
  ✓ Token: ghp_************************************
  ✓ Token scopes: gist, read:org, repo, user
```

Thanks, Ido

**Comment by mashehu** [comment]
Hi @IdoBar,

Can you please post the error log when you run the nf-core command (with the `--verbose` parameter)?

**Comment by IdoBar** [comment]
Hi @mashehu ,

This is the error message I get:
```
$ nf-core --verbose download rnaseq --container-system singularity -r 3.12.0

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.10 - https://nf-co.re


DEBUG    Fetching list of nf-core workflows                                                                                                     list.py:102
DEBUG    Starting new HTTPS connection (1): nf-co.re:443                                                                             connectionpool.py:1048
DEBUG    https://nf-co.re:443 "GET /pipelines.json HTTP/1.1" 304 0                                                                    connectionpoo[0/1927]
DEBUG    Initialising GitHub API requests session                                                                                              utils.py:440
DEBUG    Using GitHub auth: gh CLI config: IdoBar                                                                                              utils.py:484
DEBUG    Starting new HTTPS connection (1): api.github.com:443                                                                       connectionpool.py:1048
DEBUG    https://api.github.com:443 "GET /repos/nf-core/rnaseq/branches HTTP/1.1" 401 80                                              connectionpool.py:546
DEBUG    Requested URL: https://api.github.com/repos/nf-core/rnaseq/branches                                                                   utils.py:490
DEBUG    From requests cache: False                                                                                                            utils.py:491
DEBUG    Request status code: 401                                                                                                              utils.py:492
DEBUG    Request reason: Unauthorized                                                                                                          utils.py:493
DEBUG    {                                                                                                                                     utils.py:497
             "Server": "GitHub.com",
             "Date": "Thu, 05 Oct 2023 12:34:17 GMT",
             "Content-Type": "application/json; charset=utf-8",
             "Content-Length": "80",
             "X-GitHub-Media-Type": "github.v3; format=json",
             "X-RateLimit-Limit": "60",
             "X-RateLimit-Remaining": "59",
             "X-RateLimit-Reset": "1696512857",
             "X-RateLimit-Used": "1",
             "X-RateLimit-Resource": "core",
             "Access-Control-Expose-Headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining,
         X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval,
         X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",
             "Access-Control-Allow-Origin": "*",
             "Strict-Transport-Security": "max-age=31536000; includeSubdomains; preload",
             "X-Frame-Options": "deny",
             "X-Content-Type-Options": "nosniff",
             "X-XSS-Protection": "0",
             "Referrer-Policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
             "Content-Security-Policy": "default-src 'none'",
             "Vary": "Accept-Encoding, Accept, X-Requested-With",
             "X-GitHub-Request-Id": "D0E0:1849F:8142:8E39:651EAD49"
         }
DEBUG    {                                                                                                                                     utils.py:498
             "message": "Bad credentials",
             "documentation_url": "https://docs.github.com/rest"
         }
DEBUG    {}                                                                                                                                    utils.py:499
ERROR    GitHub API PR failed - got return code 401 from https://api.github.com/repos/nf-core/rnaseq/branches                                __main__.py:78
```

Thanks, Ido

**Comment by mashehu** [comment]
I added your github user to the nf-core org. Can you try the command again?

**Comment by IdoBar** [comment]
Hi @mashehu ,

I'm still getting the same error.
Please note that my connection is behind a proxy (though I have exported `HTTP_PROXY`, etc that allow me to download from the web, install conda, etc. regularly)
My organisation uses a custom Docker registry if that helps.

Thanks!

**Comment by IdoBar** [comment]
Is there a way to just get the list of containers so I could download them myself (something like `--dry-run` flag)?
Thanks, Ido

**Comment by IdoBar** [comment]
> Is there a way to just get the list of containers so I could download them myself (something like `--dry-run` flag)? Thanks, Ido

If anyone interested in this, that's how I downloaded the container images myself:
```
find ~/.nextflow/assets/nf-core/rnaseq/ -name *.nf | xargs grep "depot.galaxyproject" | awk '{print $2}' | uniq | tr -d \' | parallel --rpl  "{outfile} s=https://==; s=[:/]+=-=g;" aria2c -c {} -o $NXF_SINGULARITY_CACHEDIR/{outfile}.img
```
