### ISSUE TITLE
Travis should check releases

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#23]
Travis builds on pushes, PRs and also tags (which for us are the same as releases). It would be great if there could be a set of tests which are specific to releases.

Suggestions:
* [x] Introduce `--release` flag for nf-core lint
* [x] Conditionally execute lint tests with `--release` flag, when git activity happens on the `master` branch (check env var `TRAVIS_BRANCH`)

On `--release` set:
* [x] Check that the version variable is numeric-only
* [x] Check that the docker slug has a tag which isn't `latest`
* [x] Check that the tag name (release number) is the same as the config version and container label.

Bonus points for challenging ones:

* [ ] Check that fixed bioconda package versions are the latest available (warn if not)

**Comment by ewels** [comment]
If we always develop in a `develop` branch, these tests could instead just run whenever a push goes to the `master` branch. Then we have a chance to catch failures before we push the release.

**Comment by apeltzer** [comment]
I'd be even happier with that kind of best practices: Branches are good to keep things like the master branch stable. Just imagine we'd have merged my commits this morning without further testing ;-)

**Comment by sven1103** [comment]
What do you have in mind? A `--release` flag for lint, that additionally checks the points above? We could then use the `TRAVIS_BRANCH` env var for differentiate between `master` and `develop`.

**Comment by ewels** [comment]
I was just thinking of getting Python to look for the env var or the git branch name. But a `--release` command line flag is even better as then it's easy to soft-test it before pushing. Then we can just have a conditional test that runs with this flag if it's on `master`...

**Comment by sven1103** [comment]
exactly what i was thinking :)

**Comment by sven1103** [comment]
I just updated your first comment @ewels, hope that's ok :)

**Comment by sven1103** [comment]
Opened an issue, so we modify the `travis.yml` accordingly: https://github.com/nf-core/cookiecutter/issues/16

**Comment by ewels** [comment]
I think move the bioconda thing into a separate issue, then this is done 👍 

Nice job @sven1103!
