### ISSUE TITLE
[create] Improve logic in CLI wizard

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#2341]
At the moment, the wizard in `nf-core create` is not very user friendly.

* Needs a lot more help text
* Needs simpler distinction between usage for nf-core or not
    * Should be one of the first questions. Point out that it's difficult to go back to being nf-core.
* When customising for non nf-core, features should be opt-in, not opt-out
* Better phrasing of questions - focus on usage, not feature names
   * Current bad example: _"Remove igenomes"_
   * Could be rephrased: <br>_"Will this pipeline work with genomics data? <br><sub>(Does it need built-in configuration for reference genome indices?)</sub>"_
* Add more options about certain behaviour, such as installing default modules
    * #2285

> I was too afraid to not include something we might need so i simply clicked N when I was asked 😄 
> _@FloWuenne_

- [ ] Sketch out potential flow and discuss (in this issue)
- [ ] Refactor prompts

**Comment by awgymer** [comment]
As part of this might be useful to properly maintain docs on what fields a `template.yml` can have and what values they can take. 
Currently you can't tell particularly easily and you are better off running the wizard to generate one first.

Very minor as running the wizard isn't really that intensive, but it is interactive and some use case where you want to programatically run `create` with a `--template-yaml` does exist. Also, and this is really quite niche, if you want to update the template of your repo to include/exclude a particular optional feature then technically you can do so by adjusting the `template.yaml` appropriately and running `nf-core sync` with the modified file passed to `--template-yaml`. Again it would be useful to be able to edit/construct that more easily without needing to run a create command to generate it for you.

**Comment by mirpedrol** [comment]
Closing this as it is implemented. The docs will be added after nf-core/tools release by the website PR https://github.com/nf-core/website/pull/2742
