### ISSUE TITLE
Add template information to `.nf-core.yml` file

### ISSUE THREAD

**Issue by mirpedrol** [nf-core/tools#2359]
### Description of feature

When the creation of a pipeline is customized, the information is now stored in a file `pipeline_template.yml`. We should store  this information in the `.nf-core.yml` file under a new tag `template`.
Lint that the deprecated `pipeline_template.yml` file doesn't exist.

**Comment by awgymer** [comment]
Would this then be auto-detected by commands that currently take a `--template-yaml` param?

**Comment by mirpedrol** [comment]
> Would this then be auto-detected by commands that currently take a --template-yaml param?


We should take this into account. Reading the current `pipeline_template.yml` file and adding the info to `.nf-core.yml` before removing it.

**Comment by mirpedrol** [comment]
This is now done by #2388 and #2389
@awgymer if you are using this feature and would like to try it out with your pipeline, let us know your feedback :D
