### ISSUE TITLE
Wrong links in "assets/multiqc_config.yml"

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#2361]
### Description of the bug

The link rendered when the pipeline template below doesn't work:
https://github.com/nf-core/tools/blob/e5ce6ce20304835bd40f102f038b7e1aadc888b2/nf_core/pipeline-template/assets/multiqc_config.yml#L2

 I believe it should be `href="https://github.com/{{ name }}/tree/{{ version}}"`

Also, a related question. Will the link below work on the website if for example I have a dev version of a pipeline defined in `manifest.version` e.g. `3.13.0dev`. Could be another bug there too.
https://github.com/nf-core/tools/blob/e5ce6ce20304835bd40f102f038b7e1aadc888b2/nf_core/pipeline-template/assets/multiqc_config.yml#L4

**Comment by maxulysse** [comment]
I had the dev in sarek, something is weird there

**Comment by SusiJo** [comment]
Is this wrong link related to [this linting error](https://github.com/nf-core/tools/actions/runs/5143935324/jobs/9259577934#step:17:28)? 

```
[✗] 1 Pipeline Test Failed                                                                           
multiqc_config: 'assets/multiqc_config.yml' does not contain a matching 'report_comment'.                                                          
```

**Comment by SusiJo** [comment]
The linting of the `multiqc_config` https://github.com/nf-core/tools/blob/e5ce6ce20304835bd40f102f038b7e1aadc888b2/nf_core/lint/multiqc_config.py#L74 checks for the `manifest.version` in the `nextflow.config`. However, if the `dev` branch has a version string like `manifest.version = '2.1.0dev'. There will not be any such tag available for creating the link described above. 
So maybe the `manifest.version` should be taken from the `nextflow.config` of the `master` branch or the `dev` string removed.
