### ISSUE TITLE
Add a `--stub` option to `create-test-yml`

### ISSUE THREAD

**Issue by nvnieuwk** [nf-core/tools#2420]
### Description of feature

Some modules/subworkflow tests can only be run on big data. For now developers had to manually add the `-stub` argument to every command after the `create-test-yml` command finishes. It would be nice if an option could be added the `create-test-yml` command for `modules` and `subworkflows` that will add this option automatically and possibly also runs these tests as stub runs.

Slack thread: https://nfcore.slack.com/archives/CE5LG7WMB/p1694503436203269

**Comment by mirpedrol** [comment]
Done with #2277
