### ISSUE TITLE
nf-core modules test migrate

### ISSUE THREAD

**Issue by Emiller88** [nf-core/tools#2491]
We should create a command that takes some of the effort out of converting tests. Wipes the pytest-workflow files, makes all of the new ones and maybe creates a co-pilot or some other LLM prompt to take the tests from pytest-workflow and convert them to nf-test.

```[tasklist]
### Tasks
- [ ] Test generation prompt for copilot for modules
```

**Comment by mashehu** [comment]
👀 https://github.com/nf-core/tools/pull/2490

**Comment by Emiller88** [comment]
Duplicate of #2490
