### ISSUE TITLE
Check that bioconda package versions are latest

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#25]
If pipelines have a bioconda `environment.yml`, we should be able to check:

* [x] That they are all pinned to a specific version _(fail if not)_

When running with `--release`:
* [x] That  this version is the most recent bioconda version available _(warn if not)_

**Comment by sven1103** [comment]
>  That this version is the most recent bioconda version available (warn if not)

Suggestion: Build the conda environment on TRAVIS, then `--dry-run update` the specified packages from the `environment.yml` and handle the output (check which packages would have been updated).

Second: Should we do this for release check only?

**Comment by sven1103** [comment]
Hm, maybe it is just easier to use the Anaconda cloud API :) https://api.anaconda.org/docs#/package

**Comment by ewels** [comment]
> `--dry-run update`

Nice idea! I was thinking of doing some kind of `conda search` for each requirement, but perhaps this would be simpler.

> Should we do this for release check only?

Yes, apologies I meant to put this in the issue but forgot. Now updated.

> Anaconda cloud

Sure, though it may be a pain if we need authentication to use that..

**Comment by ewels** [comment]
Ok great! That's perfect.

**Comment by sven1103** [comment]
Solved in #28
