### ISSUE TITLE
nf-core bot should fix black linting on pipelines

### ISSUE THREAD

**Issue by mirpedrol** [nf-core/tools#2519]
### Description of feature

Add black to pipelines [fix-linting.yml workflow](https://github.com/nf-core/tools/blob/master/nf_core/pipeline-template/.github/workflows/fix-linting.yml).

As we do in the tools repo:
https://github.com/nf-core/tools/blob/9ab896c140ee3fde816d250f3d8353aee5547d78/.github/workflows/fix-linting.yml#L35-L39

**Comment by mashehu** [comment]
Done with #2635
