### ISSUE TITLE
Drop Singularity Hub build file from all repositores / Update linting? 

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#252]
As we already dropped Singularity support and only pull Docker images, we don't really need a Singularity recipe in the respective repositories.  This should also be updated in the linting, as we currently lint for the presence of the `Singularity` file. 

Afterwards, we could update each repository and remove the Singularity file & remove it from the template as well.

**Comment by pachiras** [comment]
Have you decided not to support Singularity? May I ask the reason why?

**Comment by matq007** [comment]
I can have a look at it and make a PR @apeltzer.

**Comment by apeltzer** [comment]
That would be fab 👍

**Comment by ewels** [comment]
Don't worry, we absolutely won't drop Singularity - we love it! Most of the original nf-core users are running Singularity as the primary back end. It's just Singularity Hub that has been difficult.

**Comment by pachiras** [comment]
Thank you for your comments. I'll give it a try.

**Comment by drpatelh** [comment]
Implemented in https://github.com/nf-core/tools/pull/261
