### ISSUE TITLE
Add subcommand level `--verbose` for `nf-core modules tests`

### ISSUE THREAD

**Issue by jfy133** [nf-core/tools#2554]
### Description of feature

Currently you can get verbose module (and presumably subworkflow) nf-test verbose/debugging logs by asking for `--verbose`  at the tools level.

I find this unintuitive as if I'm looking for nf-test logs, I wouldn't ask at the nf-core level as I'm not interested in nf-core logs at the same time.

e.g. I want to find out why my nf-test failed

```
nf-core --verbose modules test <module>
```

doesn't make sense to me, but rather

```
nf-core modules test --verbose <module>
## OR
nf-core modules test <module> --verbose
```

Does, as it 'feels' like I'm assking the `--verbose` log for the test itself. However this gives an error of an unrecognised option

More details here: https://nfcore.slack.com/archives/CE5LG7WMB/p1701779689455179

That said the 'mixed' `--verbose` isn't so messy.  As a fast work around could just alias a `modules test` level verbose to the general nf-core one.

**Comment by Femi-lawal** [comment]
@jfy133 @mashehu Hi, please can I work on this?

**Comment by mashehu** [comment]
Sure, give it a try! You can tag me or @mirpedrol here or on the nf-core slack if you need some help.

**Comment by LaurenceKuhl** [comment]
Hi @Femi-lawal, I'd have a look if you haven't yet?

**Comment by LaurenceKuhl** [comment]
Hi, this is now done in https://github.com/nf-core/tools/pull/3120 so closing this issue :)
