### ISSUE TITLE
Add linting for dependency tags in modules with nf-test

### ISSUE THREAD

**Issue by nvnieuwk** [nf-core/tools#2559]
### Description of feature

As discussed on [Slack](https://nfcore.slack.com/archives/CQY2U5QU9/p1701867507315399)

Add a linting failure if the `main.nf.test` does not contain the tag of the modules used in the `setup` clause. This to make sure that any changes done to the dependencies doesn't break any tests.

**Comment by mashehu** [comment]
fixed with #2572
