### ISSUE TITLE
Gitbook for documentation

### ISSUE THREAD

**Issue by matq007** [nf-core/tools#257]
I have seen this project already used by some tools. Maybe it's an overkill but I like the nice clean UI https://www.gitbook.com/pricing#contactus. They also offer a free plan for open source projects. We can make an organization `nf-core` which could store all everything in one nice wiki? 
Any thoughts?

**Comment by ewels** [comment]
Yeah I've seen this before too. I think our current website is nicer though..? 🤔 😉  We're already set up to just write markdown, so I think it's comparatively easy to write.
