### ISSUE TITLE
Add monochrome logs to template

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#265]
@ewels implemented some changes in the PR below that will need to be updated in the template:

* Monochrome logs in `main.nf `along with an associated parameter.
* Output paths have also been changed for nextflow trace files in `nextflow.config`
* `base.config`  now contains broader compute categories that can be invoked by tag as opposed to explicitly specifying a separate section per process. Maybe we can provide some reasonable defaults in the template.

https://github.com/nf-core/chipseq/pull/62

**Comment by ewels** [comment]
Thanks @drpatelh! I can do these now - was waiting for the merge, but good to have a reminder 😀
