### ISSUE TITLE
nf-core modules/subworkflows update should not delete modules specific config files

### ISSUE THREAD

**Issue by maxulysse** [nf-core/tools#2658]
### Description of feature

ie we have this file in fetchngs https://github.com/nf-core/fetchngs/blob/dev/modules/nf-core/sratools/fasterqdump/nextflow.config
And it gets deleted everytime, it's a bit of a hassle it would be nice to have an option or a warning or a mention or something

**Comment by mirpedrol** [comment]
Done with #2763
