### ISSUE TITLE
modules pytest migration flag fails to remove symlinked pytest directories

### ISSUE THREAD

**Issue by jfy133** [nf-core/tools#2682]
### Description of the bug

Some tools that have a subcommand named `build` did not work with the pytest implementation of module tests.

The workaround was to make a symlink of the module name from `build` to something called `build_test` 

(example: MALT/BUILD).

During `nf-core modules create malt/build --migrate-pytest`) I got an error message saying that it could not remove symlinks, so the migration failed. 

This then meant pytest files were still under the `test/` directory, and was not removed from the pytest tags yml file.

(Unfortuantely I don't have it on my terminal anymore due to other traceback)

**Comment by mirpedrol** [comment]
Done with #2770
