### ISSUE TITLE
Linting with nf-core tools 2.12.1 throws a warning when using multiple alias imports

### ISSUE THREAD

**Issue by TCLamnidis** [nf-core/tools#2726]
### Description of the bug

Using a multiple alias import like below, causes nf-core lint to throw a warning.
```
include { SAMTOOLS_INDEX as SAMTOOLS_INDEX_MEM; SAMTOOLS_INDEX as SAMTOOLS_INDEX_BT2; SAMTOOLS_INDEX as SAMTOOLS_INDEX_MERGED_LANES } from '../../modules/nf-core/samtools/index/main'
```

```
Warning:
│ map   │ subworkflows/local/map.nf │ Included component 'SAMTOOLS_INDEX_MEM; SAMTOOLS_INDEX' versions are not    │
│       │                           │ added in main.nf                                                            |
```

In the example, the module name is read in wrong as `SAMTOOLS_INDEX_MEM; SAMTOOLS_INDEX` instead of `SAMTOOLS_INDEX_MEM`, so checks for versions and use of the module throw warnings.

### Command used and terminal output

```console
nf-core lint
```

### System information

nf-core v2.12.1

**Comment by mirpedrol** [comment]
Done with #2762
