### ISSUE TITLE
Implement pinning for bump-version and linting

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#273]
As mentioned here, we currently don't pin against a specific release of nf-core/configs which caused some trouble: https://github.com/nf-core/configs/issues/18 

We should check:

- using the lint function that whenever a release is done, this is addressed
- do regular releases of nf-core/configs to incorporate newer institution configs
- check when bumping a version, that this release is NOT using latest/master but instead a fixed (tagged, released) version of a pipeline

**Comment by ewels** [comment]
Yes to the first point, and to the second if you like. No to the third point though, as this means that we lose flexibility (which is the main point of having these configs in a separate repo).

**Comment by ewels** [comment]
Closing this issue, as I don't think that we should do the pinning (and we've discussed this on slack). Feel free to reopen if you feel that this needs discussion :)
