### ISSUE TITLE
Add --profile flag  to `nf-core modules test` to allow CLI speification of container/conda engine

### ISSUE THREAD

**Issue by jfy133** [nf-core/tools#2753]
### Description of feature

It would be nice to skip having to select the container engine /env software option when running tests.

This is work aroundable by specifying `PROFILE=singularity`  before the command for example, but I find that is not natural usage when executing flag based CLI tools that otherwise the `nf-core` package is.

One other alternative is to add a `.nfcorerc` file or similar that goes into home, and one can permanently set such an option, and if the file/option is detected, the `-d`.
I  don't

**Comment by mirpedrol** [comment]
Done with #2767
