### ISSUE TITLE
Github Action Runners run out of diskspace

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#2754]
### Description of the bug

Basic summary here: https://github.com/actions/runner-images/discussions/9329
Also see thread on slack: https://nfcore.slack.com/archives/C04QR0T3G3H/p1707727354930699

### System information

Bugfix coming ;-)

**Comment by apeltzer** [comment]
See https://github.com/nf-core/tools/pull/2755 for fix

**Comment by mashehu** [comment]
fixed in #2755
