### ISSUE TITLE
linting issue with files_exist

### ISSUE THREAD

**Issue by maxulysse** [nf-core/tools#2787]
### Description of the bug

Running nf-core lint on sarek, with `nf-core/tools version 2.13`.

In `Pipeline Tests Ignored`
```
files_exist: File is ignored: .github/workflows/awsfulltest.yml
```

but:
in `Pipeline Test Warnings`

```
files_exist: File not found: .github/workflows/awstest.yml
```

**Comment by mashehu** [comment]
`awstest`!=`awsfulltest`

**Comment by maxulysse** [comment]
nevermind
