### ISSUE TITLE
nf-core modules install --dir seems to not reset the working directory 

### ISSUE THREAD

**Issue by luisas** [nf-core/tools#2796]
### Description of the bug

I am trying to install an nf-core module into a not nf-core pipeline. 

By using the command: 
`nf-core modules install famsa --dir . `

I get the error: 
```
WARNING  Could not find a 'main.nf' or 'nextflow.config' file in '/home/luisasantus/Desktop'                                                                                                               
INFO     The 'modules.json' file is not up to date. Recreating the 'modules.json' file.                                                                                                                    
? Can't find a ./modules directory. Would you like me to create one? [y/n] (y): n
```

I also tried with the absolute path of the directory, same error. 

### Command used and terminal output

```console
nf-core modules install famsa --dir . 

( the current dir . is not the default working directory)
```

### System information

nextflow version 23.10.1.5891
Desktop
Local
Ubuntu 20.04.3 LTS
nf-core/tools version 2.13 - https://nf-co.re
Python 3.10.12

**Comment by pmoris** [comment]
I just tried to replicate this, but everything seemed to work fine for me. Perhaps I've misunderstood the issue though?

---

Using a non-nf-core template pipeline:

```
mkdir new-pipeline && cd new-pipeline && touch main.nf
nf-core modules install zip --dir .
```
Prompts the warning:
```
WARNING  'repository_type' not defined in .nf-core.yml
? Is this repository an nf-core pipeline or a fork of nf-core/modules? (Use arrow keys)
 » Pipeline
   nf-core/modules
```

Selecting pipeline results in a few more messages (asking whether to add a `.nf-core.yml` file and `modules` directory), and then the module appears in the folder as expected.
```

---

Using a nf-core template pipeline (via `nf-core create`) also works as expected.

However, I did notice that when trying to use the `--dir` flag to point to another directory, while the current working directory already contains the module, the installation would be skipped. To fix this, the check to look for already installed modules needs to point to whatever directory is supplied via the `--dir` flag.

**Comment by pmoris** [comment]
No worries, glad you got it resolved! 

Incidently, When I mentioned this on Slack, @awgymer spotted a related bug and managed to fix it! https://github.com/nf-core/tools/pull/2863

**Comment by awgymer** [comment]
Yep that error was the precisely the issue I applied the fix for. It's rare that people have nested config yml but where they did it really messed things up
