### ISSUE TITLE
linting modules/subworkflows - add failure when no snapshots for versions

### ISSUE THREAD

**Issue by maxulysse** [nf-core/tools#2814]
### Description of the bug

the versions of tools is highly reproducible on docker/singularity, but it's often a lottery in conda.
I'd like a linting test that ensure we snapshot for modules, either:
- `process.out.versions`
- `process.out` (only since it contains versions)

 we snapshot for subworkflows either:
- `workflow.out.versions`
- `workflow.out` (only since it contains versions)

**Comment by maxulysse** [comment]
Note:
For subworkflows, we don't always use modules, so only a warning.
For subworkflows, snapshotting versions could be empty in some tests if we skip all the tools from said subworkflow.

**Comment by maxulysse** [comment]
Related PRs:
- https://github.com/nf-core/modules/pull/4828
- https://github.com/nf-core/modules/pull/4831
- https://github.com/nf-core/modules/pull/4925

**Comment by mahesh-panchal** [comment]
Wasn't it an issue for bumping modules since then the snapshot wouldn't match ? If you checked if the output matched a regex, then that should be fine too for autobumping modules?
