### ISSUE TITLE
Support downloading modules from custom locations

### ISSUE THREAD

**Issue by multimeric** [nf-core/tools#2829]
### Description of feature

Currently `nf-core modules install` only works with modules that are located in the `nf-core/modules` repo. However, since nf core modules is the de facto module system for Nextflow generally, I think it would make sense for users to be able to create their own repositories and then have users install modules from there.

For example, I could envisage a new flag for this purpose such as `nf-core modules install --repo myorg/myrepo` where this flag defaults to `nf-core/modules`.

**Comment by mashehu** [comment]
We already do: https://nf-co.re/tools#custom-remote-modules

**Comment by multimeric** [comment]
Thanks, I didn't think to look at the help for the `modules` supercommand!
