### ISSUE TITLE
Template lists URLs that don't exist

### ISSUE THREAD

**Issue by erinyoung** [nf-core/tools#2835]
### Description of the bug

I created a new workflow using nf-core create and this was in the new workflow.nf file:

```
    // TODO: OPTIONAL, you can use nf-validation plugin to create an input channel from the samplesheet with Channel.fromSamplesheet("input")
    // See the documentation https://nextflow-io.github.io/nf-validation/samplesheets/fromSamplesheet/
    // ! There is currently no tooling to help you write a sample sheet schema
    
  ```
    
 `https://nextflow-io.github.io/nf-validation/samplesheets/fromSamplesheet/` does not exist, though. This URL needs to be updated.

**Comment by mashehu** [comment]
Thanks for pointing this out! The correct link should be `https://nextflow-io.github.io/nf-validation/latest/samplesheets/fromSamplesheet` (versioned docs were only added in a recent release)

**Comment by ctuni** [comment]
Just checking: would changing [this line](https://github.com/nextflow-io/nf-validation/blob/922bb6f6c2a34f50562ff02d8d5acc0337bd0369/mkdocs.yml#L4) to `https://nextflow-io.github.io/nf-validation/latest/` solve this issue? I think so right?

**Comment by ctuni** [comment]
I created a PR: https://github.com/nextflow-io/nf-validation/pull/164

**Comment by MatthiasZepper** [comment]
Merged and done. Thanks!
