### ISSUE TITLE
Permission problem running scripts in bin

### ISSUE THREAD

**Issue by orzechoj** [nf-core/tools#289]
I just installed the pipeline with `nf-core download rnaseq --singularity -r 1.2`, and running it I get the following errors:

`......./nf-core-rnaseq-1.2/workflow/bin/markdown_to_html.r: Permission denied`

` ....../nf-core-rnaseq-1.2/workflow/bin/mqc_features_stat.py: Permission denied`

`......./nf-core-rnaseq-1.2/workflow/bin/dupRadar.r: Permission denied`

A simple `chmod a+x ......./nf-core-rnaseq-1.2/workflow/bin/`seems to fix this. I don't know if this is the right place to report this bug, or under https://github.com/nf-core/tools

**Comment by ewels** [comment]
Transferred to `tools` because I think that this is a problem with specifically the `nf-core download` command. Thanks for letting us know!

**Comment by ewels** [comment]
ok, after a little digging it seems that this is a known bug in the Python `zipfile` module: https://bugs.python.org/issue15795 - I'll see if I can fix it by making all downloaded files executable.

**Comment by ewels** [comment]
Fixed in dev 👍
