### ISSUE TITLE
logo generation is inconsistent between github actions runners and local execution

### ISSUE THREAD

**Issue by jmuhlich** [nf-core/tools#2893]
### Description of the bug

`nf-core lint` run locally tells me my logo images don't match the template, but the GitHub Actions lint check passes. If I run `nf-core lint --fix` locally and commit the changes to the logos, the GHA lint check then fails. I examined the difference in the images and it looks like a minor text tracking/kerning issue. The two images and an image diff are attached below. The pipeline I'm working in is https://github.com/nf-core/mcmicro/ .

Image that passes GHA checks:
![gha](https://github.com/nf-core/tools/assets/277154/b410569a-1487-40b1-8af9-f7390f5c4b8f)

Image generated by `--fix` locally:
![local](https://github.com/nf-core/tools/assets/277154/0e500c96-ca0e-422b-9501-c14924f3d77a)

Difference:
![image](https://github.com/nf-core/tools/assets/277154/05f2828d-fb18-4ee8-bbcc-b20c696a7630)

### System information

tools 2.13.1

**Comment by mirpedrol** [comment]
`nf-core lint` is now more permissive when comparing the logos, to allow for these small inconsistencies. 
I am going to close this issue now, but feel free to reopen it if the errors appear again.
