### ISSUE TITLE
Allow pip sub-list in conda's environment.yml

### ISSUE THREAD

**Issue by sven1103** [nf-core/tools#29]
Status: Only conda package dependencies are linted at the moment, sub-list, such as derived from additional `pip`installations are not possible at the moment.

Suggestion: Allow `pip` sub-list for dependency and use the PyPi API 

    http://pypi.python.org/pypi/<package_name>/<version>/json

**Comment by ewels** [comment]
To clarify - they are possible to have, they're just not linted :)

**Comment by sven1103** [comment]
Thanks Phil, I updated the command.
