### ISSUE TITLE
Broken link: schema_params

### ISSUE THREAD

**Issue by HomoPolyethylen** [nf-core/tools#2907]
### Description of the bug

**Describe the bug**
`nf-core lint` returned a failed pipeline test (see screenshot). Clicking the link (schema_params) takes me to a 404 error on nf-co.re
linked address: [https://nf-co.re/tools/docs/2.13.1/pipeline_lint_tests/schema_params](https://nf-co.re/tools/docs/2.13.1/pipeline_lint_tests/schema_params)

**To Reproduce**

1. have parameter `fasta` specified in `nextflow_schema.json`
2. remove default value assignment of `fasta` from `nextflow.config`
3. `nf-core lint`
4. you should receive the error below (screenshot)
5. ctrl+click on [schema_params](https://nf-co.re/tools/docs/2.13.1/pipeline_lint_tests/schema_params)

**Expected behavior**
ctrl+click on error opens detailed error description on nf-co.re webpage.

**Screenshots**
![image](https://github.com/nf-core/website/assets/57624670/67a058cc-fc83-4a62-b43b-c555041bc3a3)

### System information

- OS: Linux/Ubuntu 22
- Browser: Firefox 123.0
- Nextflow 23.10.1
- nf-core/tools 2.13.1

**Comment by mashehu** [comment]
Thanks for pointing this out. It is fixed now.
