### ISSUE TITLE
Centralise common documentation

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#291]
It's too easy for documentation to get duplicated and/or out of date when it's bundled with the pipelines (even with the template sync function). Instead, we should centralise common documentation on the website (installation, singularity, etc etc) and bundle _only_ the pipeline specific docs (command line flags, output etc).

**Comment by apeltzer** [comment]
Yes, please! Already had a bunch of pipelines where I thought this is just copy & pasted and not even up 2 date anymore :-(

**Comment by ewels** [comment]
Made a start on this here: https://github.com/nf-core/nf-co.re/pull/87

**Comment by apeltzer** [comment]
Merged latest PR addressing this - I guess we could polish this further, but for now it seems to be improved already 👍
