### ISSUE TITLE
`nf-core subworkflows test` `--profile` flag doesn't like specifying `docker` or `conda`

### ISSUE THREAD

**Issue by jfy133** [nf-core/tools#2921]
### Description of the bug

```
$ nf-core subworkflows test --profile docker

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.13.1 - https://nf-co.re/


                                                                                                    
 Usage: nf-core subworkflows test [OPTIONS] subworkflow name                                        
                                                                                                    
 Try 'nf-core subworkflows test -h' for help                                                        
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────╮
│ Invalid value for '--profile': 'docker' is not one of 'none', 'singularity'.                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
                                                                       
[10:43](https://nfcore.slack.com/archives/D017F3SUESW/p1713429815891469)



```
$ nf-core modules test --profile docker

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.13.1 - https://nf-co.re/

WARNING  'repository_type' not defined in .nf-core.yml                                                                                                                                                             
? Is this repository an nf-core pipeline or a fork of nf-core/modules? (Use arrow keys)
 » Pipeline
   nf-core/modules
   ```

### Command used and terminal output

_No response_

### System information

_No response_

**Comment by marrip** [comment]
hey, I also tried the gitpod devcontainer for the raredisease pipeline and had some weird issues with running docker - the docker daemon was not running upon container start and needed to be started manually, then permission issues prevented us from running docker without sudo and when we run nextflow it doesn't allow us to use sudo. It would be nice to solve these issues. What is the intended use of the gitpod container, should the user `gitpod` be able to run stuff directly? Is the conda environment supposed to be turned on always?

**Comment by marrip** [comment]
adding the gitpod user to the docker group seems to fix the permissions issue when using docker: `usermod -aG docker gitpod`. Starting the docker daemon could be done in a post-build script when spinning up the container.

**Comment by mirpedrol** [comment]
Done by https://github.com/nf-core/tools/pull/3233
