### ISSUE TITLE
Replace `check_max` with `resourceLimits`

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#2923]
Once https://github.com/nextflow-io/nextflow/pull/2911 is in a stable release (24.04.0) we should update the template + all configs to use `resourceLimits` instead of our custom `check_max` function.

**Comment by jfy133** [comment]
In addition to PR above:

Tools PR: 

- [ ] Remove default `resourceLimit` from base.conf
- [ ] Add default `resourceLimits` to test.conf
- [ ] Add [linting check](https://github.com/nf-core/tools/blob/930ece572bf23b68c7a7c5259e918a878ba6499e/nf_core/lint/nextflow_config.py#L165-L166) for `check_max` , `params.max_*`, 
- [ ] Bump default nextflow version

Website

- [ ] Remove references to `check_max` , `params.max_*`, in docs (replace with warning box that points to troubleshooting to refer to old pipelines)

Configs

- [ ] add  resourceLimits directive to all configs, copying existing `max_` values into them. (but leave  max_params/checkmax for now, but leave comment)
