### ISSUE TITLE
Linting: make click progress bar more granular

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#299]
Currently, the progress bar kind of hangs at two points, which are themselves looping. Would be nice to break up those functions a bit so that the progress bar shows more precise updates.

**Comment by drpatelh** [comment]
Go go `-ansi`!

**Comment by ewels** [comment]
Update - the Rich progress bar that we are now using has pretty nice support for multiple progress bars: https://rich.readthedocs.io/en/latest/progress.html#advanced-usage

Should be possible to pass the `progress` object to the linting functions and allow them to update it however they want (or ignore it). Then we can easily have progress reporting of the nested loops - eg. for conda etc.

**Comment by ewels** [comment]
Done in #831
