### ISSUE TITLE
Manual sync

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#303]
When syncing initially fails after a new release, we'd like to be able to re-issue a sync (maybe also restricting a specific sync for just certain pipelines).

**Comment by ewels** [comment]
Need to think about how / where to trigger this and who should be allowed to do it.

Command line? Website? By calling the @nf-core-bot in an issue? (like [conda-forge does](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-lint)).

My suspicion is that the easiest way to do it would be to build it in to `nf-core tools` somehow. Probably just by a script in the `bin` folder that you supply with the login credentials for the bot account. It's not super user friendly that way, but it would be secure and easy, and I guess the idea is that we shouldn't have to do this manually very often (or ever..)

Phil

**Comment by sven1103** [comment]
Technically it already works :) You can now run the `sync` script via command-line and pass a single pipeline name. If you run the script without any arguments, all pipelines will be synced. #307 

To environment vars need to be set:

1. `TRAVIS_TAG`, representing the Github release build you want to sync
2. `NF_CORE_BOT`, with the bot credentials

Sven

**Comment by apeltzer** [comment]
Thinking the same - just maybe document that in the developer docs for the nf-core team?

**Comment by sven1103** [comment]
Yes, docs are crucial!

**Comment by sven1103** [comment]
nf-core/nf-co.re#105

**Comment by apeltzer** [comment]
Done :)
