### ISSUE TITLE
Download CI erroring since is using development version of tools

### ISSUE THREAD

**Issue by JoseEspinosa** [nf-core/tools#3034]
### Description of the bug

 As shown on [this](https://github.com/nf-core/proteinfold/actions/runs/9660099782/job/26646032772) run, the `download` CI is breaking as the command download has been deprecated on version  `2.14.2.dev0` of tools.
 
Currently, we are using the development version of tools for this test, see [here](https://github.com/nf-core/tools/blob/033eaa074cd3314c206d8dc948de7e830dacfba6/nf_core/pipeline-template/.github/workflows/download_pipeline.yml#L49)

### Command used and terminal output

```console
$ nf-core download

DeprecationWarning: The command 'download' is deprecated.
ERROR    The `nf-core download` command is deprecated. Use `nf-core pipelines   
         download` instead.
```

**Comment by mirpedrol** [comment]
This is solved now by allowing the old commands to work
