### ISSUE TITLE
Non-CLI usage of nf-core download

### ISSUE THREAD

**Issue by seedgeorge** [nf-core/tools#3043]
### Description of feature

Hi there,

Currently the `nf-core download` command doesn't permit a parameter-based answer to to the `Define $NXF_SINGULARITY_CACHEDIR f` question that pops up on the command-line interface. For the purposes of putting this command in a script, it would be handy to not have to interact with a command line prompt at all.

Thanks for the useful tool!

**Comment by MatthiasZepper** [comment]
Sorry for the late reply.

Technically, this should already be the case. The code [has a check that should prevent prompts from being shown in non-interactive sessions](https://github.com/nf-core/tools/blob/930ece572bf23b68c7a7c5259e918a878ba6499e/nf_core/download.py#L441-L443):

```
if (
            self.container_system == "singularity"
            and os.environ.get("NXF_SINGULARITY_CACHEDIR") is None
            and stderr.is_interactive  # Use rich auto-detection of interactive shells
        ):
```

Why this detection fails in your case, I can't tell. Have you tried to pipe the output to `cat` or `tail` or something?At least the pipe should be detected, and any interactive prompts thus turned off.

**Comment by MatthiasZepper** [comment]
I presume that the OP does _not_ want to define a cache directory?
