### ISSUE TITLE
nf-core create fails on 2.14.2.dev0

### ISSUE THREAD

**Issue by SPPearce** [nf-core/tools#3068]
### Description of the bug

Running nf-core create gives an error message on 2.14.2.dev0 (current gitpod version in the modules repo)

### Command used and terminal output

The output is truncated in the gitpod terminal window, so can't see what the other arguments are.
```console
nf-core create

│ /opt/conda/lib/python3.12/site-packages/nf_core/__main__.py:2172 in command_create               
│ ❱ 2172 │   pipelines_create(ctx, name, description, author, version, force, outdir, template_ya  
TypeError: pipelines_create() takes 9 positional arguments but 10 were given
```

### System information

Gitpod, v2.14.2.dev0

**Comment by LaurenceKuhl** [comment]
Fixed by https://github.com/nf-core/tools/pull/3074
