### ISSUE TITLE
Move --migrate-pytest command to `module test` command group

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/tools#3082]
### Description of feature

Can we move the subcommand `--migrate_pytest` over to `modules test` since  we do the migration of a test of a module that already exists? 
The current structure keeps confusing me and I keep asking where to find it 🙈 Evidently I am not the only one: https://nfcore.slack.com/archives/CE5LG7WMB/p1721772232625089?thread_ts=1721764513.813359&cid=CE5LG7WMB

**Comment by edmundmiller** [comment]
I'm still not sure where it was before 😆

**Comment by mashehu** [comment]
`nf-core modules/subworkflows create --migrate_pytest`

**Comment by mirpedrol** [comment]
Done with #3085
