### ISSUE TITLE
Add process_high_memory to create/lint list

### ISSUE THREAD

**Issue by GallVp** [nf-core/tools#3086]
### Description of feature

Currently `nf-core modules lint` produces a warning for `process_high_memory`  label which is part of the template. The warning should be removed.

https://github.com/nf-core/tools/blob/930ece572bf23b68c7a7c5259e918a878ba6499e/nf_core/pipeline-template/conf/base.config#L52

**Comment by mirpedrol** [comment]
Done by https://github.com/nf-core/tools/pull/3087
