### ISSUE TITLE
Add citation guidelines to template

### ISSUE THREAD

**Issue by KochTobi** [nf-core/tools#312]
Add a guide on how to cite the pipeline to the template documentation.

**Comment by drpatelh** [comment]
Quoting @apeltzer from Slack whilst its fresh!

 "Dependencies should list citations if possible, pipeline itself should have a Zenodo DOI upon release (or directly after, badge can be added for all of them once we do that)"

**Comment by ewels** [comment]
x-ref: https://github.com/nf-core/tools/issues/236

**Comment by ewels** [comment]
x-ref #361 #365

**Comment by ewels** [comment]
Coming back to this - where exactly do you mean? What is the template documentation?

* This is already mentioned in the `README` generated by the template.
* The [website](https://nf-co.re/developers/adding_pipelines#release-checklist) already describes the process for creating Zenodo DOIs for the pipeline

I'm not really sure what else there is.. Maybe this one is already fixed?

**Comment by drpatelh** [comment]
Yeah. I think this is fixed too :+1:
