### ISSUE TITLE
what is 'getGenomeAttribute' and how can we use igenomes without it?

### ISSUE THREAD

**Issue by stevekm** [nf-core/tools#3146]
Throughout the main.nf, there are these lines that look like this

https://github.com/nf-core/sarek/blob/e92242ead3dff8e24e13adbbd81bfbc0b6862e4c/main.nf#L29-L31

```nextflow 
params.ascat_alleles           = getGenomeAttribute('ascat_alleles')
params.ascat_genome            = getGenomeAttribute('ascat_genome')
params.ascat_loci              = getGenomeAttribute('ascat_loci')
params.ascat_loci_gc           = getGenomeAttribute('ascat_loci_gc')

```

It seems that this is retrieving values from the igenomes.config ; https://github.com/nf-core/sarek/blob/e92242ead3dff8e24e13adbbd81bfbc0b6862e4c/conf/igenomes.config

However this method `getGenomeAttribute` does not seem to exist anywhere in the pipeline codebase. Its not clear what it does or how it works. 

I am hoping to use the igenomes.config file shown here in my other pipelines, however, it appears to be non-funcitonal without the use of this special magic mystery function. Moreso, it also appears like its only possible to use this special function in the pipeline's main.nf. I want to use igenomes.config as shown, however, I want all `params` to be set in the nextflow.config files, **not** the main.nf. This is really important because we plan to use the pipelines across different environments which will require different configs, and these configs should be external to the pipeline's main.nf code.

Is there a way available here to use the igenomes.config file without using this function `getGenomeAttribute` whose provenance or behavior or source is not clear? How can we instead have all the reference files for the pipeline set properly from inside the nextflow config files instead?

@ewels might also have some insight or thoughts about this

thanks!

**Comment by ewels** [comment]
Transferred to the tools repo from Sarek, as this is a general feature of nf-core that's in the template and not something specific to Sarek.

On mobile currently, will reply when I get to a keyboard.

**Comment by FriederikeHanssen** [comment]
Hey @stevekm, the function is specified here: https://github.com/nf-core/sarek/blob/e92242ead3dff8e24e13adbbd81bfbc0b6862e4c/main.nf#L368

**Comment by stevekm** [comment]
Thanks! The context for this, is that I am trying to figure out how we can use the `igenomes.config` files that I have seen in these various nf-core pipelines, but with our custom internal pipelines instead. The requirement that you need to add all this extra code to the `main.nf` is making it difficult, since I want to make as few changes to the pipelines' .nf files as possible. When I first started looking at the `igenomes.config` I was under the mistaken impression that it was a stand-alone Nextflow config that we might be able to just drop in and use in our non-nf-core pre-existing custom pipelines.

**Comment by FriederikeHanssen** [comment]
Would it be possible to add the function into a `lib` directory instead and just import it from there?

**Comment by stevekm** [comment]
we are trying to deprecate the usage of `lib` 
in general I am trying to push as much generic stuff into the Nextflow.config files as possible because its much much easier to manage these independently of the pipelines, for example Nextflow Tower / Seqera Platform and `tw` along with Nextflow itself all support methods for adding extra config files to pipelines. So I want to keep leveraging this to avoid forcing e.g. all internally developed pipelines to undergo extensive code changes and code reviews every time we adjust non-pipeline-specific things like "what is the path to the refernce genome files on this AWS environment" and similar.

**Comment by FriederikeHanssen** [comment]
Are you looking to keep the genome keys functional, i.e., `nextflow run nf-core/sarek --genome GRCh38` so that, for example, the fasta can be assigned based on the overall genome?

**Comment by stevekm** [comment]
Not entirely sure. Mostly was just trying to leverage igenomes in a way that we could apply easily to other pipelines with minimal changes to the pipelines. The genome keys seem convenient but I am not sure how complicate it would be to actually implement them without having to change every pipeline's `main.nf` with extra custom logic

**Comment by FriederikeHanssen** [comment]
I am intrigued and tried out something [here](https://github.com/FriederikeHanssen/testigenomes/pull/1/files): 

this currently prints:

```
nextflow run . -profile test,docker --outdir results/ --genome GRCh38

[:]/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa
```

so I think _almost_ what you need, except that the igenomes_base is not properly resolved yet?

**Comment by ewels** [comment]
I don't think you need that function, it's just for convenience.

If you go back a bunch of versions you should see us using the same config files but with different parameter parsing.

Note that iGenomes are super outdated - see https://nf-co.re/docs/usage/reference_genomes - we're working on a replacement at the moment. It'll be a project at the Barcelona hackathon if you're interested.

**Comment by stevekm** [comment]
Thanks all! I will look at these and open a new correspondence if further help is needed.
