### ISSUE TITLE
Add logo to email template

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#316]
A few pipelines have now followed suit with `nf-core/rnaseq` to include the pipeline logo in the completion email. It would be nice to add this to the template. 

Small changes would be required to the `email_template.*` files in the assets directory. The creation of the logo itself is a standalone process at the moment. Either it's kept that way and placed in `assets/` with the appropriate name or its somehow generated with `nf-core create`. Not sure how difficult the latter will be because custom fonts are required to be installed.

**Comment by ewels** [comment]
We talked about making it part of `nf-core create` for a while now. That would be best. Now that we have a docker image, I guess we can check if the host system has docker or singularity installed and running and create it if so..?
