### ISSUE TITLE
Singularity container symlinks not consistently created

### ISSUE THREAD

**Issue by muffato** [nf-core/tools#3162]
### Description of the bug

(discussed on [Slack](https://nfcore.slack.com/archives/CE5LG7WMB/p1725620006008199))

Example with
```
nf-core pipelines download nf-core/fetchngs --revision 1.11.0 --download-configuration --compress none --container-system singularity --container-cache-utilisation copy
```

1. If `NXF_SINGULARITY_CACHEDIR` is not set, symlinks are always created in the download directory after download ([L1352](https://github.com/nf-core/tools/blob/dev/nf_core/pipelines/download.py#L1352) and [L1463](https://github.com/nf-core/tools/blob/dev/nf_core/pipelines/download.py#L1463): in [both](https://github.com/nf-core/tools/blob/dev/nf_core/pipelines/download.py#L1312) [cases](https://github.com/nf-core/tools/blob/dev/nf_core/pipelines/download.py#L1386), `output_path` is set to `out_path` because `cache_path` is not set)
2. If `NXF_SINGULARITY_CACHEDIR` is set, symlinks are created in the download directory only if the container is copied from the cache. Otherwise, symlinks are only created in the cache directory (still [L1352](https://github.com/nf-core/tools/blob/dev/nf_core/pipelines/download.py#L1352) and [L1463](https://github.com/nf-core/tools/blob/dev/nf_core/pipelines/download.py#L1463) but this time, `output_path` is set to `cache_path`).

For instance, if `NXF_SINGULARITY_CACHEDIR` is set and complete, I get files + symlinks under `nf-core-fetchngs_1.11.0/singularity-images/`
```
depot.galaxyproject.org-singularity-mulled-v2-5f89fe0cd045cb1d615630b9261a1d17943a9b6a-2f4a4c900edd6801ff0068c2b3048b4459d119eb-0.img -> ./singularity-mulled-v2-5f89fe0cd045cb1d615630b9261a1d17943a9b6a-2f4a4c900edd6801ff0068c2b3048b4459d119eb-0.img
depot.galaxyproject.org-singularity-python-3.9--1.img -> ./singularity-python-3.9--1.img
depot.galaxyproject.org-singularity-sra-tools-2.11.0--pl5321ha49a11a_3.img -> ./singularity-sra-tools-2.11.0--pl5321ha49a11a_3.img
depot.galaxyproject.org-singularity-sra-tools-3.0.8--h9f5acd7_0.img -> ./singularity-sra-tools-3.0.8--h9f5acd7_0.img
depot.galaxyproject.org-singularity-synapseclient-2.7.1--pyh7cba7a3_0.img -> ./singularity-synapseclient-2.7.1--pyh7cba7a3_0.img
depot.galaxyproject.org-singularity-ubuntu-20.04.img -> ./singularity-ubuntu-20.04.img
quay.io-singularity-mulled-v2-5f89fe0cd045cb1d615630b9261a1d17943a9b6a-2f4a4c900edd6801ff0068c2b3048b4459d119eb-0.img -> ./singularity-mulled-v2-5f89fe0cd045cb1d615630b9261a1d17943a9b6a-2f4a4c900edd6801ff0068c2b3048b4459d119eb-0.img
quay.io-singularity-python-3.9--1.img -> ./singularity-python-3.9--1.img
quay.io-singularity-sra-tools-2.11.0--pl5321ha49a11a_3.img -> ./singularity-sra-tools-2.11.0--pl5321ha49a11a_3.img
quay.io-singularity-sra-tools-3.0.8--h9f5acd7_0.img -> ./singularity-sra-tools-3.0.8--h9f5acd7_0.img
quay.io-singularity-synapseclient-2.7.1--pyh7cba7a3_0.img -> ./singularity-synapseclient-2.7.1--pyh7cba7a3_0.img
quay.io-singularity-ubuntu-20.04.img -> ./singularity-ubuntu-20.04.img

singularity-mulled-v2-5f89fe0cd045cb1d615630b9261a1d17943a9b6a-2f4a4c900edd6801ff0068c2b3048b4459d119eb-0.img
singularity-python-3.9--1.img
singularity-sra-tools-2.11.0--pl5321ha49a11a_3.img
singularity-sra-tools-3.0.8--h9f5acd7_0.img
singularity-synapseclient-2.7.1--pyh7cba7a3_0.img
singularity-ubuntu-20.04.img
```
On the other hand, If `NXF_SINGULARITY_CACHEDIR` is set but empty, the cache has the files and the symlinks as above, but I get only files under `nf-core-fetchngs_1.11.0/singularity-images/`
```
$ ls nf-core-fetchngs_1.11.0/singularity-images/ 
singularity-mulled-v2-5f89fe0cd045cb1d615630b9261a1d17943a9b6a-2f4a4c900edd6801ff0068c2b3048b4459d119eb-0.img
singularity-python-3.9--1.img
singularity-sra-tools-2.11.0--pl5321ha49a11a_3.img
singularity-sra-tools-3.0.8--h9f5acd7_0.img
singularity-synapseclient-2.7.1--pyh7cba7a3_0.img
singularity-ubuntu-20.04.img
```

### Command used and terminal output

```console
nf-core pipelines download nf-core/fetchngs --revision 1.11.0 --download-configuration --compress none --container-system singularity --container-cache-utilisation copy
```

### System information

Tested on tools v2.14.1 and dev

**Comment by MatthiasZepper** [comment]
Thanks a lot for reporting the bug. This should have been fixed with commit [b79525b](https://github.com/nf-core/tools/commit/b79525bb0d5e203575cea6e385df062ad70a18fd) that has already been merged to main.
