### ISSUE TITLE
Remove `for` loops from the pipeline template

### ISSUE THREAD

**Issue by bentsherman** [nf-core/tools#3183]
`for` and `while` loops will not be supported in the strict parser that is on the way. Looks like #3166 addresses one of them, here are a few more.

In `workflowCitation()`:
```groovy
    // old
    for (String doi_ref: manifest_doi)
        temp_doi_ref += "  https://doi.org/${doi_ref.replace('https://doi.org/', '').replace(' ', '')}\n"

    // new
    manifest_doi.each { doi_ref ->
        temp_doi_ref += "  https://doi.org/${doi_ref.replace('https://doi.org/', '').replace(' ', '')}\n"
    }
```

I believe the other for loops in `utils_nfcore_pipeline` can be addressed in a similar way.

The one in `checkCondaChannels()` is a bit trickier because it's not just iterating through a list:
```groovy
    def n = required_channels_in_order.size()
    for (int i = 0; i < n - 1; i++) {
        channel_priority_violation |= !(channels.indexOf(required_channels_in_order[i]) < channels.indexOf(required_channels_in_order[i+1]))
    }
```

I believe the intent is to make sure that the required channels are in the right order while also allowing other channels to be in the list. Here is a "groovier" 😉 way to do it:
```groovy
    def channel_priority_violation = required_channels_in_order != channels.findAll { ch -> ch in required_channels_in_order }
```

**Comment by mirpedrol** [comment]
Hi, this was fixed by @nvnieuwk, the current code looks like this:

```
manifest_doi.each { doi_ref ->
        temp_doi_ref += "  https://doi.org/${doi_ref.replace('https://doi.org/', '').replace(' ', '')}\n"
    }
```
and
```
required_channels_in_order.eachWithIndex { channel, index ->
        if (index < required_channels_in_order.size() - 1) {
            channel_priority_violation |= !(channels.indexOf(channel) < channels.indexOf(required_channels_in_order[index+1]))
        }
    }
```

Does this look ok?

**Comment by bentsherman** [comment]
Looks fine to me! Just don't forget the other for loops in `utils_nfcore_pipeline`, there were several more that I didn't list

**Comment by mirpedrol** [comment]
Done with https://github.com/nf-core/tools/pull/3166, thanks!
