### ISSUE TITLE
Investigate easing pain of v3 template sync

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#3187]
Look into whether there's any magic that we can do to try to automate updates in the v3 release of the template.

* nf-schema migration ([docs](https://nextflow-io.github.io/nf-schema/latest/migration_guide/))
* Code to stack a commit onto the automated sync PRs?

**Comment by mashehu** [comment]
Things a possible script could do:
- run `sed -i -e 's/https?:\/\/json-schema.org\/draft-07\/schema/https:\/\/json-schema.org\/draft\/2020-12\/schema/g' -e 's/definitions/$defs/g' nextflow_schema.json`
- check for fastqc and multiqc in modules.json and if not present add them to the skip_features (for this to work extra well we would then need to run the sync command a second time)

**Comment by mirpedrol** [comment]
> check for fastqc and multiqc in modules.json and if not present add them to the skip_features

We could always skip them, to avoid merge conflicts as we update the modules in the template. Then pipeline devs would have to update the modules manually if they want to.

**Comment by mirpedrol** [comment]
done 🎉
