### ISSUE TITLE
Nose2 does not execute tests with correct Python environment during CI build

### ISSUE THREAD

**Issue by sven1103** [nf-core/tools#32]
Description: Although the Python environment is loaded correctly during the CI build, it seems that `nose2` is running tests under the loaded Python environment, but Python 2.7.

So we are missing Syntax errors during CI testing, which only occur in specific Python versions.

Suggestion: Call `nose2` as module in the loaded Python environment with `python -m nose2 ...`

**Comment by ewels** [comment]
Any reason we're using `nose2` versus other testing packages? This statement leaves me a little worried on their [docs homepage](http://nose2.readthedocs.io/en/latest/):

> However, given the current climate, with much more interest accruing around [pytest](http://pytest.readthedocs.io/en/latest/), `nose2` is prioritizing bugfixes and maintenance ahead of new feature development.

**Comment by sven1103** [comment]
Fixed in #35
