### ISSUE TITLE
Remove defaults conda channel from pipeline template

### ISSUE THREAD

**Issue by ktmeaton** [nf-core/tools#3241]
Hi nf-core team,

Would you consider removing the `defaults` conda channel from the pipeline template? Use of the `defaults` channel requires a paid commerical license for large organizations such as research institutes and government laboratories. To be honest I'm still trying to understand exactly what the new TOS clarifications mean:

- Anaconda TOS: https://legal.anaconda.com/policies/en/
- TOS Update: https://www.anaconda.com/blog/update-on-anacondas-terms-of-service-for-academia-and-research

![Image](https://github.com/user-attachments/assets/96352187-ef45-4b68-b65c-356a14a2acff)

https://github.com/nf-core/tools/blob/1e32f09cc3f1fcc2f56fbec15f25d2e2b0524ef0/nf_core/pipeline-template/nextflow.config#L100

Curious to hear your opinions on this matter!

Katherine

**Comment by mashehu** [comment]
This has been done in https://github.com/nf-core/tools/pull/3029

**Comment by ktmeaton** [comment]
Apologies for the duplicate post, thank you for clarifying!

**Comment by mashehu** [comment]
No worries, thanks for pointing it out!
