### ISSUE TITLE
Optical issue with NXF ansi 

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#329]
Hi everyone,

just found out that the new and now default `ansi` Nextflow log seems to malform our colored output on the console a bit:

<img width="695" alt="Bildschirmfoto 2019-05-04 um 23 33 37" src="https://user-images.githubusercontent.com/2359510/57185045-23380f80-6ec5-11e9-8ab3-56f3a8651735.png">

Running the same nextflow version with `-ansi-log false` gives this:

<img width="807" alt="Bildschirmfoto 2019-05-04 um 23 33 16" src="https://user-images.githubusercontent.com/2359510/57185050-38ad3980-6ec5-11e9-88d4-c66dbf7f5c5a.png">

(as we wanted it).

I just wanted to make that behavior documented here, to give @pditommaso some feedback 👍 

(similar behavior when working with the `rnaseq`, `eager` etc pipelines - seems to be something introduced with Nextflow 19.04.X)

**Comment by apeltzer** [comment]
I'm talking about the `2m[` created by parts of this template snippet here:

https://github.com/nf-core/tools/blob/4ab80b83cd8b6562a88bb38b6aa0a3d082fd4de6/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/main.nf#L154

**Comment by drpatelh** [comment]
https://github.com/nextflow-io/nextflow/issues/1129

Hopefully, it's just a case of updating the template with another ANSI code.

**Comment by apeltzer** [comment]
I guess its just that yes 👍

**Comment by apeltzer** [comment]
Although the stated ones are actually correct: 
https://devhints.io/ansi

**Comment by phue** [comment]
It seems that the the first character in the multi line String is the ${c_dim} variable, that is not properly escaped for some reason.

The simplest 'fix' probably is to either remove c_dim from the first line or insert a newline before.

**Comment by pditommaso** [comment]
I think it gets messed up with the library used by NF to render the ansi code. 

https://github.com/nextflow-io/nextflow/blob/95f4dd7bddd30087b7d17571364c881d2e1e161a/modules/nextflow/src/main/groovy/nextflow/trace/AnsiLogObserver.groovy#L258-L266

Likely it escapes the ANSI code because it's not expecting it ..

**Comment by ewels** [comment]
Can / should we use the same library instead of hardcoding the colour codes?

**Comment by apeltzer** [comment]
That would be ideal if this is possible :+1:
