### ISSUE TITLE
Cleanup needed for nf-core logo / monochrome logs.

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#3295]
Started looking into warnings for https://github.com/nf-core/tools/issues/3294 and saw one about `monochrome_logs` being unused here:

https://github.com/nf-core/tools/blob/41b4516e1b5dedca816749ca2a0019254cab4831/nf_core/pipeline-template/subworkflows/local/utils_nfcore_pipeline_pipeline/main.nf#L35

This seems to be a leftover from before we moved to nf-schema to print the header. The nf-core utils subworkflow no longer does this, so no longer needs the `monochrome_logs` option to be passed to it.

The more I started looking into it, the more I think that there is a bit of cleanup needed here.

* nf-schema has a [configuration option](https://nextflow-io.github.io/nf-schema/latest/configuration/configuration/#monochromelogs) called `validation.monochromeLogs`
    * We're not setting this currently, we probably should - set to `params.monochrome_logs`
* We have `def nfCoreLogo` in the [nf-core subworkflow](https://github.com/nf-core/modules/blob/d40d060ee67b7da7567eb0ecf2149df6d7b8f1f1/subworkflows/nf-core/utils_nfcore_pipeline/main.nf#L153-L170) which is, as far as I'm aware, not used anywhere
* Pretty sure that the [`dashedLine` function](https://github.com/nf-core/modules/blob/d40d060ee67b7da7567eb0ecf2149df6d7b8f1f1/subworkflows/nf-core/utils_nfcore_pipeline/main.nf#L172-L178) is only used by `nfCoreLogo`, so can also be deleted.
* The `nextflow.config` [hardcodes the logo](https://github.com/nf-core/tools/blob/41b4516e1b5dedca816749ca2a0019254cab4831/nf_core/pipeline-template/nextflow.config#L295-L304) (not using the above function), with ANSI colours hardcoded. So there is no way to disable colours.

As a minimum we need to remove the unused input from the subworkflow to help solve https://github.com/nf-core/tools/issues/3294 - but we should also try to clean up this 👆🏻 so that:
* `--monochrome_logs` makes the nf-core logo monochrome
* There is minimal code duplication / orphaned unused code

**Comment by ewels** [comment]
Unresolved - how to fix this:

https://github.com/nf-core/tools/blob/41b4516e1b5dedca816749ca2a0019254cab4831/nf_core/pipeline-template/nextflow.config#L252-L255

We're not allowed `def` in `nextflow.config` any more.

We originally added it years ago to avoid filename clashes, but that's [no longer needed](https://github.com/nextflow-io/nextflow/issues/3186). However, I'm not sure how to set the report directories to `"${params.outdir}/pipeline_info/` without _also_ specifying the report filename. And if I specify the report filename I don't know how to include the timestamp :melting_face:

So we need to either:
* Somehow specify the report directory and leave the default Nextflow filename (not possible?)
* Refactor the above code to give the entire file path, including a timestamp

**Comment by mirpedrol** [comment]
using `validation.monochromeLogs` will remove the colours from the logo we have hard coded in `validation.beforeText`. See the nf-schema [code here](https://github.com/nextflow-io/nf-schema/blob/51069b947cf1e63ad3f0a9a0c85bbe44bb67379e/plugins/nf-schema/src/main/nextflow/validation/config/HelpConfig.groovy#L35-L38).
But it doesn't work when setting `validation.monochromeLogs = params.monochrome_logs`. This looks like one of the Nextflow particularities when overriding params 🤔 do you have an idea why this could be happening?
