### ISSUE TITLE
create seems that utf8 is not supported

### ISSUE THREAD

**Issue by Liripo** [nf-core/tools#3355]
### Description of the bug

I used the following commands, the first one can be created, the second one cannot be created.
```bash
nf-core pipelines create -n scrna -d 'test' -a 'test' --force
```

```bash
nf-core pipelines create -n scrna -d '测试' -a 'test' --force
```

### Command used and terminal output

```console
$ nf-core pipelines create -n scrna -d '测试' -a 'test' --force

RuntimeError: Command 'nextflow config -flat /data01/liaorenpeng/work/20241212-nextflow-scrna/nf-core-scrna' returned non-zero error code '1':
[red]> ERROR ~ Unable to parse config file: '/data01/liaorenpeng/work/20241212-nextflow-scrna/nf-core-scrna/nextflow.config'

  Cannot read config file include: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config
```

**Comment by mirpedrol** [comment]
Hi @Liripo, 
thank you for reporting this. The failing command is `nextflow config` which we use to parse the config file. Since this seems to be a Nextflow error, would you mind opening a post in the [Seqera Community](https://community.seqera.io/)? Thanks!

**Comment by Liripo** [comment]
Thanks for the quick reply, I posted it.
https://community.seqera.io/t/nf-core-create-seems-that-utf8-is-not-supported/1550
