### ISSUE TITLE
[Feature] Release Checklist

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#355]
We should have a release checklist whenever someone intends to do a release for a pipeline - especially when doing this for one of the bigger pipelines (e.g. rnaseq, sarek).

That would help also beginners in helping with making the release happen - could organize that with milestones but maybe should have a document on the webpage or here in the template @nf-core/core what are your thoughts on this?

**Comment by ewels** [comment]
Good idea - easiest as a web page I think?

**Comment by apeltzer** [comment]
I think that should be on a webpage yes! Maybe in the general documentation?

**Comment by apeltzer** [comment]
Done on the webpage for now!
