### ISSUE TITLE
manifestHomepage is not correctly linted

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#36]
When `nextflow.config` contains this:

``` 

manifest {
  homePage = '{{ cookiecutter.pipeline_url }}'
  description = '{{ cookiecutter.pipeline_short_description }}'
  mainScript = 'main.nf'
}
```
The linting fails unfortunately. This is a problem in cookiecutter, see ticket https://github.com/nf-core/cookiecutter/pull/19 for a start.

**Comment by apeltzer** [comment]
It wasn't the linting, it was a bug in the JSON description .

**Comment by sven1103** [comment]
:sunglasses:
