### ISSUE TITLE
"required" field in parameters schema

### ISSUE THREAD

**Issue by anton-khodak** [nf-core/tools#360]
In the current version of `parameter.schema.json` there is no way to explicitly mark a parameter as required or optional. This field has been removed at some point: https://github.com/nf-core/nf-co.re/commit/e21e36936c20ed8724aca231b0cf922584c11548#diff-c5b07ba81efd37851d296bbcd0043936 , but I would like to raise a discussion about putting it back. This property probably could be devised from the `pattern` field, but I find it much more intuitive to have a separate field indicating that. 

A simple use case for the property itself: a workflow that processes one sample needs to have `sample_id` field marked as required so that if it's not provided, it can be failed by the downstream app on the input validation step, not on the pipeline execution step, for example.

**Comment by sven1103** [comment]
Thank you @anton-khodak for bringing this up again! 

I agree, there are use cases where this field is valuable. Especially when you define paths for input files as parameters. A default value does not help much here.

I will put it back in for know, does not hurt anyway.
