### ISSUE TITLE
Allow for pipeline success or failure dependent email recipients

### ISSUE THREAD

**Issue by csawye01** [nf-core/tools#364]
Ability to send a pipeline's completion email to specific recipient(s) if the pipeline completes successfully and different recipient(s) if the pipeline fails.

**Comment by ewels** [comment]
Typical use case here would be to only notify a user if something fails, when running a lot of pipelines in an automated fashion. Will need extra `params` options, but should be fairly easy to add - just need a bit of extra logic here:
https://github.com/nf-core/tools/blob/4ab80b83cd8b6562a88bb38b6aa0a3d082fd4de6/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/main.nf#L341-L353

**Comment by ewels** [comment]
Implemented in https://github.com/nf-core/tools/pull/401
