### ISSUE TITLE
Remove Dockerfile requirement from linting

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#367]
For pipelines which are entirely dependent on `Docker` containers from external sources e.g. `biocontainers` it isnt necessary to have a `Dockerfile` in the pipeline repository. The lint tests will have to be adjusted to maybe just provide a warning in its absence as it currently done for `environment.yml`

`nf-core/imcyto` is an example of such a pipeline.

```
ERROR: Test Failures:
  http://nf-co.re/errors#1: File not found: ['Dockerfile']
```

**Comment by sven1103** [comment]
We then have to make sure, that the pipeline indeed references a valid Docker container.

Scenario 1:

Developer provides own Dockerfile for container definition in the nf-core pipeline repo. And he referenced the container ressource in the `process.container` parameter.  

Here the linting should fail, when the developer forgot to provide the Dockerfile.

Scenario 2:
Developer uses biocontainers. And he referenced the container ressource in the `process.container` parameter.  

Linting should fail, if the container slug does not represent a valid container resource.  
No local Dockerfile necessary.

Currently, we fail if the Dockerfile is not present and raise a warning, if the `process.container` parameter is not set.

**Comment by drpatelh** [comment]
**Scenario 1**
Agreed

**Scenario 2**
In the absence of a `Dockerfile` the most obvious and transparent place to put the container path is within the process definition e.g.
https://github.com/nf-core/imcyto/blob/aa0def2070a8208f8ae1460712198cd4da099ccc/main.nf#L186

Can we extend the linting to check `main.nf` instead of `nextflow.config` for a `container` definition (in one or more processes) if the `Dockerfile` is absent?

**Comment by drpatelh** [comment]
May need to think about where to look for container definitions when we implement `DSL2` too which will likely be a further extension of the "one process > one container" model. I would have thought `container` would be defined within the module file process, with the possibility of being overwritten using a `params` variable.

**Comment by sven1103** [comment]
hm, would be cool if Nextflow could output the process containers with `nextflow config` command?

**Comment by MaxUlysse** [comment]
Don't we already have that info in the `execution_report.html`?

**Comment by drpatelh** [comment]
@MaxUlysse These limiting checks would have to be performed on the pipeline repo before execution and so this file wouldn't exist at that point.

**Comment by MaxUlysse** [comment]
I see, then, yes, we could definitively get these info from the `nexflow config` command, but the output could be more complicated given the pipelines.
ie: sarek
```
> nextflow config | grep container
container = 'nfcore/sarek:dev'
container = {(params.annotation_cache && params.snpEff_cache) ? 'nfcore/sarek:dev' : "nfcore/sareksnpeff:dev.${params.genome}"}
container = {(params.annotation_cache && params.vep_cache) ? 'nfcore/sarek:dev' : "nfcore/sarekvep:dev.${params.genome}"}
```

**Comment by MaxUlysse** [comment]
But we could still definitively check if there's at least one container declaration.

**Comment by ewels** [comment]
Hold your horses here chaps, a few points to consider here:

1. Let's not rush to change the linting for modules yet, until we have a very clear idea on what we think the new best practices should be
    * biocontainers are great, but we need a proper strategy. Are we just going to leave conda users out in the cold now? Are we going to allow any docker image from anywhere, or only trusted sources? Are we going to insist on certain versioning systems? Lots of questions..
    * For now, insisting on our current strategy solves all of these problems by having one method. I'm not unhappy with this system.
    * We may well have to move to a guidelines version 2.0 for modules, as a lot of stuff is going to be different. This will cover a lot of stuff in the linting.
2. Per-process containers are probably coming, but they do not  and _should not_ be in `main.nf`. These can go in `base.config` like any other process-specific information.
    * If they're here instead of in `main.nf` then (a) they can be overwritten more easily and (b) will show up with the `nextflow config` command. If they're in `main.nf` then they are ignored by this command (see https://github.com/nextflow-io/nextflow/issues/876)
    * If they do show up with `nextflow config`, then linting is still pretty trivial - if they are a simple string. Complicated closures like @MaxUlysse suggested do give odd outputs though. So we need a strategy for this too.

These kinds of issues are part of why I've not been rushing to use per-process and external containers. If you're writing a workflow then these things make life easier for you, but if you're trying to homogenise and test a group of pipelines it complicates everything. Also, only providing software packaging for docker / singularity users is a fairly major issue I think.

Plenty of problems and not many solutions for now sorry, just jotting down my thoughts quickly!

Phil

**Comment by ewels** [comment]
Quick update after re-reading this - I basically think it's going to be impossible to lint for this until `nextflow config` parses the main pipeline, and not just the pipeline config. This likely isn't going to happen any time soon.

I think that the only thing that we _can_ do for now is to downgrade the fail to a warn (even this is a bit confusing, as we actually want to push people in this direction).

Phil

**Comment by drpatelh** [comment]
Warning is fine because at least it means we don't need to have a `Dockerfile` in the repo that isn't doing anything which could lead to even more confusion 😅

**Comment by drpatelh** [comment]
Thanks guys! 😍
