### ISSUE TITLE
Increase default time limit in template base.config

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#370]
As discussed on Slack with @ewels and @MaxUlysse it may be useful to increase the default time limit (currently 2 hours) in the template. The number we choose is still up for discussion. 

I suggested that increasing it too much may affect job queuing on some systems that use "wall time" to allocate jobs. The Slurm cluster we have at the Crick does this. This will just mean you have to wait longer for a job to be submitted but the upside is that its less like to fail.

**Comment by ewels** [comment]
Yeah, we’re the same. But I doubt that pushing it from 2 hours to 4 hours will make much difference to queueing..? I think that the intention was to default to small fast tasks and assume that pipeline authors would customise for anything else. But negligible impact for minor changes, so I’m keen to push it to 4ish hours (or even 8?)

**Comment by alneberg** [comment]
Sounds good to me as well. It's a bigger hassle if the job is crashing/restarting than waiting a bit longer in the queue.

**Comment by apeltzer** [comment]
This has been addressed now 👍
