### ISSUE TITLE
Remove `params.singleEnd` from the expected parameters during linting

### ISSUE THREAD

**Issue by sven1103** [nf-core/tools#380]
Hi all, 

feedback from the nf-core hands-on session from @aunderwo (thanks!).

`nf-core lint` raises a warning, if the `params.singleEnd` is not set in the pipeline. I think we can remove this requirement from the hardcoded list of parameters, as this is strongly bound to the NGS domain and should not be a basic nf-core required parameter.

https://github.com/nf-core/tools/blob/c34b04bf8039de39c3fd8a41a75cdaf2dbfc90ae/nf_core/lint.py#L354

Any thoughts?

best, Sven

**Comment by MaxUlysse** [comment]
I'm all for it, I would also add `--input` as an alternative for `--reads`

**Comment by ewels** [comment]
Yeah, we should probably make these more general. If we switch to `--input` then we should add a test to make sure that pipelines _don't_ have `--reads` any more, so that all are consistent.

Phil

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/tools/pull/556
