### ISSUE TITLE
Optional linting config file

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#389]
I've been thinking that we should allow an optional config file for the nf-core linting, as we do with the [markdown linting](https://github.com/nf-core/tools/blob/master/.github/markdownlint.yml) (and is common practice). Then we can be pretty relaxed about adding lots of warnings about common usage, but pipeline authors can switch these off for their pipelines if there's a good reason not to have them.

We could potentially make it possible to only turn off warnings, and not failures?

**Comment by apeltzer** [comment]
Yes, I like the idea to make things a bit more configurable. Should probably then also have a set of absolutely required ones but some optional ones that can be freely configured by pipeline authors?

**Comment by ewels** [comment]
Yeah, that's kind of what I was thinking about with warnings / failures. Failures should already be absolutely required only...

**Comment by ewels** [comment]
Now covered by #805 in more detail, so will close this issue.
