### ISSUE TITLE
Switch from Travis to GitHub Actions for CI

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#396]
It should be possible to have multiple ways of testing for the pipeline(s):

- legacy TravisCI testing as we used to have it (everything in one script section)
- matrix TravisCI testing as e.g. the `nf-core/rnaseq:dev`or `nf-core/eager:dev` have it
- GitHub Actions testing as has been implemented in `nf-core/sarek:dev` or `nf-core/eager:dev` nowadays 👍 

The linting should therefore check whether at least one of these approaches is used and actively testing the code and not enforce Variant 1, as we might want to switch over to using e.g. GitHub Actions soon.

Comments / Ideas?

**Comment by ewels** [comment]
How about we decide which method we want to use, and then test only for that?

**Comment by apeltzer** [comment]
Sounds great to me - here or on slack ?

**Comment by ewels** [comment]
I think that we're all agreed about moving to GitHub Actions now, right? So I would suggest that we do all of the updates required for that and update the linting at the same time. (Maybe after the upcoming tools release, which needs to be done soon..)

**Comment by apeltzer** [comment]
GitHub Actions sounds like the way to go for me at least - then I'll downgrade the RNAseq travis tests to normal behaviour and add the same tests using GitHub actions there. (So "legacy TravisCI" + GitHub Actions - old linting will work, new linting is going to work too :-))

**Comment by drpatelh** [comment]
Yeah. I agree. Would be better I think if we update tools to use GitHub Actions and then roll this across the pipelines :+1:

**Comment by ewels** [comment]
Ok, I think let's do this for v1.8 if that's ok. Travis is stable and there's no big need to change immediately. Better to switch to GitHub actions when that work is completely finished and polished? Or are we there already?

**Comment by ewels** [comment]
As long as the travis files are still there, pipelines shouldn't fail for also having GitHub Actions.. So we can essentially test this new method for a bit first..

**Comment by apeltzer** [comment]
I agree that we should have this period where we still test using TravisCI but can nevertheless roll out the GitHub Actions and make sure that this is mature too - I think we are basically there yet but I'd rather see v1.7 out sooner than later and this involves some more testing ...

**Comment by MaxUlysse** [comment]
cf https://github.com/nf-core/tools/pull/369

**Comment by ggabernet** [comment]
solved by #472

**Comment by drpatelh** [comment]
Great work @ggabernet :sunglasses: Maybe we should leave this issue open until we have fully removed Travis in the next release :+1:

**Comment by ewels** [comment]
Travis was removed from the template in https://github.com/nf-core/tools/pull/502
