### ISSUE TITLE
Syncing is broken

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#416]
The automatic sync for the v1.7 release of tools broke 😞 

See the [travis logs](https://travis-ci.org/nf-core/tools/jobs/594611240#L1105-L1114):

```python
Traceback (most recent call last):
  File "./bin/sync", line 8, in <module>
    import syncutils.template
  File "/home/travis/build/nf-core/tools/bin/syncutils/template.py", line 2, in <module>
    from syncutils import utils
  File "/home/travis/build/nf-core/tools/bin/syncutils/utils.py", line 1, in <module>
    import erro
ModuleNotFoundError: No module named 'erro'
```

Sure enough, looks like a simple typo, introduced by yours truly in a35d554a0d4178913da7f7a0e0ede8b951c2cc41 :
https://github.com/nf-core/tools/blob/2d324b4334658e1cd907289b4a7497abf5ef4191/bin/syncutils/utils.py#L1
(should be `errno`) Sorry everyone 🤦‍♂ 

Maybe we should, ahem, have some testing for these files...? 🙄

**Comment by apeltzer** [comment]
Ahem maybe 😅

**Comment by MaxUlysse** [comment]
That does make a good case for it ;-)

**Comment by drpatelh** [comment]
Im going on strike.

**Comment by drpatelh** [comment]
Can we close this now @ewels ?

**Comment by ewels** [comment]
oh yeah, this is an old one sorry..
