### ISSUE TITLE
Template should specify `saveReference` 

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#417]
All pipelines should use similar syntax for stuff like this:

x-ref https://github.com/nf-core/rnaseq/pull/300#discussion_r333019764

**Comment by drpatelh** [comment]
This currently isnt in the template because we dont have a process that can use it sensibly i.e. we only have `fastqc` and `multiqc` there. Its probably best to keep it simple like this so Ill close this issue but feel free to re-open if required.

**Comment by drpatelh** [comment]
This currently isnt in the template because we dont have a process that can use it sensibly i.e. we only have `fastqc` and `multiqc` there. Its probably best to keep it simple like this so Ill close this issue but feel free to re-open if required.
