### ISSUE TITLE
iGenomes paths wrong for GRCm38

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#418]
These lines should point to `GRCm38` and not `GRCh37`! Does this require a patch? If it isnt spotted by the pipeline developer it could lead to issues. Hopefully, the pipeline fails because the annotation files arent consistent but possibly not worth the risk...

https://github.com/nf-core/tools/blob/2e2fe8e2bed87b9d25582811115f429de9f48e33/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/conf/igenomes.config#L27-L28

**Comment by apeltzer** [comment]
Just double-checked and it should at least fail:

```
ls -l /nfsmounts/igenomes/Mus_musculus/Ensembl
GRCm38
NCBIM37
```

**Comment by apeltzer** [comment]
see https://github.com/nf-core/tools/pull/419 for a PR
