### ISSUE TITLE
Link to Slack pipeline channel broken in README

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#420]
In main [`README.md`](https://github.com/nf-core/tools/blob/dev/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/README.md)

```
For further information or help, don't hesitate to get in touch on [Slack](https://nfcore.slack.com/channels/{{ cookiecutter.name }}) (you can join with this invite).
```

On pipeline creation this should evaluate to e.g.:
```
For further information or help, don't hesitate to get in touch on [Slack](https://nfcore.slack.com/channels/chipseq) (you can join with this invite).
```

instead of:
```
For further information or help, don't hesitate to get in touch on [Slack](https://nfcore.slack.com/channels/nf-core/chipseq) (you can join with this invite).
```

**Comment by MaxUlysse** [comment]
`{{ cookiecutter.name }}` should be `chipseq`, right?

**Comment by drpatelh** [comment]
Yep :+1:

**Comment by MaxUlysse** [comment]
OK, then it's not my fault :-D
Because I do believe I'm the one that introduced this direct channel address in template.

**Comment by drpatelh** [comment]
Also needs to be fixed in this file [`CONTRIBUTING.md`](https://github.com/nf-core/tools/blob/dev/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/.github/CONTRIBUTING.md)
```
For further information/help, please consult the [{{ cookiecutter.name }} documentation](https://github.com/{{ cookiecutter.name }}#documentation) and don't hesitate to get in touch on the [{{ cookiecutter.name }} pipeline channel](https://nfcore.slack.com/channels/{{ cookiecutter.name }}) on Slack.
```

**Comment by GeniusStorm** [comment]
Need some help here. since `cookiecutter.name` is dynamically evaluated and looking at the code . i believe the the change should be happening here ` self.name = 'nf-core/{}'.format(self.short_name)` in __init__ method of PipelineCreate class. Please correct me if I am wrong

**Comment by drpatelh** [comment]
```
For further information/help, please consult the [{{ cookiecutter.name }} documentation](https://github.com/{{ cookiecutter.name }}#documentation) and don't hesitate to get in touch on the [{{ cookiecutter.name }} pipeline channel](https://nfcore.slack.com/channels/{{ cookiecutter.short_name }}) on Slack.
```

This should do it @GeniusStorm ! Thank you! Ill send you an invite as a contributor to if thats ok with you?

**Comment by GeniusStorm** [comment]
@drpatelh  Sure you can send me the invite. I'll make that happen. Thanks

**Comment by drpatelh** [comment]
xref: https://github.com/nf-core/tools/pull/421
