### ISSUE TITLE
Lint pipeline code indentation 

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#430]
Ok. I'm going to run away now :running_shirt_with_sash: ...discuss :smile:

**Comment by ewels** [comment]
Would be nice! Difficult though - need to find a code linter for groovy that checks indentation.

**Comment by ewels** [comment]
CodeNarc: http://codenarc.sourceforge.net/codenarc-rules-formatting.html#Indentation

**Comment by drpatelh** [comment]
Yeah, it would be really nice to enforce this mainly because each contributor will have their own way of including spacing which is fine but its the pipeline code that actually suffers for consistency. Also, makes it quite difficult to review if this isnt consistent.

**Comment by ewels** [comment]
Feel free to make a PR! 😉

**Comment by drpatelh** [comment]
Will do when I feel free 😅

**Comment by piotr-faba-ardigen** [comment]
I tried to configure uncrustify. I had to force it to run in `VALA` language mode. `Java` would be better, but indtents every line if `;` is missing at the end of the statement.

## Usage
You will need to have [`uncrustify`](http://uncrustify.sourceforge.net/) installed. Then

```
uncrustify -l VALA -c uncrusify.cfg -f main.nf --replace --no-backup
uncrustify -l VALA -c uncrusify.cfg -f nextflow.config --replace --no-backup
```
The configuration file `uncrustify.cfg` contents:
```
# Uncrustify-0.67-87-d75a44aa9
input_tab_size                  = 3
output_tab_size                 = 3
indent_columns                  = 3
indent_continue                 = -1
indent_with_tabs                = 0
indent_class                    = true
indent_col1_comment             = true
code_width                      = 120
align_assign_span               = 1
align_nl_cont                   = true
# option(s) with 'not default' value: 10
#
```

## Style guide:

Line width: `120`
Indent: `3` spaces

## Warnings

1.  Need to use `;` at the end on statements even though it is optional in groovy. Otherwise, some indentation will go wrong.

**Comment by piotr-faba-ardigen** [comment]
To make a note...
It was also mentioned that possibly coala.io could be adapted: https://coala.io/#/about

**Comment by grst** [comment]
A coala bear sounds awesome. 
How about putting this on the agenda for the next hackathon?

**Comment by ewels** [comment]
Quick update - I have tried running a Groovy linter in VSCode and it's a nightmare 😅 So yeah, this is not trivial.

How far does EditorConfig take us, as used in nf-core/modules? eg. https://github.com/nf-core/modules/pull/340/checks

![image](https://user-images.githubusercontent.com/465550/112276328-e58f2c00-8c80-11eb-976a-1b15a3ab17fe.png)

**Comment by grst** [comment]
Making Code-Narc and npm-groovy-lint properly work with nf-core pipelines seems daunting indeed. 
I was wondering if a very simple rule-based autoformatter (basically some regexes in python) would be a good start. It certainly won't scale up to completely reformatting a whole document, but it could cover some simple, but common cases (e.g. indentation of `input` channels, module imports, etc.)

**Comment by ggabernet** [comment]
Hi, what is the status here? Would the `EditorConfig` as we have it set right now already solve this issue, or is there still something that we are missing @grst @drpatelh @ewels

**Comment by grst** [comment]
@Emiller88 is working on it. 

See the #prettier-plugin-nextflow channel on slack.

**Comment by ewels** [comment]
EditorConfig does it but bluntly I believe. I think it checks that indentation is a multiple of `x` ([in our case](https://github.com/nf-core/tools/blob/e0d00d3e09a996f59eb5ce6ebc4795452a5b1d39/nf_core/pipeline-template/.editorconfig#L8), 4). But there's nothing to stop you from indenting your entire pipeline at 16 spaces per line. You can see this in action in [my comment above](https://github.com/nf-core/tools/issues/430#issuecomment-805595978).

The only solution to be more clever than this is a fully fledged language linter. The current effort is a Prettier plugin led by @Emiller88 which actually understands the syntax.... and yeah, just saw @grst's comment pop up, see that slack channel 😓 

I think close the issue 👍🏻

**Comment by ggabernet** [comment]
ok thanks for the clarifications!
