### ISSUE TITLE
Bump version for conda export command

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#431]
Added this to the template recently but it just twigged that we also need to bump the version here in the `Dockerfile` too:
https://github.com/nf-core/tools/blob/a0a72de7a2d8ff874c1efaab427fe73f4ce6574b/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/Dockerfile#L7

**Comment by phue** [comment]
https://github.com/nf-core/tools/pull/453

**Comment by drpatelh** [comment]
Thanks @phue 👍
