### ISSUE TITLE
Move awsbatch.config to nf-core/configs

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#435]
We should probably move `conf/awsbatch.config` from the template to nf-core/configs. It's generic enough to do so and will be easier to update for all pipelines from a single location on nf-core/configs. However, since this file already exists in most nf-core pipeline repos we need to test if there is a clash when we pull exactly the same file from nf-core/configs at run-time. Config priority will probably need to be taken into account too :running_man:

**Comment by MaxUlysse** [comment]
Done with #463 https://github.com/nf-core/configs/pull/71 https://github.com/nf-core/configs/pull/89
