### ISSUE TITLE
Parameter for "workflow.manifest.name/workflow.manifest.version"

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#441]
It would be nice to set `singularity.cacheDir` within Institute specific files in `nf-core/configs`. Providing this area is read/write for anyone at a given Institute it means that whenever someone uses an nf-core pipeline for the first time the singularity containers will be pulled and stored in a central area for reuse by anyone!

The easiest way would have been to use the `workflow` scope directly in these config files but this isn't possible. The alternative is that we add a parameter to the template that represents e.g. `rnaseq/1.4.2`. This would have to be changed when bumping versions too.

Need to figure out whether this will work when pulling `dev` tagged containers too :thinking:

**Comment by ewels** [comment]
Does nextflow not already name the image filename intelligently? Can the cachedir not just be something generic for all pipelines?

**Comment by apeltzer** [comment]
Yeah but it's dumping all of them in a single folder then, we do that on `CFC` already. Doesn't look too nice, on the other hand as this is just a dump I don't mind too much either? ;-) 

<img width="769" alt="Bildschirmfoto 2019-11-05 um 15 26 31" src="https://user-images.githubusercontent.com/2359510/68216183-cedf2b00-ffe0-11e9-9f20-68938612c1cf.png">

**Comment by drpatelh** [comment]
Agreed. Biggest downside of separating them by "workflow.manifest.name/workflow.manifest.version/" would be that you could have duplicate containers across pipelines when `modules` eventually take over. Biggest upside is its better for organisation, and to maintain later.

However we decide to implement this though we will need to factor in the backward compatibility of such a parameter because most pipelines wont have it until they have updated to the latest template.

**Comment by MaxUlysse** [comment]
So many sarek containers...
2.5.1 and 2.5 are exactly the same, if you want to save space, you can make a link ;-)

**Comment by ewels** [comment]
My vote is for keeping it simple and just doing what the [CFC config does](https://github.com/nf-core/configs/blob/ebbf884ac5503eca48ee2446c62e2be6c7f23935/conf/cfc.config#L8-L11):

```nextflow
singularity {
  enabled = true
  cacheDir = '/nfsmounts/container'
}
```

**Comment by ewels** [comment]
> However we decide to implement this though we will need to factor in the backward compatibility of such a parameter because most pipelines wont have it until they have updated to the latest template.

..and if we do keep it simple then we don't need to make any changes to pipelines, right?

**Comment by drpatelh** [comment]
Probably best to leave things as they are even though I think its not the optimal solution for organising containers across multiple pipelines.
