### ISSUE TITLE
nf-core bump versions in container/*/Dockerfile and container/*/environment.yml

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#466]
As we're seeing https://github.com/nf-core/tools/pull/453 address one more point, I'm considering thinking about also bumping versions for multiple container Dockerfiles in `container/*/Dockerfile` paths e.g. for Sarek but also other pipelines.

**Comment by MaxUlysse** [comment]
Love the idea, should do that for the `environment.yml` file as well

**Comment by apeltzer** [comment]
Good point - yeah, that would be a really useful addition. The `sarek` and `bcellmagic` pipelines would love to have that, `bacass` would be good to have that too.

**Comment by ewels** [comment]
Closing as I think this use case will hopefully slowly vanish with DSL2.
