### ISSUE TITLE
Shields.io badge not recognised

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/tools#468]
From https://shields.io/
> We support .svg and .json. The default is .svg, which can be omitted from the URL.

So such a badge works:

```Markdown
[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen)](http://bioconda.github.io/)
```

[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen)](http://bioconda.github.io/)

But it's not recognised by linting.

I'm guessing we're checking for the exact existence of this line:

```Markdown
[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg)](http://bioconda.github.io/)
```

We could be slightly more lenient

**Comment by ewels** [comment]
Ok, so you're talking about the presence of absence of the `.svg` extension?
```diff
-[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen)](http://bioconda.github.io/)
+[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg)](http://bioconda.github.io/)
```

**Comment by MaxUlysse** [comment]
Yes, that's precisely that

**Comment by ewels** [comment]
..does this matter? 😅 

Should be an easy fix if you want to make a PR though! Good excuse to brush up on your Python skills 😉

**Comment by ewels** [comment]
Closing as low priority and doesn't affect most people. Simpler to update the pipeline badge than to update the linter to allow different variants.
