### ISSUE TITLE
nf-core lint fails to fail when no nextflow is installed.

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/tools#469]
cf @sofiahaglund 
Critical error, but we still got 14 tests passed, 0 with warning or 0 failed...

Error message:
```
CRITICAL: Critical error: It looks like Nextflow is not installed. It is required for most nf-core functions.
INFO: Stopping tests...
INFO: ===========
 LINTING RESULTS
=================
  14 tests passed   0 tests had warnings   0 tests failed
```

**Comment by ewels** [comment]
I guess we could prevent the summary printing in this case. But I'm not sure that this is really a bug - it's working as expected. The end user not having nextflow installed is not a failure with the pipeline code.

**Comment by MaxUlysse** [comment]
So it's a bug then, we should stop printing info at this step
