### ISSUE TITLE
nf-core lint searches vim tmp files

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/tools#477]
Files matching .*.sw? should probably not be included in what's linted.

**Comment by ewels** [comment]
hah, oops.. Which linting step is this?

**Comment by ewels** [comment]
Hi @erikrikarddaniel,

Are you able to confirm which linting step you had this issue with? Just so that we can be sure to track down the error.

Cheers,

Phil

**Comment by erikrikarddaniel** [comment]
Den fre 31 jan. 2020 kl 17:49 skrev Phil Ewels <notifications@github.com>:
>
> Hi @erikrikarddaniel,
>
> Are you able to confirm which linting step you had this issue with? Just so that we can be sure to track down the error.
>
I'm afraid not and I can't reproduce it now... I have opened the
main.nf in vim and have a .main.nf.swp file but do not get any
warnings from that. (I do get a number of other warnings though: conda
packages not up to date and a few TODOs, but not in vim files.)
nf-core is at version 1.7; not updated since November I believe.

> Cheers,
>
> Phil
>
/D

**Comment by ewels** [comment]
I don’t think that the linting looks at main.nf at all, or any of the config files. It checks those by running `nextflow config` - so it’s up to Nextflow to ignore temp files for those. It’s possible that the linting would pick up on temp files for other stuff I guess, but I’m not sure which files or tests would be affected by this.

If it’s ok, I’ll close this issue now. But please reopen if it happens again with the specific error / warning that you get from a temp file and it should be easy enough to track down.

Phil

**Comment by fasterius** [comment]
I'm getting similar behaviour with TODO strings and vim undo-files (`<file.extension>.un~`): even TODOs that I've fixed are still showing up in the undo files (as they are part of the files' histories), which is a bit annoying. A workaround is of course to just store my undo-files in my home folder, but I prefer them to be in the same directory as their original file.

**Comment by ewels** [comment]
Fix is to improve the code that ignores files in the `check_pipeline_todos()` function: 
https://github.com/nf-core/tools/blob/8f3c482b3a186a3e56771927943719062826ced8/nf_core/lint.py#L1167

At the moment it will only work with exact filename matches though, so will need to be extended to use `fnmatch` to match file patterns as well.

**Comment by ewels** [comment]
Suggestion for glob patterns: `*~` and `*?`

**Comment by fasterius** [comment]
Should work, though I don't know if any others use `*~`. Either use that or `*.un~`if you want to be more specific.

**Comment by ewels** [comment]
I can't see why we would need to commit any files ending in `~`. Easy enough to change / manually add if we do anyway, so I'd rather keen it broad I think.

**Comment by Gullumluvl** [comment]
Hey there, quick question: is this merged into main? I installed `nf-core` 3.2.0 with `pip` but this does not seem to work (on `.*.sw?` files).

Which `.gitignore` file is it looking at? The one from the repository where you are currently running the command? I checked and it has the pattern.

I tried a `nf-core modules lint ...` from the `modules` repo.

**Comment by mashehu** [comment]
I looked a bit in the code and looks like `nf-core pipelines lint` ignores files in `.gitignore` while this is not the case for `nf-core modules|subworkflows lint`. What is your use case?

**Comment by Gullumluvl** [comment]
Thanks @mashehu . I'm running `nf-core modules lint`. I think it would make sense for this configuration to apply to all linting commands.

**Comment by mashehu** [comment]
Could you open a new issue with this, please?
