### ISSUE TITLE
Change pipeline's homepage URL

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/tools#498]
Currently the URL should begin with `https://github.com/nf-core/`.
I would change that to `https://nf-co.re/` and maybe put a warning if it begins with `https://github.com/nf-core/` and still an error otherwise.

**Comment by ewels** [comment]
Do you mean the `manifest.homepage` config variable?

**Comment by MaxUlysse** [comment]
Yes, sorry, that was clear for me, but obviously now I can see that I did not give enough details

**Comment by ewels** [comment]
Looking at this again now, I do not think that we want to do this. The de-facto URL for any pipeline is GitHub, as this is where it is executed from. I think it is risky to put the nf-co.re URL there as it could break all kinds of things.
