### ISSUE TITLE
Covert tools to GitHub Actions

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#500]
We should move the tools repo itself to GitHub actions. Tasks that need to be ported: (ticked are done)

- [x] Markdown linting
- [x] Python code tests
- [x] Running `nf-core create` and `nf-core lint`
- [x] Uploading code coverage results
- [x] Generating API docs for website
- [x] Uploading releases to PyPI automatically
- [x] Synchronising template updates to all pipelines

**Comment by ewels** [comment]
First PR: https://github.com/nf-core/tools/pull/487

**Comment by drpatelh** [comment]
Assuming this will need to be amended too:
https://github.com/nf-core/tools/blob/25335b387589008838c83fb0a73808cc0f9a7cbb/scripts/nf-core#L232

**Comment by ewels** [comment]
Nearly there now! Just fixing the sync..

**Comment by ewels** [comment]
Sync stuff added to github actions and `.travis.yml` file deleted in https://github.com/nf-core/tools/pull/524

🍾

**Comment by ewels** [comment]
Completed in #524
