### ISSUE TITLE
Release checklist for tools repo

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#505]
It would be useful to have a point of reference when releasing `nf-core/tools` just to make sure nothing has been forgotten before release and that everything has been triggered properly after the release. Ive jotted down some stuff below:

## Before release

1. Check issue milestones to see outstanding issues to resolve if possible or transfer to the milestones for the next release e.g. [`v1.9`](https://github.com/nf-core/tools/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.9)
2. Create a PR to `dev` to bump the version in  `CHANGELOG.md` and `setup.py`.
3. Make sure all CI tests are passing!
4. Create a PR from `dev` to `master`
5. Make sure all CI tests are passing again (additional tests are run on PRs to `master`)
6. Request review (2 approvals required)
7. Most importantly, pick an undeniably outstanding [name](http://www.codenamegenerator.com/) for the release where *Prefix* = *Metal* and *Dictionary* = *Animal*.
8. Merge the PR into `master`
9. Once CI tests on commit have passed, create a new release copying the `CHANGELOG` for that release into the description section.

## After release

1. Check the automated template synchronisation has been triggered properly. This should automatically open PRs directly to individual pipeline repos with the appropriate changes to update the pipeline template.
2. Check that the automatic `PyPi` deployment has worked: https://pypi.org/project/nf-core/
3. Check `BioConda` has an automated PR to bump the version, and merge. eg. https://github.com/bioconda/bioconda-recipes/pull/20065
4. Create a tools PR to `dev` to bump back to the next development version in  `CHANGELOG.md` and `setup.py`

**Comment by ewels** [comment]
Edited your issue to add a bit more detail - click the "edited by ewels" dropdown to see what I changed 👍

**Comment by ewels** [comment]
We should make one of these for pipelines too - maybe on the website? Will be pretty similar..

**Comment by drpatelh** [comment]
Im not convinced this makes sense anymore: "Add today's date for the Changelog release number." This is almost always a delay between merging final changes to `dev` and reviews being approved which means it just another thing to look out for and update...given also that the date is recorded by GitHub anyway.

@apeltzer wrote something similar for pipelines a while back:
https://nf-co.re/developers/adding_pipelines#release-checklist

**Comment by ewels** [comment]
Ah my bad, this is just my habit from other tools I guess (I was referring to my MultiQC checklist when I was editing this). Didn't realise that we don't have release dates on the changelog. Adjusted..

The pipeline release checklist is great, but maybe a little tricky to find.. (I had forgotten it existed!)

**Comment by drpatelh** [comment]
No worries 👍 

Agreed, we should maybe re-position the pipeline checklist somewhere a bit more findable on the website.

**Comment by apeltzer** [comment]
Yeah I also figured its not ideally placed for people to look after it 😓 Should have that somewhere more up the list I think so too?

**Comment by MaxUlysse** [comment]
> @apeltzer wrote something similar for pipelines a while back:
> https://nf-co.re/developers/adding_pipelines#release-checklist

That was there....
I was looking for this for such a long time.
Can we have that in the template in a `.github/RELEASE_CHECKLIST.md` file, like in the [MultiQC repo](https://github.com/ewels/MultiQC/blob/master/.github/RELEASE_CHECKLIST.md)
