### ISSUE TITLE
Allow the `!` prefix to manifest.version linting

### ISSUE THREAD

**Issue by jfy133** [nf-core/tools#506]
# Problem
The nextflow check against `manifest.version` doesn't actually stop the pipeline with a helpful error message if a users version doesn't use the specify version unless `!` is specified before the `>=`, as described here: https://www.nextflow.io/docs/latest/config.html?highlight=manifest#nextflow-version

Howeve linting fails if `!`, is included.

# Solution

It would be nice if `!` would also be accepted by linting on this line (thanks for @drpatelh for pointing towards it): https://github.com/nf-core/tools/blob/9e33e7f02758964a1a09436af1eb6afe0e596e4c/nf_core/lint.py#L467

(Note: I'm not familar with python and don't have much time atm so not comfortable making a PR myself yet).

# Alternative
Current workaround, add the following to main.nf

https://www.nextflow.io/docs/latest/metadata.html#nextflow-metadata

**Comment by ewels** [comment]
Fixed 🎉
