### ISSUE TITLE
Docs nf-core sync for individual pipeline

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#509]
Having had a go at this today, things didnt quite work out as they should have done. I thought it would be a good idea to note this all down here so the process can be refined if need be. I attempted to trigger the sync on my local fork of the pipeline that just has a `master` branch.

1. Switch to local branch you would like to merge with `TEMPLATE`

2. Remove/move any files in local repo that you dont want to commit and commit the rest.
    * This triggers an error because the tool needs to switch between branches and `rm -rf` all of your files. So if you have uncommitted changes they will be deleted.

3. Run `git remote -v` to check you have the right upstream set:

    ```bash
    origin	https://github.com/drpatelh/nf-core-imcyto.git (fetch)
    origin	https://github.com/drpatelh/nf-core-imcyto.git (push)
    upstream	https://github.com/nf-core/imcyto.git (fetch)
    upstream	https://github.com/nf-core/imcyto.git (push)
    ```

4. Fetch/create the `TEMPLATE` branch and run `nf-core sync`:

    1. If the `TEMPLATE` branch doesnt exist in the local and remote repo of your fork BUT it does exist in the nf-core repo then fetch it and run `nf-core sync`:

    ```bash
    git fetch upstream TEMPLATE:TEMPLATE
    git checkout TEMPLATE
    git push --set-upstream origin TEMPLATE
    git checkout master

    nf-core sync --pull-request ./
    ```

    2. If the `TEMPLATE` branch doest exist on your fork AND the nf-core repo then create it via `nf-core sync`:

    ```bash
    git fetch upstream TEMPLATE:TEMPLATE
    git checkout TEMPLATE
    git push --set-upstream origin TEMPLATE
    git checkout master

    nf-core sync --make-template-branch --pull-request ./
    ```

    3. If you have previously synced the nf-core pipeline via your fork then delete the `TEMPLATE` branch locally (`git branch -D TEMPLATE`) and remotely via the *branches* tab on GitHub to remove the commits from the last sync, and then follow the steps in `i.` above.

5. Manually create a PR from `TEMPLATE` to `master` on your local fork

    * You will need to do this if you get the error:
      `ERROR: No GitHub authentication token set - cannot make PR`

6. Follow the command-line instructions provided on the PR by GitHub to resolve the conflicts. These will most likely be:

    ```bash
    git fetch origin
    git checkout TEMPLATE
    git merge master               ## This will report a number of merge conflicts that you will need to resolve and commit (dont push!)

    git checkout master
    git merge --no-ff TEMPLATE
    git push origin master        ## This merges and auto closes the PR from TEMPLATE to master on the local repo
    ```

7. Create a PR to nf-core `dev` from local repo `master`
    * This should only contain the commits you created to resolve the merge conflicts

8. Create a PR to nf-core `TEMPLATE` from local repo `TEMPLATE`
    * This should only contain the commit for the creation of the `TEMPLATE`

**Comment by ewels** [comment]
Docs written in nf-core/nf-co.re#299 that hopefully supersede these. You'll see that there is stuff in common, but it's hopefully a lot easier 😅
