### ISSUE TITLE
tools-docs generation not working

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#511]
Travis should be auto-generating documentation for the tools python package:
https://github.com/nf-core/tools/blob/9e33e7f02758964a1a09436af1eb6afe0e596e4c/.travis.yml#L40-L44

However, this seems to be broken at the moment. https://nf-co.re/tools-docs is returning a 404 error.

Need to look in to this and rewrite the whole functionality to use GitHub actions.

**Comment by ggabernet** [comment]
The link worked for me now. Is this fixed?

**Comment by ewels** [comment]
Yup, this was fixed in https://github.com/nf-core/tools/pull/530 sorry 👍
