### ISSUE TITLE
nf-core download: Handle multiple containers

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#513]
At the moment, if used with `--singularity` then `nf-core download` expects there to only be a single container and pulls that. There are however some pipelines that need more than one (sarek, neutronstar and more) and there will be many more (all) in the future.

Need to instead parse all instances of `process.container` if possible and automatically pull all required singularity images.

Would be good to combine with https://github.com/nf-core/tools/issues/464 to also automatically configure the pipeline with paths so that it knows where these containers are out of the box.

**Comment by MaxUlysse** [comment]
Could be an issue if the tag is specified by a parameter:
https://github.com/nf-core/sarek/blob/5c30fd821ab7cdf27fd4105464a1fba5eabdfcd5/conf/base.config#L67-L74
I could rewrite these lines to specify each containers for each genome, but then wouldn't `nf-core download` try to download all containers?
Then again, Sarek is a very specific case...

**Comment by apeltzer** [comment]
Yeah, I fear this is very special behaviour. Most people will (hopefully?) use biocontainers soon when DSLv2 is used more widely, then downloading directly from biocontainers instead...

**Comment by ewels** [comment]
Much of the download code was rewritten #832 - I think that having special cases like this is beyond the scope of `nf-core download` so I will close this issue now.
