### ISSUE TITLE
Update template and readme with paper

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#519]
As on the tin

**Comment by apeltzer** [comment]
Done :)

**Comment by drpatelh** [comment]
We havent yet!

**Comment by ewels** [comment]
Ready to be merged: https://github.com/nf-core/tools/pull/520

**Comment by drpatelh** [comment]
Maybe we should keep this open until we know whether we can change it to Open Access.

**Comment by ewels** [comment]
We can't.. 😞 Closing.
