### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#54]
We should really do a release on at least PyPI soon.

**Comment by sven1103** [comment]
+1

**Comment by sven1103** [comment]
Suggestion: let's wait for your #53 to be merged, then I write some tests to increase CC, and then we can go for 1.0.0

**Comment by sven1103** [comment]
@ewels once #59 is merged, i think you are good to go for the first release? @nf-core/admin any objections?

**Comment by ewels** [comment]
Will do 👍

**Comment by ewels** [comment]
@sven1103 see #60
