### ISSUE TITLE
wrong `export_plots` value in multiqc_config.yaml

### ISSUE THREAD

**Issue by mashehu** [nf-core/tools#555]
I ran into the following error after the template sync:
```
Missing output file(s) `multiqc_plots` expected by process `multiqc (1)`
```
When changing `export_plots` value in multiqc_config.yaml from `true` to `True` it worked, see https://github.com/nf-core/rnaseq/issues/200

Not sure if it is really a bug, but at least I ran into it and it looks like it is still like that in the template.

**Comment by ewels** [comment]
That is odd. I was under the impression that YAML didn't care about the upper or lower case of `true`. Indeed if I do a quick test in Python that seems to be the case:

```python
>>> import yaml
>>> y_string = '''
... var_1: true
... var_2: True
... var_3: truee
... '''
>>>
>>> yaml.safe_load(y_string)
{'var_1': True, 'var_2': True, 'var_3': 'truee'}
```

**Comment by ewels** [comment]
Just tested MultiQC locally with two `multiqc_config.yaml` files and it generated the exported plots with both `true` and `True`.

Could you check in the working directory and see the contents of `multiqc_config.yaml` please? Also paste the MultiQC log file?

**Comment by mashehu** [comment]
argh, now it worked also with the old `mulitqc_config.yaml`. Sorry for bothering you.

**Comment by ewels** [comment]
Ok phew 😅
