### ISSUE TITLE
Improve Branch Protection GitHub Actions

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/tools#558]
Instead of just a simple failure when PR are coming to `master`, I would like to have a comment posted saying something like:

> Hi,
> You recently made this PR into the `master` branch
> It is not a patch, so it should be made into the `dev` branch
> You can change that by clicking on EDIT and then changing the base branch to `dev`
> Thanks again for your contribution

cf #518

**Comment by ewels** [comment]
ooh, nice idea. I think this should be doable..

**Comment by MaxUlysse** [comment]
Hackathon task?

**Comment by ewels** [comment]
Oh sorry, I did it already 🙄 https://github.com/nf-core/tools/pull/559
