### ISSUE TITLE
Have nf-core lint check for cookiecutter statements in code and docs

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/tools#564]
I have no idea why, or how, but I got some cookiecutter statements in the sarek code.
cf https://github.com/nf-core/sarek/pull/131
I'm guessing more a bad copy-paste rather than a faulty template update.
So not sure if it'll be really useful, but it could be good to check for cookiecutter statements in code and docs

**Comment by ewels** [comment]
Good idea - should be as simple as just searching for the string `cookiecutter` in all pipeline files I guess 👍

**Comment by drpatelh** [comment]
Fixed in linked PRs above.
