### ISSUE TITLE
Warn for Bioconda badge requirements

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#567]
If I remove the Bioconda badge in the main `README.md` of `nf-core/nanoseq` then the linting fails because I have an `environment.yml` in the pipeline repo:
https://github.com/nf-core/tools/blob/ebf63095ab222e4df987c4e950ce3839e8784d3e/nf_core/lint.py#L649

This pipeline is implemented with a mixture of containers on Docker Hub as well as the container shipped with the pipeline. So as it stands "install with bioconda" badge isnt strictly speaking true because ALL of the dependencies cant be installed with BioConda.

**Comment by ewels** [comment]
I started writing a comment explaining how to change this, but then I figured that I could make a PR to fix it in about the same number of keystrokes 😅
