### ISSUE TITLE
Automatically build CLI help using JSON Schema

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#577]
Once JSON Schema files are present in pipelines, we can start to use these files to automatically generate the command-line help outputted by pipelines with the `--help` parameter.

Requires parsing in Groovy in the pipeline code, then writing a function to output nicely formatted text.

**Comment by drpatelh** [comment]
Assuming this would be similar to the code use in the `hlatyping` pipeline:
https://github.com/nf-core/hlatyping/blob/bf5d0c2d4646df8ce240230b1a15c0a241658a07/main.nf#L16-L86

**Comment by apeltzer** [comment]
Yes, but I'd advise to have this as an external small library that can be synced more easily across pipelines :-) 

Sarek had/has some script in groovy that are kept externally, to keep these separated from the `main.nf` - which makes sense I think :-)

**Comment by ewels** [comment]
Aha yeah - I think this was back from when we started with the custom nf-core metaschema? Looks like we can build on that code for sure though 👍 

I'll try to get to this soon, it's basically at the top of my list once I get some more talk slides finished.

**Comment by ewels** [comment]
> Yes, but I'd advise to have this as an external small library that can be synced more easily across pipelines :-)

It would be great to do this generally - see https://github.com/nf-core/tools/issues/634 (will also help / become more relevant with DSL2 file imports).

**Comment by drpatelh** [comment]
Initial implementation added in https://github.com/nf-core/tools/pull/665

**Comment by mashehu** [comment]
As discussed on [slack](https://nfcore.slack.com/archives/CE5LG7WMB/p1602757500146100), it would be good to run this function also in the `output_documentation` step (together with a `copyTo` for `output.md` and `usage.md`) and put the output into a `parameters.md`, so that every result directory comes bundled with the complete, version specific docs.

**Comment by drpatelh** [comment]
Think we should have a separate issue for this @mashehu as the original proposal has been solved already.

**Comment by drpatelh** [comment]
However, @ewels mentioned that the code added in #665 , the latest of which is currently sitting in the [rnaseq](https://github.com/nf-core/rnaseq/blob/a3222ce3010caf25c92f0c981de501a57cd583f6/lib/Schema.groovy#L34-L53) pipeline doesn't factor in some nesting/grouping that is possible to use with the JSON schema?
