### ISSUE TITLE
Allow for numbers in pipeline name

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/tools#588]
Sometimes is does make sense to have numbers in pipeline names.
i.e. current situation trying to create a `sarscov2` or `covid19` pipeline.
`sarscovtwo` or `covidnineteen` doesn't work as well. 
So it could be good to update `lint` and `create` to allow for it.

**Comment by ewels** [comment]
First should check whether dockerhub can have numbers. I think this is probably why I set it up like that before. It doesn’t allow hyphens so I suspect that it won’t.

Having said that, it’s looking increasingly likely that we will ditch dockerhub for DSL2 pipelines, so maybe it doesn’t matter too much.

**Comment by apeltzer** [comment]
It does allow it :-)

**Comment by ewels** [comment]
Then yeah, should just be a case of adding two characters (`\d`) to a regex somewhere.

**Comment by ewels** [comment]
Fixed in part of a bigger PR that I'm about to submit..

**Comment by drpatelh** [comment]
Seems like this was fixed so closing. Ping @ewels.

**Comment by ewels** [comment]
I have basically no memory of this, but sure - looks like I fixed it! 😅
