### ISSUE TITLE
Add GitHub actions aws test workflow to template

### ISSUE THREAD

**Issue by ggabernet** [nf-core/tools#596]
The aws test GitHub actions workflow should be added to the template

- [x] Small CI tests on `push` to master
- [x] Big tests triggered by a bot
- [x] Docs on how to add big datasets

**Comment by ggabernet** [comment]
Hi @nf-core/core, 
thinking about it I'm a bit hesitant about adding the AWS full test trigger on a comment to issues. In this case, anyone could trigger AWS full size tests by just adding this keyword to an issue, even if they are not part of nf-core. 

There is also the option of triggering it on comments to pull requests only when they are opened (and not synchronized), but that doesn't really solve the problem as anybody part of the nf-core organization still can open a pull request. 

I think still on `push` to master would be the safest option to trigger the workflow, and maybe also after a `release` to have the final results.

**Comment by ewels** [comment]
Sure! I guess if we wanted we could always check if the comment came from someone in the nf-core/core team? But I’m pretty happy with just doing it on push to master & release. That’s still basically pre-release and release which is a lot.

**Comment by ggabernet** [comment]
As discussed via slack, the pre-release full tests can be done via Nextflow tower launch. The same queues, S3 bucket and AWS credentials can be specified there, and it should also launch the tests.

**Comment by ggabernet** [comment]
Solved in #620

**Comment by ewels** [comment]
![image](https://user-images.githubusercontent.com/465550/84948257-c2c95900-b0eb-11ea-9e10-965d503e61b9.png)
