### ISSUE TITLE
Add contact info to CoC Enforcement section; add new Escalation section

### ISSUE THREAD

**Issue by heuermh** [nf-core/tools#598]
I note two issues with the [Contributor Covenant Code of Conduct](https://github.com/nf-core/tools/blob/master/CODE_OF_CONDUCT.md) used by the `nf-core` template:

The first is that the contact method in the Enforcement section is inadequate, as it only links to Slack.  It should really be an email alias and possibly also a name and phone number, for those who might be worried about sensitive communication via email.

The second issue is that an Escalation section is missing, for reporting issues with the project team listed in the Enforcement section.  We have such an [Escalation section in our CoC](https://github.com/bigdatagenomics/adam/blob/master/CODE_OF_CONDUCT.md#escalation).

**Comment by apeltzer** [comment]
xref https://github.com/OBF/obf-docs/issues/67 to have a link to it

**Comment by ewels** [comment]
@heuermh would be fab if you fancied prepping a PR for this. We can use the email address core@nf-co.re I think, or happy to make a new alias (but would probably get it to send to the same people?).

Note that we have multiple copies of this CoC, but can start with the one that you linked to plus the one in the template that is in the same repo. Then it's just the website and the rest should be automated I think.

**Comment by heuermh** [comment]
Sure, will do!

**Comment by heuermh** [comment]
Looking back at this, the open question is if there can be an escalation contact.  Meanwhile, I'll create a PR swapping the Slack link in the enforcement section to the core@ email alias.

**Comment by ewels** [comment]
Now written 🎉
