### ISSUE TITLE
ValueError: Reference at 'refs/heads/master' does not exist 

### ISSUE THREAD

**Issue by TheSallyGardens** [nf-core/tools#599]
Hi!
When I run "nf-core list" I get this error(ValueError: Reference at 'refs/heads/master' does not exist ).
what can I do ?
I try to reinstall git,but it do not work.
python version 3.8     git version 1.8.3.1

**Comment by ewels** [comment]
Hi @TheSallyGardens,

Did you manage to solve this problem?

Phil

**Comment by TheSallyGardens** [comment]
> Hi @TheSallyGardens,
> 
> Did you manage to solve this problem?
> 
> Phil

Yeah,I solved it.

**Comment by ewels** [comment]
Great! What was the issue?

**Comment by TheSallyGardens** [comment]
I deleted the nf-core configuration file,and re-install it.

**Comment by ewels** [comment]
Ok nice, thanks! Hopefully helpful for future googlers 👍

**Comment by TheSallyGardens** [comment]
You're welcome.
