### ISSUE TITLE
Add a warning when launching with no profile

### ISSUE THREAD

**Issue by maxulysse** [nf-core/tools#606]
I think it could be good for new user to add a warning when launching a pipeline with no profile.
I know that we do say so in the docs, but I don't think it would hurt to have an extra warning explaining that if no profiles have been specified, there might be some errors due to the absence of finding the tools, due to the lack of containers or virtual environment.
And maybe some extra help in https://nf-co.re/usage/troubleshooting

**Comment by ewels** [comment]
Good idea! I don’t think that this should be too difficult to do either. We already have some other checks that look at the profile that is being used.

**Comment by MaxUlysse** [comment]
It's true that a warning when no profile would be good, but actually, I think we need more than a no profile, we need to test if dependencies are being handled.
It's actually quite easy to check if a pipeline is run with docker or singularity, but I have no idea on how to know when a pipeline is using conda.

So far, my idea is something like that:
```
if (!workflow.containerEngine) {
    log.warn "[nf-core] No containers were specified"
    log.warn "Nextflow will expect all depencencies to be handle with conda, or within the system"
    log.warn "If a process fails with: command not found"
    log.warn "It was probably because of that"
}
```
Any suggestions @nf-core/core

**Comment by ewels** [comment]
Yes, I had exactly the same thought but decided to keep it to myself as it sounded more complicated 😅 

I guess we can check if `process.conda` is set?

https://github.com/nf-core/tools/blob/ebf63095ab222e4df987c4e950ce3839e8784d3e/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/nextflow.config#L59

Also we could make this a hard failure unless a `params.ignore_software_check` is set or something. That way, advanced users could still do whatever they want, but the 99% of beginners who hit this are immediately told without a nasty error.

**Comment by MaxUlysse** [comment]
Not sure on how to access processes information outside of a process.

**Comment by MaxUlysse** [comment]
> Also we could make this a hard failure unless a `params.ignore_software_check` is set or something. That way, advanced users could still do whatever they want, but the 99% of beginners who hit this are immediately told without a nasty error.

Not sure about that, I think a warning should be good enough.
Especially if the warning is clear about a `command not found` error.
But I don't want to scare our conda users with an unjustified warning

**Comment by drpatelh** [comment]
Added in https://github.com/nf-core/tools/pull/1309
