### ISSUE TITLE
nf-core lint fails to find the branch workflow

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/tools#627]
On the current Sarek dev, I just installed the latest tools dev with:
`pip install --upgrade --force-reinstall git+https://github.com/nf-core/tools.git@dev`

Workflow branch does exist:
```
ll ./.github/workflows/branch.yml
```
But test fails:
```
nf-core lint .
...
ERROR: Test Failures:
  https://nf-co.re/errors#5 : Couldn't find GitHub Actions 'branch' workflow step to check that forks don't submit PRs to master: './.github/workflows/branch.yml'
```

Any ideas?

**Comment by ewels** [comment]
Running with `dev` linting needs the [`dev` style of `branch.yml`](https://github.com/nf-core/tools/blob/dev/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/.github/workflows/branch.yml).

Docs for `dev` lint test: https://github.com/nf-core/tools/blob/dev/docs/lint_errors.md#error-5---continuous-integration-configuration--5

**Comment by MaxUlysse** [comment]
Thanks, I'm closing the issue then
