### ISSUE TITLE
Move boilerplate code into separate lib file

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#634]
Currently, nf-core pipelines have a lot of boilerplate code in the main `main.nf` script. It would be nice to move this out into a separate file to make the pipeline code easier to read.

This is intended for DSL1 pipelines, but the move will also be useful for DSL2 when we will also want to import this code and call it from functions in the same way.

@pditommaso made a start on this way back in 2018, with a draft PR on the methylseq pipeline: https://github.com/nf-core/methylseq/pull/47

@phue followed up with a draft PR on the hlatyping pipeline https://github.com/nf-core/hlatyping/pull/61 (also included stuff for the now depreciated `parameters.settings.json` file)

Needs reassessing with the latest version of the pipeline and testing.

**Comment by ewels** [comment]
See also what @drpatelh started in the chipseq pipeline: https://github.com/nf-core/chipseq/tree/modules/modules

**Comment by apeltzer** [comment]
Tried something similar in https://github.com/nf-core/eager/pull/490

**Comment by ewels** [comment]
Yes, let's try to combine all of this in the template instead of spread across loads of different repos 😅

**Comment by drpatelh** [comment]
Will be mostly fixed in https://github.com/nf-core/tools/pull/665

**Comment by ewels** [comment]
Nearly finished - just the email code really that needs moving I think..

**Comment by ewels** [comment]
We already have an issue dedicated to rewriting the email code - https://github.com/nf-core/tools/issues/112

Closing in favour of that.
