### ISSUE TITLE
Launch - make a web GUI for setting parameters

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#637]
The command-line wizard for `nf-core launch` is great, and should work fine if people are working on systems that have no internet connection. However, buoyed by the apparent success of the web-based JSON Schema builder, it could be nice to build something similar for launching pipelines too.

This would be a fairly minor change for `nf-core launch`, just a question at the start as to whether to use the web-based interface or the command-line interface. Then if web-based, send off to the website in the same way as the schema builder and wait for a response.

Should probably reuse as much of the schema build code as possible.

**Comment by ewels** [comment]
Done in #638 and nf-core/nf-co.re#400, nf-core/nf-co.re#402, nf-core/nf-co.re#404, nf-core/nf-co.re#405

**Comment by drpatelh** [comment]
We good to close this @ewels ?

**Comment by ewels** [comment]
Ah sorry, yes - I think I meant to hit close with that last comment..
