### ISSUE TITLE
JSON Schema: Write some documentation!

### ISSUE THREAD

**Issue by jpfeuffer** [nf-core/tools#650]
I.e. use `[text](#param_PARAMID)`.
If you tell me where to put it, I probably could write something.

**Comment by ewels** [comment]
There isn't anywhere to add it yet, because there are no docs written for schema at all yet. It's one of the last remaining things left to do..

**Comment by ewels** [comment]
Documentation has been written in the tools changelog and in the schema builder header. Hopefully this is sufficient, though I would like to generally have a go-over the documentation for tools. There's already another issue for that though: https://github.com/nf-core/tools/issues/670
