### ISSUE TITLE
Schema build - more helpful error message if no internet connection

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#656]
Currently, if you are working on a headless machine (e.g. via SSH), and try to use the `nf-core schema build .` command, it correctly asks questions but doesn't forward you to a respective browser session. 

As tools anyways queries the nf-co.re website for the existence of a finished JSON file ( correct me if I'm wrong here ), could we maybe have a (clickable) URL posted on the command line for users that are working remotely on a Linux machine? 

That doesn't have to break the auto-forward to browser thing, but could indeed help remote workers :-)

**Comment by ewels** [comment]
It does show you the URL, doesn't it?

**Comment by apeltzer** [comment]
Yes, there is a URL - but 
![image](https://user-images.githubusercontent.com/2359510/87009402-6a0a4f00-c1c5-11ea-88d6-6a2d0bbd4ddc.png)

Probably would be helpful to show the session id to enter and then users can go there themselves?

**Comment by ewels** [comment]
Ah right, I see. The online schema builder is a multiple step process:

1) Sends schema to the nf-core website where it is saved, website returns an ID
2) Opens the web browser with that cache ID
3) Polls the API for that ID to see when the state changes
4) When ready, pulls the updated schema from the API when it's finished

I don't think it's just the headless browser opening thing that's an issue for you here, as it prints the URL with the ID when it tries to open the browser. So I think it's probably a lack of connectivity to the website for step (1) that is your problem.

What you can do is copy your schema to the clipboard, paste into the website at https://nf-co.re/json_schema_build, use the tool, then copy the output when you're done and paste it into your terminal again to update the file.

Phil

**Comment by apeltzer** [comment]
True, just wondered whether we should at least add some hint for users (can do that myself too of course) to document this 👍

**Comment by ewels** [comment]
Yes, should be able to add some more help text to the failed connection exception 👍
