### ISSUE TITLE
Automatize DSL2 modules creation + linting

### ISSUE THREAD

**Issue by JoseEspinosa** [nf-core/tools#667]
We are discussing in the DSL2 channel of the 2020 July nf-core hackathon that since the implementation of DSL2 modules shares a common structure, it could be nice to implement a kind of `nf-core modules create` command. This command should work in a similar manner as `nf-core create` but for creating new modules. Will this make sense?

**Comment by ewels** [comment]
Could be a nice idea, though a major difference to `nf-core create` is that this would only be for use within the nf-core/modules repository, in quite a specific place. Not necessarily a reason not to do it though.

I have a nasty feeling that someone is going to suggest `nf-core modules lint` and `nf-core modules sync` and all sorts of other command mirrors soon too..! 😰

**Comment by grst** [comment]
> I have a nasty feeling that someone is going to suggest nf-core modules lint and nf-core modules sync and all sorts of other command mirrors soon too..! 

That sounds like a very reasonable thing to do ;) 
But maybe first the module structure itself needs to settle a bit

**Comment by ewels** [comment]
I made a stub `nf-core modules check` to ensure that the pipeline version of a module is unchanged from the upstream version. The intention would be to bring the same functionality into the main `nf-core lint` command.

Note that all current `nf-core modules` subcommands are designed to be used with a pipeline though. I think that anything we write to work with nf-core/modules wrappers should be kept quite separate to make the distinction clear.

**Comment by ewels** [comment]
Having hit submit, I'm now wondering if `nf-core modules create` might be an exception. As I guess we will have DSL2 wrappers which are pipeline-specific. So maybe it can skeleton such a module in the current pipeline, _or_ work with the nf-core/modules repo for imported modules 🤔

**Comment by ewels** [comment]
> I think that anything we write to work with nf-core/modules wrappers should be kept quite separate to make the distinction clear.

Ok so this didn't happen 😆 

The requested functionality is basically in place now though I think 🚀
