### ISSUE TITLE
Helper function for versioning modules' docker containers

### ISSUE THREAD

**Issue by grst** [nf-core/tools#674]
In a module wrapper script, we want to have the version/identifier of the associated docker container hard-coded. 
(if the `latest` tag would be used, pipelines could break if the latest docker container was updated in the modules repository)

Initially, the idea was to name the docker container by the git-hash which is also used to identify the module, version. However, in https://github.com/nf-core/modules/pull/23, we figured that this is impossible, because the git hash would change by hard-coding it into the wrapper script. 

One possible solution could be to use the sha256(`Dockerfile` + `environment.yml`) to identify docker containers. 
For this it would be helpful to have a `nf-core` command which automatically calculates the checksum and bumps the corresponding `container` line in the module script. 

Moreover, module linting should check if the specified container-id needs to be updated. 

@ewels, anything I forgot?

**Comment by ewels** [comment]
Thinking about this now, maybe we should have a `nf-core modules lint` command which does linting for a single module. This could check that the `process.container` tag uses the hash and print a log message with what it should be if not. I think that should be sufficient help without actually changing the file for the user, what do you think?

**Comment by grst** [comment]
:+1: makes sense

**Comment by ewels** [comment]
Is this issue still relevant now that we are using BioContainers for everything? I guess there may still be cases where we need to build custom containers, but I would hope that these would be very very rare...
