### ISSUE TITLE
conda install failed

### ISSUE THREAD

**Issue by pcantalupo** [nf-core/tools#683]
Hello,

I tried to install tools with 
`conda install -c bioconda nf-core` but got following error:

```
$ conda install -c bioconda nf-core
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                            

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

Any suggestions on what to try next? I'm on a Mac 10.15.5 and just installed Miniconda3 today.   Thank you

**Comment by pcantalupo** [comment]
I figured it out.  I needed to set up the Bioconda channels first `https://bioconda.github.io/user/install.html#set-up-channels`

**Comment by ewels** [comment]
Hi @pcantalupo - glad you got it working. I’m trying to replace all instances of `conda install -c bioconda nf-core` in the docs with just `conda install nf-core`, as I think that the former is a bit misleading. Let me know if you spot any like this or can suggest where you would expect to find better documentation.

Phil
