### ISSUE TITLE
Tool to create child images for users without overlayFS

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#69]
One of the most common problems for users with singularity is that they don't have overlayFS configured, so the pipeline fails with directory mounting issues.

This subcommand would generate a Singularity image script based on the main pipeline, but dynamically adding in all base directories (detected or specified) so that mounting works properly.

Steps:

- [ ] New `nf-core` tools subcommand `fix-overlay`, takes name of target pipeline
- [ ] Download the `Singularity` file from the target pipeline
- [ ] Detect all local root directories, or take supplied list
- [ ] Replace `From` and `%post` statements in Singularity file
- [ ] Save to `/tmp` and run `singularity build` to make a new image with the required mount points

**Comment by apeltzer** [comment]
Maybe we could have a look at Packer.io - unfortunately no support for Singularity yet.

https://www.packer.io/docs/builders/index.html

**Comment by Rotholandus** [comment]
We have found some free frameworks/API that we could use with OpenStreetMap data
https://cohaesus.co.uk/finding-a-new-way-six-alternatives-to-google-maps/

**Comment by ewels** [comment]
Nice! Though the blog post is a bit old now and many of the links it points to don't work any more. I think that MapBox is probably the way to go though (perhaps using [leafletJS](https://leafletjs.com)?)

**Comment by apeltzer** [comment]
https://github.com/apeltzer/apeltzer.github.io/tree/master/talkmap

(its my private homepage, having a map.html with leafletJS integrated and a JSON for the locations...) 

Should be easy to do something very similar for us ....

**Comment by ewels** [comment]
@aanil and @remiolsen - could you add some comments here describing how far you got with this issue at the hackathon please? It would be good to come to a conclusion and get this implemented somehow (I remember that we had some different ideas for what kind of solution we could use).

**Comment by remiolsen** [comment]
Previously, I have fixed this issue in Nexflow configs. You can do this by setting `singularity.runOptions='-B /mount1:/mount1 -B /mount2:/mount2'`. [Ex](https://github.com/remiolsen/NGI-NeutronStar/blob/master/conf/tegner.config)

So a suggestion might be to in stead of a tool that creates a new image, why not have one that creates a new config?

**Comment by apeltzer** [comment]
Cool idea - but I fear this will only work on systems with enabled `OverlayFS`. We should probably test this on a system where there is no `OverlayFS` available and then find out if this works - would be much easier and not require setting up a new container for users with specific hardware...

**Comment by ewels** [comment]
I've asked if this can be tested in Gothenburg - xref: https://github.com/nf-core/rnaseq/issues/76#issuecomment-415359282

**Comment by mihai-sysbio** [comment]
Even if the solution above would work well for one user, we would basically need to tell everybody to fix it this way. For us at Hebbe the solution was to build the Singularity image from this recipe:

```
Bootstrap: docker
From: nfcore/rnaseq

%post
    mkdir -p /c3se
    mkdir -p /local
    mkdir -p /apps
    mkdir -p /usr/share/lmod/lmod
    mkdir -p /var/hasplm
    mkdir -p /var/opt/thinlinc
    mkdir -p /usr/lib64
    touch /usr/lib64/libdlfaker.so
    touch /usr/lib64/libvglfaker.so
    touch /usr/bin/nvidia-smi
```

Apparently overlayfs isn't available in centos 6.

**Comment by mihai-sysbio** [comment]
Docker compose [can take in multiple files](https://docs.docker.com/compose/reference/overview/#use--f-to-specify-name-and-path-of-one-or-more-compose-files). Singularity seems to have something similar for its [recipes](https://github.com/singularityhub/singularityhub.github.io/wiki/Build-A-Container#naming-recipes).

I was thinking it would be useful if Singularity had, like Docker, an automatic way to merge config files. At a glance, though, it doesn't seem it handles overriding the base config by another config.

**Comment by ewels** [comment]
I think we should close this issue now. We haven't seen the problem nearly so frequently recently and I don't think that it is worth the effort to write this helper tool.
