### ISSUE TITLE
Lint: Don't fail on master if no releases yet

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#72]
It's common for us to commit to the `master` branch with development code before the first release is made. The tests always fail here, which is kind of annoying. It would be good if before failing, the linting tool can check whether there are any pipeline releases.

**Comment by sven1103** [comment]
I am not so sure about this. If we stick to the GitHub Flow for example, code on `master` branch is always deployable. It might well be, that we decided it differently in the beginning of `nf-core`.

Nevertheless, why don't we have a `test` branch, which also runs the nf-core tools with the `--release` parameter? Then we can say, merges to `master` need to come from `test`, and so we always have releas-ready, passing builds on `master`.

@pditommaso happy, if you could provide us with some pro tips here too.

**Comment by ewels** [comment]
Nice idea, though that's kind of a separate problem - ensuring that tests pass before merging to master.

Here, we've already merged to master and tests are failing because it's dev code. We could fix this by just leaving `master` blank with a readme saying check the `dev` branch until there's a first release. Then we're using the same methodology as we do post-release, which is probably better.

Another option is to not fork to nf-core until the first release is ready.

**Comment by ewels** [comment]
Since PR #133, tests don't run if we're basing a PR on `master`. So new pipelines should still follow the same routine of working on `dev` instead of `master`. This means that tests should pass, and this issue is fixed.
