### ISSUE TITLE
AWS test workflows trigger

### ISSUE THREAD

**Issue by ggabernet** [nf-core/tools#737]
There is currently a problem with the AWS tests workflows: 
- The small tests are set to trigger on push to master. If the versions have been bumped there already (it's usually the case), then the container can't be found as it has not yet been pushed to dockerhub.
- The full tests are set to trigger on release. The workflow for pushing the container to dockerhub is slower than the job submission to AWS,  so there is a risk that the container can't be found either.

One solution would be to add the trigger for `workflow_dispatch` events (we already discussed that), these would then work when the container is available on docker hub. However, they will not work either on the master branch before release if the versions have been bumped, but  could be triggered again some time after releasing.

**Comment by ewels** [comment]
I think this is done now, right @ggabernet?

**Comment by ggabernet** [comment]
The trigger for AWS tests is now on `release` and also for `workflow_dispatch`. The trigger on `workflow_completion` for the `push dockerhub` workflow did not work at all, I tested it several times. 

So it is not an ideal solution yet, but we are able to retrigger the workflows any time with `workflow_dispatch`. This was solved by #751 and #755 .

**Comment by drpatelh** [comment]
I wonder whether it's worth having a "dummy" nf-core pipeline that is composed of the nf-core template. It would allow us to test these things a little more e.g. merging random things to `master` and restoring it's state etc.

**Comment by ggabernet** [comment]
That would be nice for testing these things, yes!

**Comment by ewels** [comment]
Fixed in https://github.com/nf-core/tools/pull/770

Follow-on additional linting for presence of old GHA workflow file: https://github.com/nf-core/tools/pull/771
