### ISSUE TITLE
json-schema: No such thing as a range type

### ISSUE THREAD

**Issue by mashehu** [nf-core/tools#738]
Thanks to @jfy133, I read through the [json-schema specs for ranges](https://json-schema.org/understanding-json-schema/reference/numeric.html#range) again  and it turns out what we treat as `range` types are just `number` types with a `minimum/maximum` property... 🤯 

So we have to fix that in the following files:
- tools repo:
  - [x] `launch.py`
  - [x] `test_launch.py`
- nf-co.re repo:
  - [x] `launch.php`
  - [x] `pipeline_schema_builder.php`
  - [x] `nf-core-schema-builder.js`

**Comment by ewels** [comment]
@mashehu - is this all done now? Can we close this issue?

**Comment by mashehu** [comment]
Yes, thanks! I forgot to update it once the new tools release was out.
