### ISSUE TITLE
Actions: set-env depreciated

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#739]
GitHub Actions is depreciating the `set-env` method previously used to pass environment variables between workflow steps.

I think that we use this method in quite a few places, so we may need to make some updates.

See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by ewels** [comment]
This is going away November 16, so is now urgent: https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/

**Comment by ggabernet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [nf-core tools](https://trello.com/c/7IF6AMOo/2-nf-core-tools)

**Comment by ewels** [comment]
> _The `add-path` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/_

https://github.com/nf-core/rnaseq/actions/runs/360361285

**Comment by ggabernet** [comment]
Maybe that's something we can test really nicely in the `testpipeline`.

In the case of the `awsmegatests`, it would hopefully be a matter only of updating the setup miniconda action to `conda-incubator/setup-miniconda@v2` [here](https://github.com/nf-core/testpipeline/blob/07e0833a28d98f20aa1a2699a6627241caf15206/.github/workflows/awsfulltest.yml#L18).

**Comment by ggabernet** [comment]
And the `CI` workflow uses the `set-env` command, not sure if part of the workflow or of the imported actions (e.g. technote-space/get-diff-action@v1): https://github.com/nf-core/testpipeline/actions/runs/357450322

**Comment by KevinMenden** [comment]
Using `conda-incubator` as suggested by Gisela did the trick for the awstest and awsmegatest files.

Using a newer version of `get-diff-action` should solve the trick for ci.yml as well. Needed to change the PREFIX_FILTER command with FILES due to the newer version, too.
I'm getting some new errors new when testing on the testpipeline but they seem to be docker related ....
https://github.com/nf-core/testpipeline/actions/runs/361878129

**Comment by ewels** [comment]
Looks like the linting is failing: https://github.com/nf-core/testpipeline/pull/12#issuecomment-726830086

> ### :x: Test failures:
> 
> * [Test #5](https://nf-co.re/errors#5) - GitHub Actions 'branch' workflow should be triggered for PRs to master: `/home/runner/work/testpipeline/testpipeline/.github/workflows/branch.yml`

If the linting fails then other CI checks may also be stopped early..

Not entirely sure what the failure is due to. Could be a remnant from me mucking around with stuff earlier? Might be worth rolling back my commits so that you're working with an otherwise fresh repo again.

**Comment by KevinMenden** [comment]
The CI failure is due to the docker container, which it tries to build. I could replicate it on my machine:

```
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::click-7.1.2-pyh9f0ad1d_0'.
OSError(2, 'No such file or directory')
Attempting to roll back.
```

It's probably something with the order of installation in bioconda again :/

**Comment by KevinMenden** [comment]
Okay so the error comes when installing multiqc in the docker container ... which is odd because that should be working fine ...

**Comment by KevinMenden** [comment]
The issue was the base image ... when using the nfcore/dev base image, it fails. Will test again and  if CI works I can make a PR to solve the 'set-env' issue here.

**Comment by ewels** [comment]
Just had my first CI error due to this being disabled: https://github.com/nf-core/smrnaseq/pull/57/checks?check_run_id=1408805300 😱 

Will try updating that pipeline to have your changes and hope it fixes it!

**Comment by ewels** [comment]
Nice! https://github.com/nf-core/smrnaseq/pull/57/checks?check_run_id=1408826335 🚀 

Great work @KevinMenden!

**Comment by ewels** [comment]
Solved, just needs a release.
