### ISSUE TITLE
Add a podman profile to the template

### ISSUE THREAD

**Issue by Zethson** [nf-core/tools#742]
Currently, Nextflow supports Docker, Singularity and Podman as container engines.

However, nf-core projects do not come with a Podman profile, only Docker & Singularity.

I personally consider this to be inconsistent. Podman is shaping up to be a strong Docker alternative and I would like it to be supported first class.

A simple

```
podman {
    podman.enabled = true
}
```

should allow people to run nf-core pipelines also with profile podman.
Don't think we need additional settings here, but I guess this would need some empirical evaluation.

Cheers

**Comment by MaxUlysse** [comment]
Looks easy enough.

**Comment by apeltzer** [comment]
@Zethson want to prepare one for the tools/template? :-)

**Comment by Zethson** [comment]
Sure, will do tomorrow. Was just wondering if someone ever tried to run an nf-core pipeline with podman and knows whether this is sufficient.

**Comment by apeltzer** [comment]
Never tried - but heard good things about the simple alias behaviour so could be worth to support podman yes :-)
