### ISSUE TITLE
Add podman to the pipeline docs

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#753]
@Zethson just added a new config profile to support Podman: https://github.com/nf-core/tools/pull/744

This needs describing in the pipeline template docs. For example, the readme, `docs/usage.md` and maybe `.github/ISSUE_TEMPLATE/bug_report.md`.

**Comment by Zethson** [comment]
Feel free to assign it to me.  Thursday, 22 October 2020, 11:39PM +02:00 from Phil Ewels  notifications@github.com :
