### ISSUE TITLE
Problems with pipeline logo after template sync

### ISSUE THREAD

**Issue by skrakau** [nf-core/tools#759]
With the template update to 1.11, some mysterious changes occurred on some pipeline logos in the `TEMPLATE` branch. 

For the `mag` pipeline the logo turned black: 
https://github.com/nf-core/mag/blob/TEMPLATE/docs/images/nf-core-mag_logo.png

And for the `bcellmagic` pipeline the PNG file contains HTML code: 
https://github.com/nf-core/bcellmagic/blob/TEMPLATE/docs/images/nf-core-bcellmagic_logo.png

The other pipeline logos seem fine though.

**Comment by MaxUlysse** [comment]
I have similar issues with the png for Sarek: https://github.com/nf-core/sarek/blob/TEMPLATE/docs/images/nf-core-sarek_logo.png

**Comment by ewels** [comment]
Hmm, I guess this happens because the sync PR meant that the website page that generates the logos was hit with a load of traffic all at once and was basically DDOSed.

Only "fix" that I can think of is to check the returned image a bit more carefully and try it a few times if it looks wrong.

**Comment by ewels** [comment]
Made a quick bash script to `curl` a logo for each nf-core pipeline and ran it after the above website caching strategy was merged.

On the first run it took `37.939s` to run (without cache), the second time in `16.748s` (with cache). So hopefully substantially faster now and less likely to mess up in the sync.
