### ISSUE TITLE
Dummy nf-core pipeline for testing

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#767]
It may be nice to have an nf-core pipeline with all of the standard set-up that we can use to tests things without being petrified of breaking protected branches e.g. https://github.com/nf-core/tools/issues/737#issuecomment-723568108. This could just be composed of an pipeline initialised using `nf-core create` which could also be dynamically synced on each tools release. We could then do as we wish with the pipeline e.g. merging and testing things to `master` but it may need to be blacklisted for certain things like the website.

**Comment by ewels** [comment]
What happened to the DSL2 test pipeline repo? Did we delete that?

But yes this isn't a bad idea 👍 Easy to do with some planning, just need to add the name to some website config files before creating the repo.

**Comment by drpatelh** [comment]
I think we did delete that after we changed how we were going to do things with DSL2 and merged the template into a separate branch on `tools`.

**Comment by ewels** [comment]
Prepped for making `nf-core/testpipeline` - https://github.com/nf-core/nf-co.re/pull/562

**Comment by ewels** [comment]
Created: https://github.com/nf-core/testpipeline

**Comment by ewels** [comment]
> Which could also be dynamically synced on each tools release.

NB: This will not happen. As it is ignored by the website, most automation will also ignore it. I think this is fine.

**Comment by drpatelh** [comment]
No worries. We should still be able to manually push the code after each release by wiping and replacing branches?
