### ISSUE TITLE
API docs out of date

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#775]
Not sure we actively maintain these anymore: https://nf-co.re/tools-docs/ 

But they have not been updated for quite a while - version shows 1.4 & some of the newer commands are thus missing entirely. 

Should either make sure this is in line with newest docs _or_ remove it :-)

**Comment by ewels** [comment]
Hmm, the docs build onto the `api-doc` branch on this repo, which was apparently updated 4 hours ago: https://github.com/nf-core/tools/tree/api-doc

So this time it seems that the docs are being updated properly. Maybe they're just not being pulled by the website?

**Comment by ewels** [comment]
Hmm, being updated but not up to date:

https://github.com/nf-core/tools/blob/e8eb3949d82c13ca713daa63469763c1fc44fb93/docs/api/_build/html/index.html#L50-L57

**Comment by ewels** [comment]
The plot thickens.. The commit message looks good, references commit 6840e0f which is the latest on `dev`.

Not sure why the generated docs are then out of date?

Workflow: https://github.com/nf-core/tools/blob/dev/.github/workflows/tools-api-docs.yml

Action: https://github.com/nf-core/tools/runs/1418901896?check_suite_focus=true

**Comment by ewels** [comment]
Ah, the docs generation is not quite as clever as I thought - it needs stubs for each command: https://github.com/nf-core/tools/tree/master/docs/api/_src

**Comment by apeltzer** [comment]
Works fine now - thanks for fixing :-)
