### ISSUE TITLE
List of things to transfer from eager to template

### ISSUE THREAD

**Issue by jfy133** [nf-core/tools#786]
# nf-core/tools feature request

As discussed on slack (https://nfcore.slack.com/archives/CE5LG7WMB/p1605800237461800), there is a bunch of things that (by popular demand) should be transferred from eager to the main template.

This thread is to gather a list of things to be transferred:

- [x] Extra bullet points in README (@ewels  will need to clarify this)
- [x] Contributing to pipeline docs (from .github/CONTRIBUTING.md)
- [x] Naming scheme (from .github/CONTRIBUTING.md; requires wider discussion!) 
- [x] Allow HTML tags in markdown lint
- [x] bug replort template is nice, (asking people to check a box saying that they’ve consulted the documentation and log files) _[Typo kept as vertabim because lol]_
- [ ] custom pipeline logo in MultiQC report, that needs the logo image to be staged as an input to the process I guess

**Comment by ewels** [comment]
I think this is done now, right @jfy133 ? Feel free to reopen if not.
