### ISSUE TITLE
Validate --max_memory and --max_time parameters and exit if not a valid Nextflow resource unit

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#793]
Using `--max_memory 80` should be validated properly as a Nextflow memory unit and if not to generate an error. The correct way of specifying this would be for example --max_memory '42 GB' otherwise the pipeline just allocates a memory value of 0 and still proceeds as normal. This was initially reported [here](https://github.com/nf-core/rnaseq/issues/504).

**Comment by ewels** [comment]
Actually in your example I think that it is a valid memory unit, it will allocate 80 bytes of memory.. 👀

**Comment by ewels** [comment]
This should be handled by the JSON schema parameter validation if we set the schema validation to only accept values with a GB (or TB / PB) suffix. This will mean that people are then not able to specify a huge value in bytes, but I think that's ok.
