### ISSUE TITLE
Lint GitHub Actions files

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#795]
I noticed the other day that the VSCode YAML linting tool uses JSON schema for specific YAML files if it recognises the file paths. Specifically, it validates GitHub Actions workflow files. This could be a really nice addition!

Here's the JSON Schema file for GitHub Actions: https://json.schemastore.org/github-action

We already have a bunch of code in `nf-core/tools` for handling JSON Schema, so should hopefully be fairly easy to also validate these files without adding any new dependencies.

**Comment by KevinMenden** [comment]
Makes sense - will have a look at it 👍 👀

**Comment by KevinMenden** [comment]
Made a PR #820 to add this functionality, was actually pretty straightforward to do. 

I Used the GitHub Workflows Schema: https://json.schemastore.org/github-workflow
The one posted by you is for actions.
