### ISSUE TITLE
Output docs HTML file includes GitHub warning

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#810]
In a recent release of the template we introduced an extra string into `output.md` to warn people against reading these files in GitHub:

https://github.com/nf-core/tools/blob/8c68650409a3f95376dd55c291dae5f9fc346347/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/docs/output.md#L3-L5

What I failed to remember at the time is that `output.md` is also used to generate a HTML file which is delivered with the pipeline results. This warning now also shows up there. See for example [this report](https://nf-core-awsmegatests.s3-eu-west-1.amazonaws.com/methylseq/results-dev-23fb12c16e89b651a2ef5de1e61439923906547c/pipeline_info/results_description.html):

![image](https://user-images.githubusercontent.com/465550/101482888-a948f180-3957-11eb-9cae-007e94194875.png)

We should either strip this warning from `output.md` (`usage.md` is fine) or update the pipeline md -> HTML conversion script to omit it when generating the output. My preference is to remove the warning from this file.

**Comment by mashehu** [comment]
This warning is for the documentation of the pipeline parameters, which are anyway not in `output.md` or in `usage.md`, so we might actually drop it from both (but put a link to `/parameters` in `usage.md`.

**Comment by ewels** [comment]
Not exactly  - the warning mentions `/parameters` but was mostly telling people not to read on GitHub and use the nf-core website instead.
