### ISSUE TITLE
Download doesn't find DSL2 containers

### ISSUE THREAD

**Issue by chewgl** [nf-core/tools#818]
## Steps to reproduce

Steps to reproduce the behaviour:
(See *--> below)

```
$ nf-core download rnaseq --singularity

                                          `,--./,-.`
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 1.12.1



INFO     Saving rnaseq                                                                        download.py:81
          Pipeline release: 3.0
*-->          Pull singularity containers: Yes
          Output file: nf-core-rnaseq-3.0.tar.gz
INFO     Downloading workflow files from GitHub                                               download.py:85
INFO     Downloading centralised configs from GitHub                                          download.py:89
*--> INFO     No container names found in workflow                                                 download.py:98
INFO     Compressing download..                                                              download.py:117
INFO     Command to extract files: tar -xzf nf-core-rnaseq-3.0.tar.gz                        download.py:303
INFO     MD5 checksum for nf-core-rnaseq-3.0.tar.gz: da2871c0a6db3c1019effc0cb87972be        download.py:344
```

Probably with the recent add-back of singularity containers downloaded from biocontainers, something broke in the nf-core download tool.

**Comment by drpatelh** [comment]
Since this functionality doesn't exist yet I have manually downloaded and uploaded all of the containers required for v3.0 of the rnaseq pipeline to Dropbox (4.5GB). Please see instructions below for downloading them for use in an offline environment:

```
## (1) Download an archive containing all of the containers for the pipeline
wget -L https://dl.dropboxusercontent.com/s/5venz3l2wihaqdp/nf-core-rnaseq_v3.0.tar.gz
wget -L https://dl.dropboxusercontent.com/s/0w2e72pz2iuj37e/nf-core-rnaseq_v3.0.tar.gz.md5

## (2) Check tar archive was downloaded ok
md5sum -c nf-core-rnaseq_v3.0.tar.gz.md5

## (3) Untar archive and move this somewhere where the containers can be re-used for future pipeline runs
tar -xvf nf-core-rnaseq_v3.0.tar.gz

## (4) Export this variable so Nextflow finds the containers you downloaded
export NXF_SINGULARITY_CACHEDIR=/PATH/TO/UNTAR/ARCHIVE/nf-core-rnaseq_v3.0/
```

**Comment by ewels** [comment]
Rewritten and solved in the upcoming v1.13 release of tools. See #832.

**Comment by EstelLec** [comment]
> Since this functionality doesn't exist yet I have manually downloaded and uploaded all of the containers required for v3.0 of the rnaseq pipeline to Dropbox (4.5GB). Please see instructions below for downloading them for use in an offline environment:
> 
> ```shell
> ## (1) Download an archive containing all of the containers for the pipeline
> wget -L https://dl.dropboxusercontent.com/s/5venz3l2wihaqdp/nf-core-rnaseq_v3.0.tar.gz
> wget -L https://dl.dropboxusercontent.com/s/0w2e72pz2iuj37e/nf-core-rnaseq_v3.0.tar.gz.md5
> 
> ## (2) Check tar archive was downloaded ok
> md5sum -c nf-core-rnaseq_v3.0.tar.gz.md5
> 
> ## (3) Untar archive and move this somewhere where the containers can be re-used for future pipeline runs
> tar -xvf nf-core-rnaseq_v3.0.tar.gz
> 
> ## (4) Export this variable so Nextflow finds the containers you downloaded
> export NXF_SINGULARITY_CACHEDIR=/PATH/TO/UNTAR/ARCHIVE/nf-core-rnaseq_v3.0/
> ```

Hello, would it be possible to have equivalent Dropbox for nf-core-atacseq-1.2.1 and nf-core-chipseq-1.2.2 ? I had trouble dowloading singularity containers for RNAseq pipeline and it solved my problem, but I face the same issue for atacseq and chip seq pipelines. Thank you !

**Comment by ewels** [comment]
Hi @EstelLec - have you tried using `nf-core download`?
