### ISSUE TITLE
Time parameters like `4.d` get parsed as double and fail schema validation

### ISSUE THREAD

**Issue by KevinMenden** [nf-core/tools#858]
## Description of the bug

Using e.g. `--max_time 4.d` throws a validation exception because the schema expects a string for `--max_time` 
which should be granted by internal conversion of nextflow Duration objects to string, which seems to fail in this case

## Steps to reproduce

Running a pipeline with the new parameter validation and a time parameter as described above should reproduce the bug.
I did it with a fresh template.

**Comment by KevinMenden** [comment]
Some testing confirmed that it is indeed not catched by the `cleanParameters` function.

Adding
```
if (p['value'].getClass() == Double) {
                new_params.replace(p.key, p['value'].toString())
            }
```

To that function captures the parameter, but converts it to `4.0` which then doesn't match the schema validation anymore.

**Comment by KevinMenden** [comment]
Catching the double and then appending the `.d` back doesn't work by the way and is also way to hacky.

Given that you can just specify e.g. 72.h instead of 3.d we can live without the day version, but the error message might not be very clear to the user unfortunately.

**Comment by ewels** [comment]
Did we solve this by changing how we specify dates in the end?

**Comment by KevinMenden** [comment]
We might have ... wanted to spend some quality time with this issue during the hackathon.
I'm not too worried any more because I didn't run into this in the nextflow plugin tests.

**Comment by ewels** [comment]
Is this fixed by https://github.com/nf-core/tools/pull/974 ?

**Comment by ewels** [comment]
Nope:

```console
$ nextflow run nf-core-testpipeline/ -profile test,docker --max_time 4.d
N E X T F L O W  ~  version 21.03.0-edge
Launching `nf-core-testpipelinee/main.nf` [nauseous_visvesvaraya] - revision: de1773e09a


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/testpipelinee v1.0dev
------------------------------------------------------


ERROR: Validation of pipeline parameters failed!


* --max_time: expected type: String, found: Double (4.0)

```

**Comment by ewels** [comment]
I don't totally understand why `4.d` gives a double and fails but `72.h` works fine..? 🤔

**Comment by KevinMenden** [comment]
Ah thanks for reminding me, need to have a closer look at this ...

I think it's because of the `d`, but that's just a suspicion

**Comment by KevinMenden** [comment]
We could probably the hack from above:

```nextflow
if (p['value'].getClass() == Double) {
    new_params.replace(p.key, p['value'].toString())
}
```
and fix the the resulting string to pass validation. This is as hacky as it gets though ... :/

**Comment by KevinMenden** [comment]
Okay we can catch the parameter internally, fix it so it looks like a proper duration ("4.d") but then it still fails because it's already parsed as double internally and sets to run time limit to a rather short 4ms ...

It get's converted to `4.0` before the parameter validation, somewhere through the Nextflow/Groovy parsing process ...

**Comment by ewels** [comment]
@pditommaso have you seen this before? Nextflow time objects with days being parsed as a numeric double instead?

Sounds like it may be something that should be fixed upstream @KevinMenden..

**Comment by pditommaso** [comment]
I think it conflicts with 'd' literal for double https://stackoverflow.com/a/27368444/395921. `1.day ` works tho. 

Also try to avoid hacks like the following, looks very bad 

```
if (p['value'].getClass() == Double) {
    new_params.replace(p.key, p['value'].toString())
}
```

**Comment by KevinMenden** [comment]
Okay thanks - so then there's really nothing we can do here, except adapting the regex and use `*.day` instead, I guess.

Yes we're not using that, it doesn't really work anyway :) Although we use similar hacks to deal with the nextflow duration objects etc 👀  need to remove them before passing the object to the Schema validator

**Comment by ewels** [comment]
I didn't know about `.day` syntax - ok then yes let's just force people to use that 👍🏻

**Comment by ewels** [comment]
@pditommaso we just implemented this but ran into a problem - if a Nextflow config file uses a native memory variable type then Nextflow will automatically simplify this and uses the `.d` syntax. 

```nextflow
params.some_time = 48.h
println(params.some_time)
```

```console
$ nextflow run mem_test.nf
N E X T F L O W  ~  version 21.03.0-edge
Launching `mem_test.nf` [condescending_panini] - revision: 18bf7ca334
2d
```

So then we're kind of screwed as this then hits the string double parsing issue we see above. But there's nothing that we can do about it..

Is it possible to get Nextflow to use `.day` instead of `.d` as the primary unit type for these conversions?

**Comment by ewels** [comment]
x-ref https://github.com/nextflow-io/nextflow/pull/2038

**Comment by ewels** [comment]
@KevinMenden @drpatelh - can this issue be closed now?

**Comment by drpatelh** [comment]
Yes, I believe we fixed it in these PRs:
https://github.com/nf-core/tools/pull/1012
https://github.com/nf-core/tools/pull/1003
