### ISSUE TITLE
Add linting results to PR as a comment

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#86]
The linting tests give lots of information on pull requests, but you have to dig into the travis results to find them. It would be super cool if we could set up a GitHub app or something which the `nf-core lint` service could use to post a comment with the linting results to the PR directly.

Low priority, but would be fun 🤓

**Comment by ewels** [comment]
This was @senthil10's idea originally 😉

**Comment by MaxUlysse** [comment]
I would love to see that :-D

**Comment by ewels** [comment]
If we use `tee` to save the linting output to a file as well as printing it to Travis, could then have a bash script that runs after the test is finished to post this as a comment to the PR using @nf-core-bot 

Need to ensure that this step always runs though, even if tests fail. Or better still, _only_ if linting fails? (or throws warnings?). Or could parse output somehow to look nicer for a comment.

**Comment by ewels** [comment]
I think that we can close this now that we're moving to GitHub Actions - it's much easier to find the output from specific tasks in this UI. Closing, feel free to reopen if you disagree.
