### ISSUE TITLE
Modules install / lint - add comment explaining origin

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#865]
It would be nice if software wrappers from nf-core/modules could have an explainer comment added when installing into a pipeline. This way, anyone browsing the pipeline code can understand where it comes from and that it shouldn't be edited within the pipeline.

Ideally needs adding at the time of installation (`nf-core modules install` and `nf-core modules update`) and should be expected when the pipeline code is checked (`nf-core lint`).

**Comment by KevinMenden** [comment]
Good idea - where do you want to have this comment? Inside the module file, or inside the pipeline?
Because right now `nf-core modules install` only adds the module code but nothing to the pipeline.

**Comment by ewels** [comment]
Inside the module file, as a code comment at the top of the file I was thinking (maybe for every file ending in `.nf`? Could also do the YAML file?)

Can also have stuff written about this in the pipeline, but that can go out in the template sync as part of the readme or whatever.

**Comment by KevinMenden** [comment]
Okay - should we add a timestamp installed/modified while we're at it?

**Comment by ewels** [comment]
I did wonder the same, but figured that as we're going to have version control via GitHub sha anyway it didn't add much (and makes life _slightly_ more complicated if not a static string).

Seeing as we haven't figured out _how_ we're going to do the git sha thing yet I guess we could combine the two though? For example we could add comment line with a link to the nf-core/modules repo for that file at that commit, as we know all of that information.

**Comment by drpatelh** [comment]
Saw your initial comment and your latest and this is exactly what I think we should do with this too. Been thinking about versioning since for a while now. Maybe a `README.md` per module that contains a link to the commit hash on modules and other info we want to put in it? We can parse this file for version control too?

It would also be great if we are able to add functionality to tools to list all historic git sha for a particular module and maybe a link to visualise the file?

**Comment by KevinMenden** [comment]
Ah yes that's a nice way of doing it .... 

Also I actually like the idea of the `README.md`, although my thirst thought was that we have enough files per module already :grin:  ... but it might actually be useful to have a very short description on how to use a module, e.g. in cases where we applied the optional input hack.

**Comment by ewels** [comment]
Great minds think alike 😅 I was also going to suggest a `README.md` file but then wasn't sure what it would really add beyond a link to the modules repo / file / commit.

Originally I was assuming that version info etc. would go in the YAML file for each module. But actually maybe it makes more sense to keep that separate (as we don't want to maintain it in nf-core/modules) and instead we just make the top line of every file a comment with a link to the file on nf-core/modules. Then yeah, use this as the version control 👍🏻 

> It would also be great if we are able to add functionality to tools to list all historic git sha for a particular module and maybe a link to visualise the file?

Given that GitHub already does a pretty amazing job of both of these things, I'm inclined to say that we just link out to GitHub and delegate this task?

**Comment by drpatelh** [comment]
💥 So I am suggesting that nf-core/tools creates the README and it's not something coming from nf-core/modules where I agree we do have enough files to deal with. Then we don't need to add comments to the top of the files - feels a bit dirty? If there is a README in the repo then I am hoping developers will look at that first anyway?

We could indeed use GitHub but I think we have to assume that not everyone is clued up with how to get that info. Personally, I would much prefer have a single link to click (especially when looking through more than one modules) than navigation through multiple links. Given we have already been asked the question about version control a couple of times it would be a quick get out clause to point to a little helper tool.

**Comment by ewels** [comment]
I think we're making the same points but from different angles 😄 

I was thinking that a `README.md` would be more clicks, as people are likely to get into these files from a search / share etc. So to get to the `README.md` they have to navigate back up a folder and then open the additional file. By having the links at the top of each file, the link is right there however they find the file.

For user-friendliness we can add more links, then stuff is still just a single click away? eg. something like:

```nextflow
// Module from central nf-core/modules repository. DO NOT EDIT! Source:
// https://github.com/nf-core/modules/blob/5fb90932f75b6792a464c792b062cba918fb90f0/software/fastqc/main.nf
//
// See the file history: https://github.com/nf-core/modules/commits/master/software/fastqc/main.nf
// Documentation about nf-core/modules: https://github.com/nf-core/modules
```

> We could indeed use GitHub but I think we have to assume that not everyone is clued up with how to get that info. Personally, I would much prefer have a single link to click (especially when looking through more than one modules) than navigation through multiple links. Given we have already been asked the question about version control a couple of times it would be a quick get out clause to point to a little helper tool.

Maybe I'm not on the same page as what you are imagining here.. Could you sketch out a use case / pseudo commands and output or something?

**Comment by ewels** [comment]
Closing in favour of https://github.com/nf-core/tools/issues/868 after discussion on Slack
