### ISSUE TITLE
Add questionary's autocomplete functionality to more commands

### ISSUE THREAD

**Issue by KevinMenden** [nf-core/tools#885]
The autocomplete functionality of questionary works really nice for `nf-core modules install`([code](https://github.com/nf-core/tools/blob/0d962273916a99b2e7a5b57e25b5a9a8937aeca7/nf_core/modules/pipeline_modules.py#L98-L101))
and should  be used more often, e.g. for the `download` command subcommands of `nf-core modules`

**Comment by ewels** [comment]
There is no `nf-core modules download` command is there? Could we have a list of the commands where we want to implement this in this issue perhaps?

**Comment by KevinMenden** [comment]
Nope, I wasn't specifically talking about modules here :) 

Yep I will make a list of tools where this could be meaningfully implemented 👍

**Comment by ewels** [comment]
I've suggested that @ErikDanielsson can take a stab at this.
