### ISSUE TITLE
Rich formatting for Click help texts

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#897]
Making some stuff pretty with _Rich_ makes everything else look ugly.

The output from `click` when `--help` is used could do with some love. I think this could be of general interest for the Python community too as a lot of people use the two packages together.

Should be able to make a custom Click formatter I think, see https://stackoverflow.com/a/61955663/713980 and https://stackoverflow.com/a/62437850/713980

By looking at the Click source code can hopefully make it functionally the same but with nicer colours etc.

**Comment by ewels** [comment]
Started a discussion to see if this is of general interest here: https://github.com/willmcgugan/rich/discussions/1121

**Comment by Zethson** [comment]
Hey @ewels,

we are already doing this over at mlf-core:
https://github.com/mlf-core/mlf-core/blob/master/mlf_core/custom_cli/click.py


![image](https://user-images.githubusercontent.com/21954664/111871650-90ef6680-898b-11eb-8446-4903cda61b5b.png)

**Comment by ewels** [comment]
Done with `rich-click`!
