### ISSUE TITLE
create-test-yml: move 'work' and '.nextflow*' files to tmp directory

### ISSUE THREAD

**Issue by KevinMenden** [nf-core/tools#908]
Currently, `nf-core modules create-test-yml` creates the "work" directory and ".nextflow" files in the current working directly (which is "modules"). These files should be moved to the tmp directory used for creating the output.

**Comment by KevinMenden** [comment]
Alright I have had another go at this. Essentially there are three things that pollute the CWD, which is the clone of `modules`:

* work
* .nextflow/
* .nextflow.log

It's possible to direct the `.nextflow.log` files to the tmp directories by adding a `-log` directive to the nextflow command before running it. The `work` and `.nextflow/` can't be redirected that way unfortunately, that would require a new `workDir` directive which can only be modified in an additional config file. However we are already using a custom config file via `-c`.
So from what I understand the only solution to clean things up would be to manually remove them.
`nextflow clean -f` doesn't really work either (needs workflow name, doesn't remove the work directory ...).

So this is not super important, I would say we wait until something more elegant from the nextflow side is available, see here for instance:

https://github.com/seqeralabs/nf-tower/issues/279
https://github.com/nextflow-io/nextflow/issues/452

Not sure when this will be available though.

**Comment by ewels** [comment]
I thought that `-w` set the work directory from the command line?

**Comment by KevinMenden** [comment]
😱 
Do you happen to have the part in the nextflow documentation that explains that? I've been looking through but all I could find was the `workDir` directive and search didn't help .... 😏 
I never find stuff on documentation pages.

Well anyway thanks! In that case I guess we could at least direct the `work` dir and the `.nextflow.log` to the tmp-dirs. I think the `.nextflow/` folder will still exist though, but it's better than nothing.

**Comment by ewels** [comment]
Yeah these flags can be tricky to find. `nextflow help run | grep "-w"`? 😅

Not sure about the hidden log dirs, that might be harder as you say..

**Comment by ewels** [comment]
Found it: https://www.nextflow.io/docs/latest/cli.html#run

**Comment by KevinMenden** [comment]
Yeah that works if you know what to look for :P also I just looked at the documentation 😏 

Okay so the search function on that documentation really doesn't work and I am too dumb to search. Alright I guess we can already start adding that to the code, and then it's only the hidden logs left, which is something we can live with for now I'd say 👍

**Comment by drpatelh** [comment]
Closed by https://github.com/nf-core/tools/pull/1098
