### ISSUE TITLE
Versioning for sphinx docs

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#913]
Currently the Sphinx docs on tools are running off `dev`: https://nf-co.re/tools-docs/

It would be great if we could have a version of the docs for each release of tools, plus dev. That way the docs for the lint tests etc. can be viewed for the version that is relevant for the end user.

**Comment by ewels** [comment]
ok, so after discussion with we have said that we will go for a strategy where we build on GitHub Actions and push the files to the website via FTP.

So currently the URL is: https://nf-co.re/tools-docs/

I think that we should change this to https://nf-co.re/tools/docs/[VERSION]/

I will also play around with the website header nav I think, I don't like how it works currently.

**Comment by ewels** [comment]
@mashehu any thoughts on the website stuff?

@ErikDanielsson I will set up the FTP credentials as secrets and you can build the GitHub Actions workflow 👍🏻

**Comment by ewels** [comment]
Path will be `public_html/tools/docs/[VERSION]`

**Comment by ewels** [comment]
Action should be triggered on release, with that version name. Also on every push to `dev` with version name `dev`. That should overwrite.

**Comment by ewels** [comment]
Can also have `latest` - overwritten for each release.

**Comment by mashehu** [comment]
yes, i was also confused for a bit that it is under "lint error codes", but links to the general docs.

If we do versioned, should we have a disclaimer, if somebody is looking at an older version of the docs?

**Comment by ewels** [comment]
We could do, but to be honest that might be quite difficult with the above approach as they will only be built once and that's what it will be the latest release. To do a disclaimer we would need to rebuild old docs each time (possible) or have some kind of injected header.

Regarding the latter - I have previously wondered about just rendering a "core" HTML fragment without a `<head>` etc, then rendering that within the website PHP header + footer. Then it would be easy to do stuff like show warnings, and would mean that we could maintain the CSS in the website repo instead for cross-version updates etc. Do you think that would be possible @mashehu?

**Comment by mashehu** [comment]
sounds like a good approach (I haven't used sphinx enough to see if that works, but worst case we filder the `<head>` out in the php. But I don't think the CSS can really be streamlined like that, due to the difference in elements and classes sphinx produces.

**Comment by MaxUlysse** [comment]
I had no idea we had sphinx docs...
:facepalm: 
But I love that
