### ISSUE TITLE
Make docker image for nf-core/tools

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#917]
We have a root level `Dockerfile` in the tools repo which automatically builds at Docker Hub but it's the `nfcore/base` one that is used as a base for pipeline images: https://hub.docker.com/repository/docker/nfcore/base

It would be good to also write a Dockerfile that builds the nf-core/tools package into an image that people can use (yes I know, it should be on BioContainers too, but doing `docker run nfcore/tools` is nicer).

* [ ] Build a `Dockerfile` for tools which has as small a footprint as possible
* [ ] Organise `Dockerfiles` into directories so we can have both base and tools
* [ ] Remove DockerHub automated builds
* [ ] Write GitHub Actions builds + push to DockerHub
* [ ] Write some documentation

**Comment by phue** [comment]
Could be worth considering [micromamba](https://hub.docker.com/r/mambaorg/micromamba) as base image for the container builds. Its size is currently just `31MB` (vs `150MB` for the miniconda base image)

**Comment by ewels** [comment]
Yup, I was also wondering about just not using conda. I build the MultiQC image using pip and it's pretty small I think. Maybe also using multistage builds?

Also need to install Nextflow into this image and check around for any other dependencies.. 🤔

**Comment by ewels** [comment]
Done in https://github.com/nf-core/tools/pull/996 - needs checking that the image works! 'cc @ErikDanielsson

**Comment by ewels** [comment]
Docs: https://github.com/nf-core/tools/blob/bf83b05745d094ac922499f15b29374c9ff2f16c/README.md#docker-image
