### ISSUE TITLE
Patches for "nf-core modules"

### ISSUE THREAD

**Issue by KevinMenden** [nf-core/tools#918]
This is a list of relatively small things to address in the next release, collected from Slack.

`nf-core modules lint`
- [x] sort by error, then name of module
- [x] re-order columns -> module name, file path, test result
- [x] fix bug with `./software/functions.nf` not being a directory

Let's add more things here if we can find anything and try to address them before the patch release.

**Comment by drpatelh** [comment]
This is all I have spotted so far 🙂 Let me know if you want me to test.

**Comment by KevinMenden** [comment]
Great - that sounds doable!
I'll probably make single PRs for each of those. Will ping you!

**Comment by KevinMenden** [comment]
More: 

- [ ] removing emit statements doesn't lead to failure
- [ ] conda version parsing not robust
- [ ] file path not outputted for failurs

**Comment by KevinMenden** [comment]
https://github.com/nf-core/tools/pull/919

**Comment by KevinMenden** [comment]
Others:

- [ ] issue warning when `tag` is missing
- [ ] safer `test.yml` parsing
