### ISSUE TITLE
Lint check for for `dsl2.enabled` - also sync behaviour?

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#929]
This relies on the DSLv2 template being merged of course. 

Once this has happened, we should maybe consider having a quick check and not open any further sync PRs for such pipelines that were not (yet) converted to DSLv2. 

This is just a reminder to keep this in mind :-)

**Comment by ewels** [comment]
I disagree - I think that we should continue with the sync PRs as it will help push people towards the conversion.

We should maybe add a `nf-core lint` check for DSL2, plus essential DSL2 files in the template.

DSL1 pipelines will continue to work, but for standardisation we want to push everyone to DSL2.

**Comment by apeltzer** [comment]
Looking at it from that perspective, it might just happen that older pipelines will be kind of force-pushed to upgrade ;-) Fine by me, was just wondering whether we really want to do that or have a flag as described above.

**Comment by apeltzer** [comment]
I can see the benefits though, and its not very likely that there will be another such a breaking change as with DSLv1-DSLV2 anytime soon I guess 🤔

**Comment by ewels** [comment]
Yeah we discussed this a while back and decided that when we switch to DSL2 we go all in. Too much trouble to try to maintain both I think. After all, we're all about standardisation right? :)

**Comment by drpatelh** [comment]
We went all in so no need for this anymore I think? Will close for now.
