### ISSUE TITLE
AWSBatch Configuration

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#99]
_From @apeltzer on August 2, 2018 13:6_

Hi!

I think we could have a generic AWSBatch configuration in cookiecutter. 

Did so for ICGC-featureCounts but we could use a similar way (open for ideas if thats not optimal in your opinion):

AWSBatch config:

https://github.com/nf-core/ICGC-featureCounts/blob/master/conf/awsbatch.config

Main Nextflow.config / setting some defaults:
https://github.com/nf-core/ICGC-featureCounts/blob/master/nextflow.config

And then allowing users to specify the required params /also using that in the summary if the proper profile is used:

https://github.com/nf-core/ICGC-featureCounts/blob/4929959b77d13169a8c96ef4abec3ff8b8af314e/main.nf#L138

I guess this could as well be extrapolated to other pipelines easily and could be in cookiecutter therefore!

I'd be happy to contribute that but would like to have some more feedback/ideas on this before moving on... 

_Copied from original issue: nf-core/cookiecutter#48_

**Comment by ewels** [comment]
_From @MaxUlysse on August 2, 2018 13:15_

I would love to see that as well

**Comment by ewels** [comment]
_From @apeltzer on August 2, 2018 13:30_

cross linking an example here, which even checks for the params in the `main.nf` https://github.com/nf-core/rnaseq/pull/42

**Comment by apeltzer** [comment]
I think this can actually be closed and is present already now?! 

check https://github.com/nf-core/tools/blob/6dc0f1609acd521a6c5b8a93486669fd4476be89/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/main.nf#L41 (for example, config is also present and in the `nextflow.config` file.
